[package]
name = "pdbiox-xtal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Assemblies, symmetry and crystallographic transforms for pdbiox"

[dependencies]
num-traits.workspace = true
pdbiox-core.workspace = true
pdbiox-cif.workspace = true
pdbiox-geom.workspace = true
pdbiox-spatial.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
pdbiox-bench.workspace = true

[[bench]]
name = "xtal"
harness = false

[lints]
workspace = true
