from typing import final
from numpy import uint32
from numpy.typing import NDArray
from ..core import Structure
from ..audit import (AlignmentPolicy, ContactDefinition, EquivalencePolicy,
    HydrogenPolicy, PeriodicPolicy, Precision, SymmetryPolicy, Tolerance)
from ..chem import RadiusSet
@final
class Namespace:
    Label: Namespace
    Auth: Namespace
    Explicit: Namespace

@final
class MissingPolicy:
    Ignore: MissingPolicy
    Report: MissingPolicy
    Indeterminate: MissingPolicy
    Fail: MissingPolicy

@final
class ModelChoice:
    @staticmethod
    def first() -> ModelChoice: ...
    @staticmethod
    def index(index: int) -> ModelChoice: ...
    @staticmethod
    def all() -> ModelChoice: ...
    @staticmethod
    def ensemble() -> ModelChoice: ...

@final
class AltlocPolicy:
    @staticmethod
    def keep_all() -> AltlocPolicy: ...
    @staticmethod
    def conformer_consistent() -> AltlocPolicy: ...
    @staticmethod
    def label(label: str) -> AltlocPolicy: ...
    @staticmethod
    def first() -> AltlocPolicy: ...
    @staticmethod
    def highest_occupancy_per_residue() -> AltlocPolicy: ...
    @staticmethod
    def highest_occupancy_per_atom() -> AltlocPolicy: ...

@final
class AssemblyChoice:
    @staticmethod
    def asymmetric_unit() -> AssemblyChoice: ...
    @staticmethod
    def biological(identifier: str) -> AssemblyChoice: ...
    @staticmethod
    def crystal(radius: float) -> AssemblyChoice: ...

@final
class AnalysisPolicy:
    def __init__(self, *, assembly: AssemblyChoice | None = None, model: ModelChoice | None = None, altloc: AltlocPolicy | None = None, identifiers: Namespace = Namespace.Auth, missing_atoms: MissingPolicy = MissingPolicy.Report, hydrogens: HydrogenPolicy | None = None, atom_equivalence: EquivalencePolicy | None = None, symmetry: SymmetryPolicy | None = None, alignment: AlignmentPolicy | None = None, precision: Precision | None = None, periodic: PeriodicPolicy | None = None, vdw_radii: RadiusSet | None = None, contact_def: ContactDefinition | None = None, float_tolerance: Tolerance | None = None) -> None: ...
    @property
    def fingerprint(self) -> str: ...
    assembly: AssemblyChoice
    model: ModelChoice
    altloc: AltlocPolicy
    identifiers: Namespace
    missing_atoms: MissingPolicy
    hydrogens: HydrogenPolicy
    atom_equivalence: EquivalencePolicy
    symmetry: SymmetryPolicy
    alignment: AlignmentPolicy
    precision: Precision
    periodic: PeriodicPolicy
    vdw_radii: RadiusSet
    contact_def: ContactDefinition
    float_tolerance: Tolerance

@final
class Selection:
    def __init__(self, indices: list[int]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, index: int) -> bool: ...
    @property
    def indices(self) -> NDArray[uint32]: ...
    def intersect(self, other: Selection) -> Selection: ...
    def union(self, other: Selection) -> Selection: ...
    def difference(self, other: Selection) -> Selection: ...
    def complement(self, atom_count: int) -> Selection: ...

@final
class Evaluation:
    selection: Selection
    warnings: list[object]

@final
class Query:
    def __init__(self, source: str) -> None: ...
    @staticmethod
    def from_builder(builder: QueryBuilder) -> Query: ...
    def logical_plan(self) -> LogicalPlan: ...
    def plan(self, structure: Structure, *, policy: AnalysisPolicy | None = ...) -> PhysicalQuery: ...

@final
class LogicalPlan:
    def __repr__(self) -> str: ...

@final
class PhysicalQuery:
    def execute(self, *, groups: dict[str, Selection] | None = ...) -> Evaluation: ...

class SelectQuery:
    def __init__(self, *, query: Query, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Evaluation: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> SelectQuery: ...
    def __repr__(self) -> str: ...

@final
class QueryBuilder:
    def query(self) -> Query: ...
    def __and__(self, right: QueryBuilder) -> QueryBuilder: ...
    def __or__(self, right: QueryBuilder) -> QueryBuilder: ...
    def __invert__(self) -> QueryBuilder: ...

Builder = QueryBuilder

@final
class ColumnBuilder:
    def eq(self, value: str) -> QueryBuilder: ...
    def lt(self, value: float) -> QueryBuilder: ...
    def le(self, value: float) -> QueryBuilder: ...
    def gt(self, value: float) -> QueryBuilder: ...
    def ge(self, value: float) -> QueryBuilder: ...

@final
class Columns:
    @staticmethod
    def all() -> QueryBuilder: ...
    @staticmethod
    def none() -> QueryBuilder: ...
    @staticmethod
    def is_protein() -> QueryBuilder: ...
    @staticmethod
    def name() -> ColumnBuilder: ...
    @staticmethod
    def resname() -> ColumnBuilder: ...
    @staticmethod
    def chain() -> ColumnBuilder: ...
    @staticmethod
    def bfactor() -> ColumnBuilder: ...
    @staticmethod
    def occupancy() -> ColumnBuilder: ...
    @staticmethod
    def x() -> ColumnBuilder: ...
    @staticmethod
    def within(radius: float, target: QueryBuilder) -> QueryBuilder: ...
    @staticmethod
    def by_residue(target: QueryBuilder) -> QueryBuilder: ...

col: Columns
