from __future__ import annotations
from typing import Protocol

class Coordinates(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class DistanceMatrix(Protocol):
    @property
    def shape(self) -> tuple[int, int]: ...

def centroid(coordinates: Coordinates) -> tuple[float, float, float] | None: ...
def distance_matrix(coordinates: Coordinates) -> DistanceMatrix: ...
def rmsd(mobile: Coordinates, reference: Coordinates) -> float: ...
