from typing import Protocol

class Coordinates(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class DistanceMatrix(Protocol):
    @property
    def shape(self) -> tuple[int, int]: ...

class Vector(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class Superposition:
    """A rigid transform ``R @ x + t`` and the deviation it achieves."""

    @property
    def rotation(self) -> Coordinates: ...
    @property
    def translation(self) -> tuple[float, float, float]: ...
    @property
    def rmsd(self) -> float: ...
    def apply(self, positions: Coordinates) -> Coordinates: ...

def centroid(coordinates: Coordinates) -> tuple[float, float, float] | None: ...
def distance_matrix(coordinates: Coordinates) -> DistanceMatrix: ...
def rmsd(mobile: Coordinates, reference: Coordinates) -> float: ...
def distances(left: Coordinates, right: Coordinates) -> Vector:
    """Distances between corresponding rows, in Å."""

def angles(first: Coordinates, vertex: Coordinates, third: Coordinates) -> Vector:
    """Angles at ``vertex`` in degrees; ``NaN`` where undefined."""

def dihedrals(
    first: Coordinates, second: Coordinates, third: Coordinates, fourth: Coordinates
) -> Vector:
    """Signed torsions in degrees in ``(-180, 180]``; ``NaN`` where undefined."""

def centre_of_mass(
    positions: Coordinates, masses: Vector | None = None
) -> tuple[float, float, float] | None: ...
def radius_of_gyration(positions: Coordinates, masses: Vector | None = None) -> float | None: ...
def inertia_tensor(positions: Coordinates, masses: Vector | None = None) -> Coordinates | None: ...
def principal_axes(
    positions: Coordinates, masses: Vector | None = None
) -> tuple[Vector, Coordinates] | None:
    """Principal moments and axes (as columns), longest first."""

def gyration_axes(positions: Coordinates) -> tuple[Vector, Coordinates] | None: ...
def asphericity(positions: Coordinates) -> float | None: ...
def shape_parameter(positions: Coordinates) -> float | None: ...
def best_fit_plane(
    points: Coordinates,
) -> tuple[tuple[float, float, float], tuple[float, float, float]] | None:
    """Fit the plane through at least three points: ``(centre, normal)``."""

def plane_deviation(points: Coordinates) -> float | None: ...
def rmsd_after_fit(mobile: Coordinates, reference: Coordinates) -> float: ...
def superpose(mobile: Coordinates, reference: Coordinates) -> Superposition: ...
def rmsf(positions: Coordinates) -> Vector:
    """Per-atom fluctuation about the mean over ``(frames, atoms, 3)`` positions, in Å."""
