
from __future__ import annotations

from collections.abc import Mapping
from os import PathLike
from types import ModuleType
from typing import Literal, Protocol

from . import sel as sel

class Float32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class UInt32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class AnalysisPolicy:
    def __init__(
        self,
        *,
        identifiers: Literal["label", "auth", "explicit"] | None = None,
        altloc: str | None = None,
        missing_atoms: Literal["ignore", "report", "indeterminate", "fail"] | None = None,
        hydrogens: Literal["explicit_only", "include_inferred", "exclude"] | None = None,
        symmetry: Literal["none", "crystallographic", "biological_assembly"] | None = None,
        vdw_radii: Literal["bondi", "amber_united", "charmm", "alvarez"] | None = None,
        precision: Literal["f32", "f64"] | None = None,
    ) -> None: ...
    @property
    def identifiers(self) -> str: ...
    @property
    def altloc(self) -> str: ...
    @property
    def missing_atoms(self) -> str: ...
    @property
    def hydrogens(self) -> str: ...
    @property
    def symmetry(self) -> str: ...
    @property
    def vdw_radii(self) -> str: ...
    @property
    def precision(self) -> str: ...
    @property
    def profile(self) -> str | None: ...
    @property
    def fingerprint(self) -> str: ...

class Structure:
    @property
    def atom_count(self) -> int: ...
    @property
    def residue_count(self) -> int: ...
    @property
    def chain_count(self) -> int: ...
    @property
    def model_count(self) -> int: ...
    @property
    def atoms(self) -> Atoms: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def models(self) -> Models: ...
    @property
    def coordinates(self) -> Float32Array: ...
    def select(
        self, query: str | Query, *, policy: AnalysisPolicy | None = ...
    ) -> Selection: ...
    def edit(self) -> StructureEditor: ...
    @property
    def bond_count(self) -> int: ...
    def infer_bonds(self, *, scale: float = ..., lower_bound: float = ..., across_chains: bool = ...) -> Structure: ...

class Atom:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def coordinate(self) -> tuple[float, float, float] | None: ...
    @property
    def component_name(self) -> str | None: ...
    @property
    def residue(self) -> Residue | None: ...
class Atoms:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...

class Residue:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def atoms(self) -> Atoms: ...
    def atom(self, name: str) -> Atom | None: ...

class ResidueSelection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...

class Residues:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...

class Chain:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> str | None: ...
    @property
    def residues(self) -> Residues: ...

class Chains:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Chain: ...

class Model:
    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int | None: ...
    @property
    def chains(self) -> Chains: ...

class Models:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Model: ...

class StructureEditor:
    def rename_chain(self, chain: int, label: str) -> None: ...
    def finish(self) -> Structure: ...

class Selection:
    def __len__(self) -> int: ...
    @property
    def indices(self) -> UInt32Array: ...
    def is_stale_for(self, structure: Structure) -> bool: ...
    def to_coordinates(self, *, model: int = ...) -> Float32Array: ...
    def residues(self, structure: Structure | None = ...) -> ResidueSelection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __and__(self, other: Selection) -> Selection: ...
    def __sub__(self, other: Selection) -> Selection: ...

class Query:
    def __init__(self, source: str) -> None: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def references(self) -> list[str]: ...
    def select(
        self, structure: Structure, *, policy: AnalysisPolicy | None = ...
    ) -> Selection: ...
    def __and__(self, other: Query) -> Query: ...
    def __or__(self, other: Query) -> Query: ...
    def __invert__(self) -> Query: ...

class QueryError(ValueError):
    """A selection query that cannot be compiled or evaluated.

    The message quotes the query, underlines the offending token, and names
    the details and the remedy.
    """

class QueryWarning(UserWarning):
    """A selection query that is valid but probably not what was meant."""

class QueryAliases:
    def __init__(self) -> None: ...
    def define(self, name: str, query: Query) -> Query | None: ...
    def remove(self, name: str) -> Query | None: ...
    def get(self, name: str) -> Query | None: ...
    @property
    def names(self) -> list[str]: ...
    def resolve(self, query: Query) -> Query: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...

class Reader:
    def __init__(self, data: bytes, *, name: str | None = ...) -> None: ...
    @property
    def byte_length(self) -> int: ...
    def read(self) -> Structure: ...

class WorkflowNode: ...

class Workflow:
    def input(
        self,
        name: str,
        *,
        kind: Literal["coordinates", "float", "structure"],
        cost: Literal["borrow", "adopt", "decode", "copy", "materialize"] = ...,
    ) -> WorkflowNode: ...
    def centroid(self, coordinates: WorkflowNode) -> WorkflowNode: ...
    def rmsd(self, mobile: WorkflowNode, reference: WorkflowNode) -> WorkflowNode: ...
    def distance_matrix(self, coordinates: WorkflowNode) -> WorkflowNode: ...
    def atom_contacts(self, structure: WorkflowNode, cutoff: float) -> WorkflowNode: ...
    def output(self, name: str, node: WorkflowNode) -> None: ...
    def compile(self) -> CompiledWorkflow: ...

class CompiledWorkflow:
    def run(self, values: Mapping[str, object], *, copy: bool = ...) -> dict[str, object]: ...
    def explain(self) -> dict[str, object]: ...

__version__: str

class QueryNamespace:
    def complete(
        self,
        source: str,
        cursor: int,
        aliases: QueryAliases | None = ...,
        structure: Structure | None = ...,
    ) -> tuple[int, int, list[tuple[str, str]]]: ...

def read(source: str | PathLike[str] | bytes, *, name: str | None = ...) -> Structure: ...

analysis: ModuleType
chemistry: ModuleType
compare: ModuleType
crystal: ModuleType
formats: ModuleType
geometry: ModuleType
motif: ModuleType
query: QueryNamespace
sequence: ModuleType
spatial: ModuleType
surface: ModuleType
trajectory: ModuleType
validation: ModuleType
