from collections.abc import Mapping
from os import PathLike
from typing import ClassVar, Generic, Literal, Protocol, TypeVar

from . import (
    analysis as analysis,
    chemistry as chemistry,
    compare as compare,
    crystal as crystal,
    errors as errors,
    formats as formats,
    geometry as geometry,
    motif as motif,
    query as query,
    sel as sel,
    sequence as sequence,
    spatial as spatial,
    surface as surface,
    trajectory as trajectory,
    validation as validation,
)
from .errors import (
    Cancelled as Cancelled,
    ConsistencyError as ConsistencyError,
    ConversionError as ConversionError,
    Diagnostic as Diagnostic,
    GeometryError as GeometryError,
    InternalError as InternalError,
    MemoryBudgetError as MemoryBudgetError,
    MolframeError as MolframeError,
    MolframeIndexError as MolframeIndexError,
    MolframeIOError as MolframeIOError,
    MolframeKeyError as MolframeKeyError,
    MolframeTypeError as MolframeTypeError,
    MolframeValueError as MolframeValueError,
    MolframeWarning as MolframeWarning,
    ParseError as ParseError,
    PolicyError as PolicyError,
    QueryError as QueryError,
    QueryWarning as QueryWarning,
    ResourceError as ResourceError,
    SchemaError as SchemaError,
)

_T_co = TypeVar("_T_co", covariant=True)

class Float32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class UInt32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class Coverage:
    @property
    def intended(self) -> int: ...
    @property
    def used(self) -> int: ...
    @property
    def missing(self) -> int: ...
    @property
    def ambiguous(self) -> int: ...
    @property
    def fraction(self) -> float: ...

class Analysis(Generic[_T_co]):
    @property
    def value(self) -> _T_co: ...
    @property
    def status(self) -> Literal["complete", "partial", "ambiguous", "indeterminate"]: ...
    @property
    def coverage(self) -> Coverage: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def assumptions(self) -> list[str]: ...
    @property
    def provenance(self) -> str: ...
    @property
    def profile(self) -> str | None: ...

class Table:
    def __len__(self) -> int: ...
    @property
    def names(self) -> list[str]: ...
    def __getitem__(self, name: str) -> Float32Array | UInt32Array: ...
    def __contains__(self, name: str) -> bool: ...
    def to_dict(self) -> dict[str, Float32Array | UInt32Array]: ...

class AnalysisPolicy:
    def __init__(
        self,
        *,
        identifiers: Literal["label", "auth", "explicit"] | None = None,
        altloc: str | None = None,
        missing_atoms: Literal["ignore", "report", "indeterminate", "fail"] | None = None,
        hydrogens: Literal["explicit_only", "include_inferred", "exclude"] | None = None,
        symmetry: Literal["none", "crystallographic", "biological_assembly"] | None = None,
        vdw_radii: Literal["bondi", "amber_united", "charmm", "alvarez"] | None = None,
        precision: Literal["f32", "f64"] | None = None,
    ) -> None: ...
    @property
    def identifiers(self) -> str: ...
    @property
    def altloc(self) -> str: ...
    @property
    def missing_atoms(self) -> str: ...
    @property
    def hydrogens(self) -> str: ...
    @property
    def symmetry(self) -> str: ...
    @property
    def vdw_radii(self) -> str: ...
    @property
    def precision(self) -> str: ...
    @property
    def profile(self) -> str | None: ...
    @property
    def fingerprint(self) -> str: ...

class SecondaryStructure:
    Unknown: ClassVar[SecondaryStructure]
    Coil: ClassVar[SecondaryStructure]
    AlphaHelix: ClassVar[SecondaryStructure]
    Strand: ClassVar[SecondaryStructure]
    Turn: ClassVar[SecondaryStructure]
    ThreeTenHelix: ClassVar[SecondaryStructure]
    PiHelix: ClassVar[SecondaryStructure]
    OtherHelix: ClassVar[SecondaryStructure]
    BetaBridge: ClassVar[SecondaryStructure]
    Bend: ClassVar[SecondaryStructure]
    PolyProline: ClassVar[SecondaryStructure]
    def __int__(self) -> int: ...
    def is_helix(self) -> bool: ...
    def is_strand(self) -> bool: ...
    def is_sheet_like(self) -> bool: ...

class Structure:
    @property
    def atom_count(self) -> int: ...
    @property
    def residue_count(self) -> int: ...
    @property
    def chain_count(self) -> int: ...
    @property
    def model_count(self) -> int: ...
    @property
    def atoms(self) -> Atoms: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def models(self) -> Models: ...
    @property
    def coordinates(self) -> Float32Array: ...
    def select(self, query: str | Query, *, policy: AnalysisPolicy | None = ...) -> Selection: ...
    def edit(self) -> StructureEditor: ...
    @property
    def bond_count(self) -> int: ...
    @property
    def secondary_structure(self) -> list[SecondaryStructure]: ...
    def infer_bonds(
        self,
        *,
        scale: float = ...,
        lower_bound: float = ...,
        across_chains: bool = ...,
        context: ExecutionContext | None = None,
    ) -> Structure: ...

class Atom:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def coordinate(self) -> tuple[float, float, float] | None: ...
    @property
    def component_name(self) -> str | None: ...
    @property
    def residue(self) -> Residue | None: ...

class Atoms:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...

class Residue:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def atoms(self) -> Atoms: ...
    def atom(self, name: str) -> Atom | None: ...

class ResidueSelection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...

class Residues:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...

class Chain:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> str | None: ...
    @property
    def residues(self) -> Residues: ...

class Chains:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Chain: ...

class Model:
    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int | None: ...
    @property
    def chains(self) -> Chains: ...

class Models:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Model: ...

class StructureEditor:
    def rename_chain(self, chain: int, label: str) -> None: ...
    def finish(self) -> Structure: ...

class Selection:
    def __len__(self) -> int: ...
    @property
    def indices(self) -> UInt32Array: ...
    def is_stale_for(self, structure: Structure) -> bool: ...
    def to_coordinates(self, *, model: int = ...) -> Float32Array: ...
    def residues(self, structure: Structure | None = ...) -> ResidueSelection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __and__(self, other: Selection) -> Selection: ...
    def __sub__(self, other: Selection) -> Selection: ...

class Query:
    def __init__(self, source: str) -> None: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def references(self) -> list[str]: ...
    def select(self, structure: Structure, *, policy: AnalysisPolicy | None = ...) -> Selection: ...
    def __and__(self, other: Query) -> Query: ...
    def __or__(self, other: Query) -> Query: ...
    def __invert__(self) -> Query: ...

class ExecutionContext:
    """Limits and a cancellation switch for the operations run under them.

    Omitted limits keep the library's bounded defaults. A context describes
    limits and can govern many calls at once; ``cancel()`` stops whichever are
    running, and they raise :class:`Cancelled`. Ctrl-C reaches any operation that
    takes ``context=`` as cancellation and surfaces as ``KeyboardInterrupt``.
    """

    def __init__(
        self,
        *,
        workers: int | None = None,
        memory_budget: int | None = None,
        scratch_bytes: int = 0,
        temp_directory: str | PathLike[str] | None = None,
        temp_bytes: int = 0,
    ) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...
    @property
    def workers(self) -> int | None: ...
    @property
    def memory_budget(self) -> int | None: ...
    @property
    def scratch_bytes(self) -> int: ...
    @property
    def temp_directory(self) -> str | None: ...
    @property
    def temp_bytes(self) -> int: ...

class QueryAliases:
    def __init__(self) -> None: ...
    def define(self, name: str, query: Query) -> Query | None: ...
    def remove(self, name: str) -> Query | None: ...
    def get(self, name: str) -> Query | None: ...
    @property
    def names(self) -> list[str]: ...
    def resolve(self, query: Query) -> Query: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...

class Reader:
    def __init__(self, data: bytes, *, name: str | None = ...) -> None: ...
    @property
    def byte_length(self) -> int: ...
    def read(self) -> Structure: ...

class WorkflowNode: ...

class Workflow:
    def input(
        self,
        name: str,
        *,
        kind: Literal["coordinates", "float", "structure"],
        cost: Literal["borrow", "adopt", "decode", "copy", "materialize"] = ...,
    ) -> WorkflowNode: ...
    def centroid(self, coordinates: WorkflowNode) -> WorkflowNode: ...
    def rmsd(self, mobile: WorkflowNode, reference: WorkflowNode) -> WorkflowNode: ...
    def distance_matrix(self, coordinates: WorkflowNode) -> WorkflowNode: ...
    def atom_contacts(self, structure: WorkflowNode, cutoff: float) -> WorkflowNode: ...
    def output(self, name: str, node: WorkflowNode) -> None: ...
    def compile(self) -> CompiledWorkflow: ...

class CompiledWorkflow:
    def run(
        self,
        values: Mapping[str, object],
        *,
        copy: bool = ...,
        context: ExecutionContext | None = None,
    ) -> dict[str, object]: ...
    def explain(self) -> dict[str, object]: ...

__version__: str

def read(source: str | PathLike[str] | bytes, *, name: str | None = ...) -> Structure: ...
