"""Python bindings for molframe."""

from . import (
    adapters,
    analysis,
    audit,
    bcif,
    cif,
    chem,
    compare,
    core,
    geom,
    fx,
    ic,
    ml,
    modelcif,
    pdb,
    query,
    seq,
    spatial,
    surface,
    traj,
    validate,
    xtal,
)
from .core import (
    AROMATIC_ATOM_ANNOTATION, ATOM_RADIUS_ANNOTATION, AUTODOCK_TYPE_ANNOTATION,
    COMPONENT_KIND_ANNOTATION, FORMAL_CHARGE_ANNOTATION, HBOND_ACCEPTOR_ANNOTATION,
    HBOND_DONOR_ANNOTATION, PAE_ANNOTATION, PARTIAL_CHARGE_ANNOTATION, PLDDT_ANNOTATION,
    POLYMER_ATOM_ROLE_ANNOTATION, SEGMENT_ID_ANNOTATION, STEREO_CONFIGURATION_ANNOTATION,
    Aabb, AltId, AlgorithmId, AnalysisParameters, AnnotationColumn, AtomAnnotation, AtomAnnotations, AtomChunk, AtomChunkStats,
    AtomRecord, BitVec, BondAdjacency, ChainRecord, ChainTable, ChunkBuilder, ColumnKind,
    CoordinateStore, EncodedColumn, ElementMask, EntityTable, ExtensionStore, Extremes,
    BondOrder, BondProvenance, BondRecord, BondTable,
    BondTableBuilder, ByteSpan, CoordinateBlock,
    CoordinateGeneration, DictionaryFull, DictionaryVersion, DifferenceError, ExecutionContext, Fingerprint,
    DatasetId, ChunkId, LogicalRow, LocalRow, PayloadKind, ChunkLayout,
    ChunkDescriptor, DatasetDescriptor, DatasetCatalog, PropertyKind, PropertyValue,
    AtomEndpoint, BondChunk, BondChunkRecord, StructureChunk, PropertyChunk, FrameChunk,
    BondChunkProvider, StructureChunkProvider,
    PropertyChunkProvider, FrameChunkProvider, ProviderError,
    Interner, MissingResidue, ModelTable, OptionalI32, OptionalSymbol, ParameterValue, ParentMapping, Position, Presence,
    ProfileId, SourceRef, StructureDifferenceOptions, ValueDifference,
    ResidueRecord, ResidueTable, StructureData, StructureView, StructureEditor, CoordinateEditor,
    AtomSelection, Class, Code, ContextItem, Diagnostics, Kind, Rendered, Severity, Strictness,
    SymbolId, TARGET_CHUNK_ATOMS, TARGET_CHUNK_BONDS, Topology, ValidityMask,
    bit_width, pack, unpack_one, write_output,
    OutputOptions, DEFAULT_OUTPUT_MEMORY_LIMIT_BYTES,
)
from .audit import (
    AlignmentPolicy, AuditPlan, AuditReport, AuditRun, ContactDefinition,
    DimensionSensitivity, EquivalencePolicy, HydrogenPolicy, PeriodicPolicy,
    PlanError, PolicyDimension, PolicyField, PolicySpace, PolicyValue, Precision,
    SensitiveItem, SymmetryPolicy, Tolerance,
)
from ._native import (
    AmbiguousResidueBoundaryPolicy,
    Contacts,
    AffineTransform,
    ApplicationConfiguration,
    AssemblyDef,
    AssemblyNeighbor,
    AssemblySet,
    AssemblyView,
    Atom,
    AtomIndex,
    Atoms,
    BackboneTorsionRecord,
    BondInference,
    BondInferenceReport,
    BondIndex,
    Bonds,
    Chain,
    ChainIndex,
    ChainInstance,
    Chains,
    Category,
    ASSEMBLIES_EXTENSION,
    CadConstructionError,
    CadError,
    CeError,
    CompareError,
    CifValue,
    CifWriteError,
    CifWriteOptions,
    ChemistryConfiguration,
    ConsistencyError,
    ConversionError,
    CoordinateEdit,
    CellTransform,
    CountDifference,
    Column,
    GeometryError,
    GovernedCompareError,
    Format,
    Limits,
    MissingElementPolicy,
    Model,
    ModelIndex,
    Models,
    ParseError,
    ParseMode,
    PdbIdentifierNamespace,
    PdbOptions,
    PdbWriteOptions,
    PdbHeaderRecord,
    PdbHeaders,
    MmtfEntityMetadata,
    MmtfGroupMetadata,
    MmtfMetadata,
    MmtfOptionalField,
    MMTF_METADATA_EXTENSION,
    MODEL_CIF_EXTENSION,
    PDB_HEADERS_EXTENSION,
    MolframeError,
    PolicyConfigError,
    MolframeIndexError,
    MolframeKeyError,
    Plan,
    PlanResult,
    RadialDistribution,
    CoordinationNumbers,
    Leaflets,
    LinearDensity,
    PoreProfile,
    SurfaceContacts,
    PolicyError,
    PeriodicAngle,
    Rotation3,
    Rmsd,
    Lddt,
    TmScore,
    GdtTs,
    GdtHa,
    SurfaceMesh,
    ProteinAlphaTrace,
    SideChainTorsionRecord,
    SideChainTorsionReport,
    Trajectory,
    TrajectoryFormat,
    TrajectoryUnits,
    TrajectoryWriteOptions,
    XyzAtom,
    XyzFrame,
    PcaResult,
    DiffusionMap,
    BatFrame,
    BcifReader,
    BinaryDocument,
    Dihedron,
    DmsBond,
    DmsCell,
    DmsFrame,
    DmsParticle,
    DmsSystem,
    DmsTopology,
    DmsVersion,
    read_dms,
    write_dms,
    EntityIndex,
    InstanceId,
    INSTANCE_ID_ANNOTATION,
    EntityKind,
    EntryMetadata,
    Document,
    AtomInstance,
    CrystalNeighbor,
    Generator,
    DataBlock,
    Hedron,
    InternalAtom,
    InternalCoordinates,
    GlobalMetric,
    LocalMetric,
    MetricDefinition,
    ModelCategory,
    ModelCif,
    ModelDescription,
    ModelRow,
    NcsCode,
    NCS_EXTENSION,
    NcsOperator,
    NcsSet,
    NcsView,
    OperExpression,
    Operator,
    OutputConfiguration,
    PairwiseMetric,
    PolicyOverrides,
    ProtocolStep,
    QualityMetrics,
    Rational,
    SpaceGroupSetting,
    ResidueIndex,
    SoftwareGroup,
    Target,
    Template,
    Residue,
    ResidueAtoms,
    Residues,
    ReadOptions,
    ReadReport,
    ReadScope,
    SchemaError,
    Structure,
    SequenceMapping,
    SequenceReferences,
    SEQUENCE_REFERENCES_EXTENSION,
    ReferenceAlignment,
    ReferenceSequence,
    PolymerKind,
    MetadataDifference,
    StructureDifference,
    structure_difference,
    SymmetrySet,
    SYMMETRY_EXTENSION,
    cartesian_pca,
    classify_ramachandran,
    default_limits,
    diffusion_map,
    infer_bonds,
    internal_coordinates,
    place_atom,
    read_component_dictionary,
    read_configuration,
    read,
    read_mmtf,
    read_pdb,
    read_pdbqt,
    read_pqr,
    read_bytes,
    read_document,
    read_policy,
    lower_model_cif,
    collect_crystal_neighbors,
    lower_assemblies,
    lower_ncs,
    lower_symmetry,
    read_with_diagnostics,
    read_with_options,
    write,
    write_with_options,
    write_bcif,
    write_bcif_with_options,
    write_mmcif,
    write_mmtf,
    write_mmtf_with_metadata,
    with_mmtf_metadata,
    mmtf_metadata,
    write_pdb,
    write_pdbqt,
    write_pqr,
    write_preserving,
    surface_mesh,
    torsion_pca,
    structure_backbone_torsions,
    structure_backbone_torsions_model,
    structure_protein_alpha_traces,
    structure_side_chain_torsions,
)
from .analysis import StreamlineDirection, StreamlineOptions, VectorFieldError, VectorFieldGrid, integrate_streamlines
from ._native import StructureBatch, StructureBatchReader, collect_structure, open_structure_batches
from .surface import SurfaceComponent, SurfaceComponentError, SurfaceComponentFilter, filter_surface_components, surface_components
from .traj import contact_counts_stream, StreamFrame, run_analysis_stream, rmsf_stream, rmsd_stream, TrajectoryInterpolation, TrajectoryInterpolationError, interpolate_trajectory_frames

from .analysis import (
    BasePair, BasePairOptions, CartesianAxis, CationPi, CationPiOptions, ContactMap,
    Contact, ContactTable, DensityGrid, DensityGridSpec,
    DsspOptions, FragmentMatch, FragmentReference, GaussianNetworkModel,
    GnmOptions, HalfSphereExposure, HydrogenBond, HydrogenBondOptions,
    LinearDensityBin, NativeContacts, NucleicTorsions, PiStacking, PiStackingOptions, Pucker,
    PolymerStatistics, PoreOptions, PoreSample,
    RadialBin, RadialOptions,
    ResidueContact, SaltBridge, SecondaryStructure, SseKind, StackingKind,
    SurfaceContactOptions, WaterBridge,
    density_map, linear_density, map_fragments,
    polymer_statistics, pore_profile, sugar_pucker,
    AssignSecondaryStructure, ChainInterfaceAnalysis, CationPiAnalysis, HalfSphereExposureAnalysis,
    HydrogenBonds, NucleicTorsionAnalysis, PiStackingAnalysis, ResidueContacts, SaltBridges,
    WaterBridges, BasePairs, Gnm,
)
from .surface import (
    AtomDepthOptions, BuriedSurface, Cavity, SurfaceGridOptions, atom_depths, buried_surface,
    cavities, solvent_accessible_surface,
)
from .validate import (
    BondDeviation, BondLengthDeviations, ChainCompleteness, ChiralityFlag,
    ChiralityIssue, ChiralityOptions, ChiralityReport, CisPeptide, CisPeptides,
    Clash, Completeness, PlanarityCheck, PlanarityFlag, PlanarityOptions,
    QualityFlag, QualityFlags, QualityIssue, RamachandranBasin,
    RamachandranOptions, RamachandranRecord, RamachandranRegion,
    ReferenceAssessment, ReferenceDistribution, ReferenceLibrary, RotamerDefinition,
    RotamerFlag, RotamerOptions, RotamerProfile, RotamerReport, StericClashes,
    Valence, ValenceError, analyse_altloc_occupancy,
    analyse_b_factor_distribution, analyse_ccd_completeness,
    analyse_plane_restraints, analyse_tls_b_factor_consistency,
    assess_bond_deviation, assess_ramachandran, validate_altloc_occupancy,
    validate_ccd_completeness, validate_plane_restraints,
)
from .chem import (
    AutomorphismLimit, Component, ComponentAtom, ComponentBond, ComponentCoverage, ComponentDictionary, InferBonds,
    CifProvider, ComponentProvider, MemoryProvider, RadiusTable, PeoeError,
    ChemistryReport, ComponentKind, Element, ElementProperties, EquivalenceCache, EquivalenceClasses, IonicRadius, IonicSpin, PeoeAtom,
    PeoeAtomType, PeoeBond, PeoeOptions, PeoeParameterProfile, PolymerAtomRole, RadiusSet, RadiiSet,
    MolAtom, MolBond, Molecule, MolVersion, MolAtomMetadata, MolBondMetadata, SdfProperty, MolRecord,
    Mol2AtomMetadata, Mol2BondMetadata, Mol2Section, Mol2Record, MolError, Mol2Error,
    SmartsDataError, SmartsError, SmartsMatch, SmartsPattern, SideChainDefinition, SideChainRoles,
    parse_mol_record, parse_sdf_records, write_mol, write_sdf, parse_mol2_record, write_mol2,
    read_ccd, element_properties, vdw_radius, ionic_radii, component_coverage,
    component_peoe_charges, apply_component_chemistry, apply_polymer_role_profile,
    equivalence_classes, automorphisms, side_chain_definition, parse_smarts,
    PolymerLinkPolicy, PolymerLinkRule, PolymerRoleProfile, PolymerRoleReport, PolymerRoleRule,
    StereoConfiguration, DEFAULT_BOND_RADIUS_SCALE, DEFAULT_MINIMUM_BOND_DISTANCE,
    peoe_charges,
)
from .xtal import (
    DEFAULT_CRYSTAL_IMAGE_LIMIT, DEFAULT_INSTANCE_LIMIT, SpaceGroup, SymmetryOperation,
    UnitCell, collect_crystal_neighbors,
    space_group_by_hall, space_group_by_number, space_group_by_symbol, space_group_setting,
    space_group_settings,
)
from .ml.graph import (
    EdgeDirection, EdgeFeature, EdgeKind, Graph, GraphOptions, MissingFeaturePolicy,
    NodeFeature, NodeLevel, SpatialBackend,
)
from .geom import (
    Axes, BackboneCoordinates, BackboneFrame, BackboneResidue, BackboneTorsions, CircularSummary,
    Decomposition, DistanceMatrix, EigenError, EigenOptions, FluctuationError,
    Centroid, CentreOfMass, RadiusOfGyration, InertiaTensor, PrincipalAxes, Asphericity,
    GyrationAxes, DistanceMatrixOp, DistanceMatrixBetween, Rmsf,
    HelixGeometry, MatrixError, PeriodicError, Plane, Rigid, RotationError,
    RotationMeanOptions, RotationOptions, Superposition, SuperposeError, SuperposeOptions,
    TorusMetric,
    angle, asphericity, asphericity_with_options, backbone_frames, backbone_torsions,
    best_fit_plane, best_fit_plane_with_options, centre_of_mass, centroid,
    circular_summary, cross, degrees, dihedral, displacement, distance,
    distance_matrix, distance_matrix_between, distance_squared, dot, gyration_axes,
    helix_geometry, inertia_tensor, norm, normalise, path_torsions, plane_deviation,
    principal_axes, principal_axes_with_options, radius_of_gyration, rmsd, rmsd_flat, rmsf,
    rotation_mean, rotation_mean_with_options, superpose, superpose_with_options, symmetric,
    symmetric_with_options, torus_summary, gyration_axes_with_options,
    helix_geometry_with_options, plane_deviation_with_options,
)
from .ml import (
    ArrowStream, AtomArrowTable, BondArrowTable, ChainArrowTable, DLDataType, DLDevice,
    DLManagedTensor, DLTensor, Dataset, DatasetEntry, DatasetError, DatasetFilter,
    DatasetSplit, DatasetWarning, DlpackError, DlpackTensor, ExportCost, GraphError,
    LoadError, ManifestEntry, MolframeExtension, ResidueArrowTable, SplitOptions, SplitRatios,
    SplitStrategy, TableFileError, build_graph, extension_name, write_atom_ipc,
    write_atom_ipc_with_metadata, write_atom_parquet, write_atom_parquet_with_metadata,
)
from .query import (
    AltlocPolicy, AnalysisPolicy, AssemblyChoice, Evaluation, LogicalPlan, MissingPolicy, ModelChoice,
    Namespace, PhysicalQuery, SelectQuery, Query, QueryBuilder, Selection, col,
)
from .seq import *
from .compare import *
# Sequence compatibility exports include an historical ``Column`` alias for
# ``AlignmentColumn``.  The facade's documented ``Column`` is the CIF column.
from .cif import Column as Column
from ._native import graph as graph
from .spatial import (
    AtomsWithin, AutoBackendProfile, CellGridOptions, KdPeriodicOptions, NeighborList, NeighborListOptions, NeighborPair, NeighborPairs, NeighborSkinProfile, NeighborTable,
    PeriodicBox, PeriodicImage, SpatialError, SpatialOption, SpatialPlan, SpatialSearchOptions, atoms_within, atoms_within_with_options,
    neighbor_pairs, neighbor_pairs_with_options, nearest_neighbors,
)
from .surface import BuriedSurfaceOp, Sasa
from .core.contract import (
    Analysis, Assumption, AssumptionSource, Coverage, Diagnostic, ImpactEstimate,
    Provenance, Status,
)
from ._native import (
    CartesianFit, SurfaceWorkflowOptions, SurfaceWorkflowResult, analyse_diffusion, analyse_pca,
    analyse_surface_geometry, analyse_torsion_pca, analyse_chain_interface, analyse_contacts,
    analyse_half_sphere_exposure, analyse_nucleic_torsions, validate_bond_lengths,
    validate_cis_peptides, validate_clashes, validate_completeness, validate_planarity,
    validate_quality, validate_valence, analyse_assign_chains, analyse_cad_contact_areas,
    analyse_ce_align, analyse_ce_alignments, analyse_map_chains,
    analyse_map_sequence_to_structure, analyse_weighted_rmsd,
)
from ._native import (
    AltlocOccupancyError, AltlocOccupancyKernelError, AtomDepthError, BFactorError,
    BFactorKernelError, BasePairError, BuriedSurfaceError, CapacityError, CationPiError,
    CcdCompletenessKernelError, CompletenessError, DatasetError, DensityError,
    DielectricError, DifferenceError, DlpackError, DmsError, DsspBinaryError, DsspError,
    DynamicsError, EnsembleGeometryError, EnsembleSimilarityError, EnsembleStatisticsError,
    FragmentMappingError, GnmError, GovernedAnalysisError, GovernedEnsembleError,
    GovernedMapError, GovernedNativeError, GraphError, HelicalError, HseError,
    HydrogenBondError, ImdError, KMeansError, LigandGeometryKernelError, LoadError,
    MapStatisticsError, MonomerLibraryReadError, MrcError, MsdError, NativeError,
    NucleicGeometryError, NucleicTorsionError, PathSimilarityError, PhysicalKernelError,
    PiStackingError, PlanarityError, PlaneRestraintKernelError, PolymerError, PoreError,
    RadialError, RamachandranError, RealSpaceCorrelationError, ReexecutionError,
    ReferenceError, ReflectionError, RestraintError, RotamerError, SasaError,
    StandaloneAnalysisError, SurfaceGeometryError, SurfaceWorkflowError, TableError,
    TableFileError, TrajectoryError, TrajectoryIoError, UpdatingSelectionError,
    WaterDynamicsError,
)

# The public surface is what this module binds: the namespaces above, every name
# the imports bound, and whatever ``seq`` and ``compare`` bring in with ``*``. It
# is read off the module rather than written out again because the 69-line list
# this replaces had already drifted from it — ``analyse_assign_chains`` and
# ``analyse_cad_contact_areas`` were imported and never exported. A name that
# must stay private takes a leading underscore.
__all__ = sorted(name for name in dir() if not name.startswith("_"))
