
from __future__ import annotations

from collections.abc import Mapping
from os import PathLike
from types import ModuleType
from typing import Literal, Protocol

from . import sel as sel

class Float32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class UInt32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class Structure:
    @property
    def atoms(self) -> Atoms: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def models(self) -> Models: ...
    @property
    def coordinates(self) -> Float32Array: ...
    def select(self, query: str, *, policy: object | None = ...) -> Selection: ...
    def edit(self) -> StructureEditor: ...

class Atom:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def coordinate(self) -> tuple[float, float, float] | None: ...

class Atoms:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...

class Residue:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def atoms(self) -> Atoms: ...

class Residues:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...

class Chain:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> str | None: ...
    @property
    def residues(self) -> Residues: ...

class Chains:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Chain: ...

class Model:
    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int | None: ...
    @property
    def chains(self) -> Chains: ...

class Models:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Model: ...

class StructureEditor:
    def rename_chain(self, chain: int, label: str) -> None: ...
    def finish(self) -> Structure: ...

class Selection:
    def __len__(self) -> int: ...
    @property
    def indices(self) -> UInt32Array: ...
    def is_stale_for(self, structure: Structure) -> bool: ...
    def to_coordinates(self, *, model: int = ...) -> Float32Array: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __and__(self, other: Selection) -> Selection: ...
    def __sub__(self, other: Selection) -> Selection: ...

class Query:
    def __init__(self, source: str) -> None: ...
    @property
    def fingerprint(self) -> str: ...
    def select(self, structure: Structure) -> Selection: ...
    def __and__(self, other: Query) -> Query: ...
    def __or__(self, other: Query) -> Query: ...
    def __invert__(self) -> Query: ...

class Reader:
    def __init__(self, data: bytes, *, name: str | None = ...) -> None: ...
    @property
    def byte_length(self) -> int: ...
    def read(self) -> Structure: ...

class WorkflowNode: ...

class Workflow:
    def input(
        self,
        name: str,
        *,
        kind: Literal["coordinates", "float", "structure"],
        cost: Literal["borrow", "adopt", "decode", "copy", "materialize"] = ...,
    ) -> WorkflowNode: ...
    def centroid(self, coordinates: WorkflowNode) -> WorkflowNode: ...
    def rmsd(self, mobile: WorkflowNode, reference: WorkflowNode) -> WorkflowNode: ...
    def distance_matrix(self, coordinates: WorkflowNode) -> WorkflowNode: ...
    def atom_contacts(self, structure: WorkflowNode, cutoff: float) -> WorkflowNode: ...
    def output(self, name: str, node: WorkflowNode) -> None: ...
    def compile(self) -> CompiledWorkflow: ...

class CompiledWorkflow:
    def run(self, values: Mapping[str, object], *, copy: bool = ...) -> dict[str, object]: ...
    def explain(self) -> dict[str, object]: ...

def read(source: str | PathLike[str] | bytes, *, name: str | None = ...) -> Structure: ...

analysis: ModuleType
chemistry: ModuleType
compare: ModuleType
crystal: ModuleType
formats: ModuleType
geometry: ModuleType
motif: ModuleType
query: ModuleType
sequence: ModuleType
spatial: ModuleType
surface: ModuleType
trajectory: ModuleType
validation: ModuleType
