"""Core topology, hierarchy storage, symbols, and coordinate ownership types."""

from typing import Any
from ._io_types import CapacityError, TableError

from .core.contract import Analysis, Assumption, AssumptionSource, Coverage, Diagnostic, ImpactEstimate, Provenance, Status
from .chem import Element
from .core.metadata import EntityKind, PolymerKind
from .query import AnalysisPolicy, Selection

from ._core_primitives import (
    Aabb, AnnotationColumn, AtomAnnotation, AtomAnnotations, AtomChunkStats, AtomIndex,
    BondAdjacency, BondIndex, BondTable, BondTableBuilder, ByteSpan, ChainIndex, Class,
    Code, ColumnKind, Compression, ContextItem, CoordinateGeneration, Diagnostics,
    ElementMask, EncodedColumn, EntityIndex, Extremes, InputBuffer, InputKind,
    InstanceId, Kind, ModelIndex, Position, ReadReport, ReadResult, Reader, Rendered,
    ResidueIndex, Select, SelectAll, Severity, Strictness,
)

from ._facade_models import (
    BondOrder, BondProvenance, BondRecord, CountDifference, Limits, MetadataDifference,
    ReadOptions, ReadScope, StructureDifference, structure_difference,
)

from ._facade_structure_io import (
    Structure,
)

from ._io_types import (
    AmbiguousResidueBoundaryPolicy, Format, MissingElementPolicy, ParseMode,
)

from ._provider import (
    ChunkId,
)

from .core.annotation import (
    AROMATIC_ATOM_ANNOTATION, ATOM_RADIUS_ANNOTATION, AUTODOCK_TYPE_ANNOTATION,
    COMPONENT_KIND_ANNOTATION, FORMAL_CHARGE_ANNOTATION, HBOND_ACCEPTOR_ANNOTATION,
    HBOND_DONOR_ANNOTATION, PAE_ANNOTATION, PARTIAL_CHARGE_ANNOTATION,
    PLDDT_ANNOTATION, POLYMER_ATOM_ROLE_ANNOTATION, SEGMENT_ID_ANNOTATION,
    STEREO_CONFIGURATION_ANNOTATION,
)

from .core.chunk import (
    TARGET_CHUNK_ATOMS,
)

class AtomRecord:
    def __init__(self, position: tuple[float, float, float] | None, element: Element,
                 atom_name: SymbolId, auth_atom_name: OptionalSymbol,
                 alternate_component_id: OptionalSymbol, alt_id: AltId, residue: ResidueIndex,
                 occupancy: tuple[float, Presence], b_factor: tuple[float, Presence],
                 formal_charge: tuple[int, Presence], atom_site_id: int) -> None: ...
    position: tuple[float, float, float] | None
    element: Element
    atom_name: SymbolId
    auth_atom_name: OptionalSymbol
    alternate_component_id: OptionalSymbol
    alt_id: AltId
    residue: ResidueIndex
    occupancy: tuple[float, Presence]
    b_factor: tuple[float, Presence]
    formal_charge: tuple[int, Presence]
    atom_site_id: int

class AtomChunk:
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    atoms: tuple[int, int]
    model: int
    stats: AtomChunkStats
    def positions(self, coords: CoordinateBlock) -> Any: ...
    def element(self, local: int) -> Element | None: ...
    def atom_name(self, local: int) -> SymbolId | None: ...
    def atom_names_plain(self) -> list[SymbolId] | None: ...
    def auth_atom_name(self, local: int) -> SymbolId | None: ...
    def alternate_component_id(self, local: int) -> SymbolId | None: ...
    def alt_id(self, local: int) -> AltId | None: ...
    def residue(self, local: int, residues: ResidueTable) -> ResidueIndex | None: ...
    def occupancy(self, local: int) -> tuple[float, Presence] | None: ...
    def occupancies_plain(self) -> Any: ...
    def b_factor(self, local: int) -> tuple[float, Presence] | None: ...
    def b_factors_plain(self) -> Any: ...
    def formal_charge(self, local: int) -> tuple[int, Presence] | None: ...
    def atom_site_id(self, local: int) -> int | None: ...
    def has_position(self, local: int) -> bool: ...
    def record(self, local: int, residues: ResidueTable,
               position: tuple[float, float, float] | None = ...) -> AtomRecord | None: ...

class ChunkBuilder:
    def __init__(self) -> None: ...
    @staticmethod
    def with_target(target: int) -> ChunkBuilder: ...
    def reserve(self, atoms: int) -> None: ...
    def start_model(self, model: int) -> None: ...
    def push(self, record: AtomRecord) -> None: ...
    def finish(self) -> tuple[list[AtomChunk], CoordinateBlock]: ...

class ModelTable:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def push(self, model_num: int, first_chain: int, end_chain: int) -> ModelIndex: ...
    def model_num(self, model: ModelIndex) -> int | None: ...
    def chains(self, model: ModelIndex) -> tuple[int, int] | None: ...
    def iter(self) -> list[ModelIndex]: ...

class ChainRecord:
    def __init__(self, label_asym_id: SymbolId, entity: EntityIndex,
                 polymer_kind: PolymerKind = ..., auth_asym_id: SymbolId | None = ...) -> None: ...
    label_asym_id: SymbolId
    auth_asym_id: OptionalSymbol
    entity: EntityIndex
    polymer_kind: PolymerKind

class ChainTable:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def push(self, record: ChainRecord, first_residue: int, end_residue: int) -> ChainIndex: ...
    def residues(self, chain: ChainIndex) -> tuple[int, int] | None: ...
    def containing(self, residue: int) -> ChainIndex | None: ...
    def label_asym_id(self, chain: ChainIndex) -> SymbolId | None: ...
    def auth_asym_id(self, chain: ChainIndex) -> SymbolId | None: ...
    def entity(self, chain: ChainIndex) -> EntityIndex | None: ...
    def polymer_kind(self, chain: ChainIndex) -> PolymerKind | None: ...
    def rename(self, chain: ChainIndex, label: SymbolId) -> None: ...
    def set_polymer_kind(self, chain: ChainIndex, kind: PolymerKind) -> None: ...
    def instances_of(self, entity: EntityIndex) -> list[ChainIndex]: ...
    def iter(self) -> list[ChainIndex]: ...

class ResidueRecord:
    def __init__(self, label_comp_id: SymbolId, auth_comp_id: SymbolId | None = ...,
                 label_seq_id: int | None = ..., auth_seq_id: int | None = ...,
                 ins_code: SymbolId | None = ..., het: bool = ...) -> None: ...
    label_comp_id: SymbolId
    auth_comp_id: OptionalSymbol
    label_seq_id: OptionalI32
    auth_seq_id: OptionalI32
    ins_code: OptionalSymbol
    het: bool

class ResidueTable:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def push(self, record: ResidueRecord, first_atom: int, end_atom: int) -> ResidueIndex: ...
    def set_atoms(self, residue: ResidueIndex, first_atom: int, end_atom: int) -> None: ...
    def atoms(self, residue: ResidueIndex) -> tuple[int, int] | None: ...
    def containing(self, atom: int) -> ResidueIndex | None: ...
    def label_comp_id(self, residue: ResidueIndex) -> SymbolId | None: ...
    def auth_comp_id(self, residue: ResidueIndex) -> SymbolId | None: ...
    def label_seq_id(self, residue: ResidueIndex) -> int | None: ...
    def auth_seq_id(self, residue: ResidueIndex) -> int | None: ...
    def ins_code(self, residue: ResidueIndex) -> SymbolId | None: ...
    def is_het(self, residue: ResidueIndex) -> bool: ...

class MissingResidue:
    canonical_position: int
    component: str

class EntityTable:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def push(self, id: OptionalSymbol, kind: EntityKind, description: OptionalSymbol,
             canonical_sequence: list[SymbolId]) -> EntityIndex: ...
    def kind(self, entity: EntityIndex) -> EntityKind | None: ...
    def id(self, entity: EntityIndex) -> SymbolId | None: ...
    def find_by_id(self, id: SymbolId) -> EntityIndex | None: ...
    def description(self, entity: EntityIndex) -> SymbolId | None: ...
    def canonical_sequence(self, entity: EntityIndex) -> list[SymbolId]: ...
    def iter(self) -> list[EntityIndex]: ...

class Topology:
    def __init__(self) -> None: ...
    def atom_count(self) -> int: ...
    models: ModelTable
    chains: ChainTable
    residues: ResidueTable
    entities: EntityTable
    def push_model(self, model_num: int, first_chain: int, end_chain: int) -> ModelIndex: ...
    def push_chain(self, record: ChainRecord, first_residue: int, end_residue: int) -> ChainIndex: ...
    def push_residue(self, record: ResidueRecord, first_atom: int, end_atom: int) -> ResidueIndex: ...
    def push_entity(self, id: OptionalSymbol, kind: EntityKind, description: OptionalSymbol,
                    canonical_sequence: list[SymbolId]) -> EntityIndex: ...

class StructureView:
    @staticmethod
    def new(structure: Structure, selection: object) -> StructureView: ...
    selection: object
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def data(self) -> StructureData: ...
    def is_empty(self) -> bool: ...
    generation: CoordinateGeneration
    def is_stale_for(self, structure: Structure) -> bool: ...
    def narrow(self, selection: object) -> StructureView: ...
    def union(self, other: StructureView) -> StructureView: ...
    def intersect(self, other: StructureView) -> StructureView: ...
    def difference(self, other: StructureView) -> StructureView: ...
    def positions(self, model: ModelIndex) -> Any: ...
    def bounds(self, model: ModelIndex) -> Aabb: ...

class StructureEditor:
    def set_annotation(self, name: str, annotation: AtomAnnotation) -> None: ...
    def remove_annotation(self, name: str) -> bool: ...
    def clear_extensions(self) -> None: ...
    def rename_chain(self, chain: ChainIndex, label: str) -> None: ...
    def transform(self, selection: object, transform: object) -> None: ...
    def delete_atoms(self, selection: object) -> None: ...
    def commit(self) -> Structure: ...

# The facade's name for the scoped coordinate-mutation context the extension
# registers as ``CoordinateEdit``; the alias is bound after the class exists, so
# it is declared here rather than pulled from the compiled module.
class CoordinateEditor:
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...

class CoordinateStore:
    @staticmethod
    def single(block: CoordinateBlock) -> CoordinateStore: ...
    @staticmethod
    def dense(frames: list[CoordinateBlock]) -> CoordinateStore: ...
    @staticmethod
    def ragged(models: list[Structure]) -> CoordinateStore: ...
    def model_count(self) -> int: ...
    def is_dense(self) -> bool: ...
    def block(self, model: ModelIndex) -> CoordinateBlock | None: ...
    def ragged_models(self) -> list[Structure] | None: ...

class ExtensionStore:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def is_empty(self) -> bool: ...
    def len(self) -> int: ...
    def keys(self) -> list[str]: ...

class StructureData:
    @staticmethod
    def empty() -> StructureData: ...
    def atom_count(self) -> int: ...
    def model_count(self) -> int: ...
    entry: Any
    topology: Topology
    chunks: list[AtomChunk]
    bonds: BondTable
    annotations: AtomAnnotations
    extensions: ExtensionStore
    coords: CoordinateStore
    dictionary: Interner
    cell: Any | None
    generation: CoordinateGeneration
    def to_structure(self) -> Structure: ...
    def atom(self, index: AtomIndex) -> Any | None: ...
    def atoms(self) -> list[Any]: ...
    def model(self, index: ModelIndex) -> Any | None: ...
    def models(self) -> list[Any]: ...
    def chain(self, index: ChainIndex) -> Any | None: ...
    def chains(self) -> list[Any]: ...
    def chain_named(self, label: str) -> Any | None: ...
    def residue(self, index: ResidueIndex) -> Any | None: ...
    def residues(self) -> list[Any]: ...

class ParentMapping:
    DEFAULT_BLOCK: int
    @staticmethod
    def offsets_only() -> ParentMapping: ...
    @staticmethod
    def explicit(parents: list[int]) -> ParentMapping: ...
    @staticmethod
    def block_indexed(parents: list[int]) -> ParentMapping: ...
    def bytes(self) -> int: ...
    def resolve(self, local: int, first_atom: int, residues: ResidueTable) -> ResidueIndex | None: ...

class SymbolId:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> SymbolId: ...
    def get(self) -> int: ...
    def is_canonical(self) -> bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class AltId:
    value: int
    BLANK: AltId
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> AltId: ...
    @staticmethod
    def labelled(symbol: SymbolId) -> AltId | None: ...
    def get(self) -> int: ...
    def is_blank(self) -> bool: ...
    def symbol(self) -> SymbolId | None: ...
    def __int__(self) -> int: ...

class OptionalI32:
    NONE: OptionalI32
    def __init__(self, value: int | None = ...) -> None: ...
    @staticmethod
    def some(value: int) -> OptionalI32: ...
    def get(self) -> int | None: ...
    def is_none(self) -> bool: ...
    def is_some(self) -> bool: ...

class OptionalSymbol:
    NONE: OptionalSymbol
    def __init__(self, value: SymbolId | None = ...) -> None: ...
    @staticmethod
    def some(value: SymbolId) -> OptionalSymbol: ...
    def get(self) -> SymbolId | None: ...
    def is_none(self) -> bool: ...
    def is_some(self) -> bool: ...

class Interner:
    DEFAULT_LIMIT: int
    def __init__(self) -> None: ...
    @staticmethod
    def with_capacity(identifiers: int) -> Interner: ...
    def with_limit(self, limit: int) -> Interner: ...
    def intern(self, text: str) -> SymbolId: ...
    def get(self, text: str) -> SymbolId | None: ...
    def resolve(self, symbol: SymbolId) -> str | None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def arena_len(self) -> int: ...
    def retained_bytes(self) -> int: ...
    def iter(self) -> list[tuple[SymbolId, str]]: ...

class DictionaryFull(ValueError): ...

class CoordinateBlock:
    def __init__(self) -> None: ...
    @staticmethod
    def with_capacity(positions: int) -> CoordinateBlock: ...
    len: int
    positions: Any
    def is_empty(self) -> bool: ...
    def push(self, position: tuple[float, float, float]) -> None: ...
    def range(self, start: int, end: int) -> Any: ...
    def bounds(self, start: int, end: int) -> Aabb: ...
    def allocated_bytes(self) -> int: ...
    def as_slice(self) -> Any: ...

class BitVec:
    def __init__(self) -> None: ...
    @staticmethod
    def repeat(value: bool, length: int) -> BitVec: ...
    @staticmethod
    def with_capacity(length: int) -> BitVec: ...
    @staticmethod
    def from_values(values: list[bool]) -> BitVec: ...
    @staticmethod
    def try_from_iter(values: list[bool]) -> BitVec: ...
    len: int
    def is_empty(self) -> bool: ...
    def try_push(self, value: bool) -> None: ...
    def get(self, position: int) -> bool | None: ...
    def test(self, position: int) -> bool: ...
    def set(self, position: int, value: bool) -> None: ...
    def count_ones(self) -> int: ...
    def all(self) -> bool: ...
    def none(self) -> bool: ...
    def ones(self) -> list[int]: ...
    def intersect_with(self, other: BitVec) -> None: ...
    def union_with(self, other: BitVec) -> None: ...
    def invert(self) -> None: ...

class Presence:
    Present: Presence
    Unknown: Presence
    Inapplicable: Presence
    def is_present(self) -> bool: ...

class ValidityMask:
    @staticmethod
    def all_present(length: int) -> ValidityMask: ...
    @staticmethod
    def from_values(values: list[Presence]) -> ValidityMask: ...
    @staticmethod
    def try_from_iter(values: list[Presence]) -> ValidityMask: ...
    len: int
    def is_empty(self) -> bool: ...
    def is_all_present(self) -> bool: ...
    def get(self, position: int) -> Presence: ...
    def set(self, position: int, presence: Presence) -> None: ...
    def present_count(self) -> int: ...
    def compact(self) -> None: ...

def bit_width(maximum: int) -> int: ...
def pack(values: list[int], width: int) -> bytes: ...
def unpack_one(data: bytes, width: int, index: int) -> int | None: ...
def write_output(path: str, data: bytes) -> None: ...
