"""Facade structure object and structure/document I/O operations."""

from ._facade_header import *
from typing import TypeAlias, final
_Coordinate: TypeAlias = tuple[float, float, float]
from .core import (
    AROMATIC_ATOM_ANNOTATION, ATOM_RADIUS_ANNOTATION, AUTODOCK_TYPE_ANNOTATION,
    COMPONENT_KIND_ANNOTATION, FORMAL_CHARGE_ANNOTATION, HBOND_ACCEPTOR_ANNOTATION,
    HBOND_DONOR_ANNOTATION, PAE_ANNOTATION, PARTIAL_CHARGE_ANNOTATION, PLDDT_ANNOTATION,
    POLYMER_ATOM_ROLE_ANNOTATION, SEGMENT_ID_ANNOTATION, STEREO_CONFIGURATION_ANNOTATION,
    Aabb, AltId, AlgorithmId, AnalysisParameters, AnnotationColumn, AtomAnnotation, AtomAnnotations, AtomChunk, AtomChunkStats, Backpressure, BatchDemand,
    AtomIndex, AtomRecord, BitVec, ChainRecord, ChainTable, ChunkBuilder, ColumnKind,
    CoordinateStore, EncodedColumn, ElementMask, EntityTable, ExtensionStore, Extremes,
    BondAdjacency, BondIndex, BondOrder, BondProvenance,
    BondRecord, BondTable, BondTableBuilder, ByteSpan, ChainIndex, CoordinateBlock,
    CoordinateGeneration, DictionaryFull, DictionaryVersion, DifferenceError, EntityIndex, ExecutionContext, Fingerprint, InstanceId, Interner, ModelIndex,
    MissingResidue, ModelTable, OptionalI32, OptionalSymbol, ParameterValue, ParentMapping, Position, Presence, ProfileId, ResidueIndex, SourceRef,
    ResidueRecord, ResidueTable, Structure, StructureData, StructureView, StructureEditor,
    CoordinateEditor, CoordinateStore, StructureDifferenceOptions, SymbolId, TARGET_CHUNK_ATOMS, Topology, ValidityMask, ValueDifference,
    AtomSelection, Class, Code, ContextItem, Diagnostics, Kind, Rendered, Severity, Strictness,
    bit_width, pack, unpack_one, write_output,
    OutputOptions, DEFAULT_OUTPUT_MEMORY_LIMIT_BYTES,
)
from .validate import (
    BondDeviation, ChainCompleteness, ChiralityFlag, ChiralityIssue,
    ChiralityOptions, ChiralityReport, CisPeptide, Clash, PlanarityFlag,
    PlanarityOptions, QualityFlag, QualityIssue, RamachandranBasin,
    RamachandranOptions, RamachandranRecord, RamachandranRegion,
    ReferenceAssessment, ReferenceDistribution, ReferenceLibrary,
    RotamerDefinition, RotamerFlag, RotamerOptions, RotamerProfile,
    RotamerReport, ValenceError, analyse_altloc_occupancy,
    analyse_b_factor_distribution, analyse_ccd_completeness,
    analyse_plane_restraints, analyse_tls_b_factor_consistency,
    assess_bond_deviation, assess_ramachandran, validate_altloc_occupancy,
    validate_ccd_completeness, validate_plane_restraints,
)
from .chem import AutomorphismLimit, ChemistryReport, CifProvider, Component, ComponentAtom, ComponentBond, ComponentCoverage, ComponentDictionary, ComponentKind, ComponentProvider, DEFAULT_BOND_RADIUS_SCALE, DEFAULT_MINIMUM_BOND_DISTANCE, Element, ElementProperties, EquivalenceCache, EquivalenceClasses, IonicRadius, IonicSpin, MemoryProvider, PeoeAtom, PeoeAtomType, PeoeBond, PeoeError, PeoeOptions, PeoeParameterProfile, PolymerAtomRole, PolymerLinkPolicy, PolymerLinkRule, PolymerRoleProfile, PolymerRoleReport, PolymerRoleRule, RadiusSet, RadiiSet, RadiusTable, SideChainDefinition, SideChainRoles, SmartsDataError, SmartsError, SmartsMatch, SmartsPattern, StereoConfiguration, MolAtom, MolBond, Molecule, MolVersion, MolAtomMetadata, MolBondMetadata, SdfProperty, MolRecord, Mol2AtomMetadata, Mol2BondMetadata, Mol2Section, Mol2Record, MolError, Mol2Error, apply_component_chemistry, apply_polymer_role_profile, automorphisms, component_coverage, component_peoe_charges, element_properties, equivalence_classes, ionic_radii, parse_mol_record, parse_sdf_records, parse_smarts, read_ccd, side_chain_definition, vdw_radius, write_mol, write_sdf, parse_mol2_record, write_mol2, peoe_charges
from .geom import Axes, BackboneCoordinates, BackboneFrame, BackboneResidue, BackboneTorsions, CircularSummary, Decomposition, DistanceMatrix, EigenError, EigenOptions, FluctuationError, HelixGeometry, MatrixError, PeriodicError, Plane, Rigid, RotationError, RotationMeanOptions, RotationOptions, Superposition, SuperposeError, SuperposeOptions, TorusMetric, angle, asphericity, asphericity_with_options, backbone_frames, backbone_torsions, best_fit_plane, best_fit_plane_with_options, centre_of_mass, centroid, circular_summary, cross, degrees, dihedral, displacement, distance, distance_matrix, distance_matrix_between, distance_squared, dot, gyration_axes, gyration_axes_with_options, helix_geometry, helix_geometry_with_options, inertia_tensor, norm, normalise, path_torsions, plane_deviation, plane_deviation_with_options, principal_axes, principal_axes_with_options, radius_of_gyration, rmsd, rmsd_flat, rmsf, rotation_mean, rotation_mean_with_options, superpose, superpose_with_options, symmetric, symmetric_with_options, torus_summary
from .ml import ArrowStream, AtomArrowTable, AtomTable, BondArrowTable, BondTable, ChainArrowTable, ChainTable, DLDataType, DLDevice, DLManagedTensor, DLTensor, Dataset, DatasetEntry, DatasetError, DatasetFilter, DatasetSplit, DatasetWarning, DlpackError, DlpackTensor, ExportCost, GraphError, LoadError, ManifestEntry, MolframeExtension, ResidueArrowTable, ResidueTable, SplitOptions, SplitRatios, SplitStrategy, TableFileError, extension_name, graph, write_atom_ipc, write_atom_ipc_with_metadata, write_atom_parquet, write_atom_parquet_with_metadata
from .query import AltlocPolicy, AnalysisPolicy, AssemblyChoice, Evaluation, LogicalPlan, MissingPolicy, ModelChoice, Namespace, PhysicalQuery, Query, QueryBuilder, Selection, col

@final
class Structure:
    @staticmethod
    def empty() -> Structure: ...
    def __repr__(self) -> str: ...
    def _pdviewx_structure_capsule(self) -> object: ...
    @property
    def atom_count(self) -> int: ...
    @property
    def model_count(self) -> int: ...
    @property
    def chain_count(self) -> int: ...
    @property
    def residue_count(self) -> int: ...
    @property
    def models(self) -> Models: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def residues(self) -> Residues: ...
    def entry_metadata(self) -> EntryMetadata: ...
    def data(self) -> StructureData: ...
    def view(self) -> StructureView: ...
    def view_of(self, selection: object) -> StructureView: ...
    def edit(self) -> StructureEditor: ...
    def materialize(self, selection: Selection) -> Structure: ...
    def atom(self, index: AtomIndex) -> Atom | None: ...
    def model(self, index: ModelIndex) -> Model | None: ...
    def chain(self, index: ChainIndex) -> Chain | None: ...
    def residue(self, index: ResidueIndex) -> Residue | None: ...
    @property
    def entity_count(self) -> int: ...
    @property
    def generation(self) -> CoordinateGeneration: ...
    @property
    def annotations(self) -> AtomAnnotations: ...
    @property
    def extensions(self) -> ExtensionStore: ...
    @property
    def positions(self) -> NDArray[float32]: ...
    def model_positions(self, model: ModelIndex) -> NDArray[float32]: ...
    def model_snapshot(self, model: ModelIndex) -> tuple[Structure, ModelIndex] | None: ...
    def ragged_models(self) -> list[Structure] | None: ...
    def resolve(self, symbol: SymbolId) -> str | None: ...
    def without_extensions(self) -> Structure: ...
    def validate(self) -> list[Diagnostic]: ...

    def sequence_references(self) -> SequenceReferences | None: ...
    @property
    def bonds(self) -> Bonds: ...
    @property
    def xyz(self) -> NDArray[float32]: ...
    @property
    def atoms(self) -> Atoms: ...
    def edit_coordinates(self, context: ExecutionContext) -> CoordinateEdit: ...
    def resolve_altlocs(self, policy: AnalysisPolicy) -> Analysis[Selection]: ...
    @property
    def cell(self) -> UnitCell | None: ...
    def write(self, path: str | PathLike[str]) -> None: ...
    def pdb_headers(self) -> PdbHeaders | None: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, stream: object | None = None, *, max_version: tuple[int, int] | None = None, dl_device: tuple[int, int] | None = None, copy: bool | None = None) -> object: ...
    def graph(self, options: GraphOptions) -> Graph: ...
    def select(self, query: Query | str, *, policy: AnalysisPolicy | None = None, groups: dict[str, Selection] | None = None) -> Selection: ...
    def evaluate(self, query: Query, *, policy: AnalysisPolicy | None = None, groups: dict[str, Selection] | None = None) -> Evaluation: ...
    def transformed(self, transform: Rigid, *, selection: Selection | None = None) -> Structure: ...
    def difference(self, other: Structure, coordinate_tolerance: float = ..., options: StructureDifferenceOptions | None = ...) -> StructureDifference: ...
    def symmetry_set(self) -> SymmetrySet | None: ...
    def assembly_set(self) -> AssemblySet | None: ...
    def assembly(self, id: str, *, limit: int | None = None) -> AssemblyView: ...
    def ncs_set(self) -> NcsSet | None: ...
    def ncs_generated(self) -> NcsView | None: ...
    def model_cif(self) -> ModelCif | None: ...
    def confidence(self) -> QualityMetrics | None: ...
    def contacts(self, cutoff: float, *, backend: SpatialBackend = SpatialBackend.Auto) -> ContactTable: ...
    def base_pairs(self, dictionary: ComponentDictionary, options: BasePairOptions, context: object | None = None) -> list[BasePair]: ...
    def residue_contact_map(self, cutoff: float, minimum_separation: int, backend: SpatialBackend, context: object | None = None) -> ContactMap: ...
    def half_sphere_exposure(self, radius: float, backend: SpatialBackend, context: object | None = None) -> list[HalfSphereExposure]: ...
    def chain_interface(self, first: str, second: str, cutoff: float, backend: SpatialBackend, context: object | None = None) -> list[int]: ...
    def native_contact_fraction(self, target: Structure, cutoff: float, tolerance: float, backend: SpatialBackend, context: object | None = None) -> NativeContacts: ...
    def surface_contacts(self, radii: NDArray[float32], options: SurfaceContactOptions, context: object | None = None) -> ContactTable: ...
    def gaussian_network_model(self, sites: Selection, options: GnmOptions, *, periodic: bool = False, context: object | None = None) -> GaussianNetworkModel: ...
    def nucleic_torsions(self) -> list[NucleicTorsions]: ...
    def secondary_structure(self, options: DsspOptions) -> list[SecondaryStructure]: ...
    def quality_flags(self) -> list[QualityFlag]: ...
    def bond_length_deviations(self, tolerance: float) -> list[BondDeviation]: ...
    def ligand_geometry_outliers(self, tolerance: float) -> list[BondDeviation]: ...
    def clashes(self, tolerance: float, radius_set: RadiusSet, *, backend: SpatialBackend = SpatialBackend.Auto, context: object | None = None) -> list[Clash]: ...
    def completeness(self, namespace: Namespace) -> list[ChainCompleteness]: ...
    def cis_peptides(self, threshold_degrees: float) -> list[CisPeptide]: ...
    def nonplanar_aromatic_rings(self, options: PlanarityOptions) -> list[PlanarityFlag]: ...
    def overvalent_atoms(self) -> list[ValenceError]: ...
    def ramachandran(self, options: RamachandranOptions, *, outliers_only: bool = False) -> list[RamachandranRecord]: ...
    def chirality_outliers(self, dictionary: ComponentDictionary, options: ChiralityOptions, *, policy: AnalysisPolicy | None = None) -> ChiralityReport: ...
    def rotamer_outliers(self, dictionary: ComponentDictionary, references: ReferenceLibrary, profile: RotamerProfile, options: RotamerOptions, *, policy: AnalysisPolicy | None = None) -> RotamerReport: ...
    def radial_distribution(self, left: Selection, right: Selection, options: RadialOptions, *, periodic: bool = False) -> list[RadialBin]: ...
    def centre_of_mass_radial_distribution(self, masses: list[float], left: list[Selection], right: list[Selection], options: RadialOptions, *, periodic: bool = False) -> list[RadialBin]: ...
    def coordination_numbers(self, left: Selection, right: Selection, shell: tuple[float, float], *, backend: SpatialBackend = SpatialBackend.Auto, periodic: bool = False, context: object | None = None) -> list[int]: ...
    def leaflets(self, sites: Selection, connection_distance: float, *, backend: SpatialBackend = SpatialBackend.Auto, periodic: bool = False) -> list[list[int]]: ...
    def hydrogen_bonds(self, options: HydrogenBondOptions, context: object | None = None) -> list[HydrogenBond]: ...
    def salt_bridges(self, maximum_distance: float, *, backend: SpatialBackend = SpatialBackend.Auto, context: object | None = None) -> list[SaltBridge]: ...
    def pi_stacking(self, options: PiStackingOptions) -> list[PiStacking]: ...
    def cation_pi(self, options: CationPiOptions) -> list[CationPi]: ...
    def water_bridges(self, options: HydrogenBondOptions, context: object | None = None) -> list[WaterBridge]: ...

@final
class StructureEditor:
    def set_annotation(self, name: str, annotation: AtomAnnotation) -> None: ...
    def remove_annotation(self, name: str) -> bool: ...
    def clear_extensions(self) -> None: ...
    def rename_chain(self, chain: ChainIndex, label: str) -> None: ...
    def transform(self, selection: Selection, transform: Rigid) -> None: ...
    def delete_atoms(self, selection: Selection) -> None: ...
    def commit(self) -> Structure: ...

@final
class StructureBatch:
    @property
    def dataset_id(self) -> int: ...
    @property
    def chunk_id(self) -> int: ...
    @property
    def logical_start(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def retained_bytes(self) -> int: ...
    @property
    def continuity_before(self) -> str: ...
    @property
    def continuity_after(self) -> str: ...
    @property
    def positions(self) -> NDArray[float32]: ...
    @property
    def models(self) -> NDArray: ...
    @property
    def chains(self) -> NDArray[uint32]: ...
    @property
    def components(self) -> NDArray[uint32]: ...
    @property
    def atoms(self) -> NDArray[uint32]: ...
    @property
    def sequences(self) -> NDArray: ...
    @property
    def elements(self) -> NDArray: ...
    @property
    def coordinate_presence(self) -> NDArray: ...
    @property
    def atom_site_ids(self) -> NDArray[uint32]: ...
    @property
    def heterogens(self) -> NDArray: ...
    @property
    def diagnostics(self) -> list[str]: ...
    def resolve(self, symbol: int) -> str | None: ...

@final
class StructureBatchReader:
    @property
    def context(self) -> ExecutionContext: ...
    def pull(self, demand: BatchDemand | None = None) -> tuple[Backpressure, StructureBatch | None]: ...

def open_structure_batches(path: str | PathLike[str], options: ReadOptions | None = None, context: ExecutionContext | None = None) -> StructureBatchReader: ...
def collect_structure(source: StructureBatchReader) -> Structure: ...

def read(path: str | PathLike[str], options: ReadOptions | None = None) -> Structure: ...
def read_with_diagnostics(path: str | PathLike[str]) -> ReadReport: ...
def read_document(path: str | PathLike[str]) -> Document: ...
def read_configuration(path: str | PathLike[str]) -> ApplicationConfiguration: ...
def read_policy(path: str | PathLike[str]) -> AnalysisPolicy: ...
def read_with_options(path: str | PathLike[str], options: ReadOptions) -> ReadReport: ...
def read_bytes(data: bytes, options: ReadOptions, *, name: str | None = None) -> ReadReport: ...
def write(path: str | PathLike[str], structure: Structure) -> None: ...
def write_mmcif(
    structure: Structure,
    *,
    block_id: str | None = None,
    generate_connection_ids: bool = False,
    connection_type: str | None = None,
) -> str: ...
def write_bcif(structure: Structure) -> bytes: ...
def write_bcif_with_options(structure: Structure, *, block_id: str | None = ..., generate_connection_ids: bool = ..., connection_type: str | None = ...) -> bytes: ...
def write_mmtf(structure: Structure) -> bytes: ...
def write_pdb(structure: Structure, options: PdbWriteOptions) -> str: ...
def write_pdbqt(structure: Structure, options: PdbWriteOptions) -> str: ...
def write_pqr(structure: Structure, options: PdbWriteOptions) -> str: ...
def write_preserving(document: Document) -> str: ...
def write_with_options(path: str | PathLike[str], structure: Structure, options: OutputOptions) -> None: ...
def default_limits() -> Limits: ...
def infer_bonds(structure: Structure, options: BondInference) -> BondInferenceReport: ...
def internal_coordinates(structure: Structure, model: int = 0) -> InternalCoordinates: ...
def place_atom(i: _Coordinate, j: _Coordinate, k: _Coordinate, length: float, angle: float, torsion: float) -> _Coordinate | None: ...
def read_component_dictionary(path: str | PathLike[str], version: str) -> ComponentDictionary: ...
def structure_protein_alpha_traces(structure: Structure) -> list[ProteinAlphaTrace]: ...
def structure_backbone_torsions(structure: Structure) -> list[BackboneTorsionRecord]: ...
def structure_backbone_torsions_model(structure: Structure, model: int) -> list[BackboneTorsionRecord]: ...
def structure_side_chain_torsions(structure: Structure, dictionary: ComponentDictionary, policy: AnalysisPolicy) -> SideChainTorsionReport: ...
