from typing import final
from .core.contract import Diagnostic

class MolframeError(Exception):
    code: str
    message: str
    remedy: str
    span: tuple[int, int, int, int] | None
    findings: list[Diagnostic]

class ParseError(MolframeError): ...
class SchemaError(MolframeError): ...
class ConsistencyError(MolframeError): ...
class ConversionError(MolframeError): ...
class GeometryError(MolframeError): ...
class PolicyError(MolframeError): ...
class PolicyConfigError(MolframeError): ...
class DifferenceError(MolframeError): ...
class ReexecutionError(MolframeError): ...
class CapacityError(MolframeError): ...
class TableError(MolframeError): ...
class DatasetError(MolframeError): ...
class GraphError(MolframeError): ...
class TableFileError(MolframeError): ...
class DlpackError(MolframeError): ...
class LoadError(MolframeError): ...
class CompareError(MolframeError): ...
class CadError(MolframeError): ...
class CadConstructionError(MolframeError): ...
class CeError(MolframeError): ...
class GovernedCompareError(MolframeError): ...
class BasePairError(MolframeError): ...
class CationPiError(MolframeError): ...
class DensityError(MolframeError): ...
class DsspBinaryError(MolframeError): ...
class DsspError(MolframeError): ...
class DynamicsError(MolframeError): ...
class EnsembleGeometryError(MolframeError): ...
class EnsembleSimilarityError(MolframeError): ...
class EnsembleStatisticsError(MolframeError): ...
class FragmentMappingError(MolframeError): ...
class GnmError(MolframeError): ...
class GovernedAnalysisError(MolframeError): ...
class GovernedEnsembleError(MolframeError): ...
class GovernedNativeError(MolframeError): ...
class HelicalError(MolframeError): ...
class HseError(MolframeError): ...
class HydrogenBondError(MolframeError): ...
class KMeansError(MolframeError): ...
class NativeError(MolframeError): ...
class NucleicTorsionError(MolframeError): ...
class PhysicalKernelError(MolframeError): ...
class PiStackingError(MolframeError): ...
class PolymerError(MolframeError): ...
class PoreError(MolframeError): ...
class RadialError(MolframeError): ...
class StandaloneAnalysisError(MolframeError): ...
class AtomDepthError(MolframeError): ...
class BuriedSurfaceError(MolframeError): ...
class SasaError(MolframeError): ...
class SurfaceGeometryError(MolframeError): ...
class SurfaceWorkflowError(MolframeError): ...
class MapStatisticsError(MolframeError): ...
class MrcError(MolframeError): ...
class MrcBrickError(MolframeError): ...
class MonomerLibraryReadError(MolframeError): ...
class RestraintError(MolframeError): ...
class ReflectionError(MolframeError): ...
class AltlocOccupancyError(MolframeError): ...
class AltlocOccupancyKernelError(MolframeError): ...
class BFactorError(MolframeError): ...
class BFactorKernelError(MolframeError): ...
class CcdCompletenessKernelError(MolframeError): ...
class CompletenessError(MolframeError): ...
class GovernedMapError(MolframeError): ...
class LigandGeometryKernelError(MolframeError): ...
class NucleicGeometryError(MolframeError): ...
class PlanarityError(MolframeError): ...
class PlaneRestraintKernelError(MolframeError): ...
class RamachandranError(MolframeError): ...
class RealSpaceCorrelationError(MolframeError): ...
class ReferenceError(MolframeError): ...
class RotamerError(MolframeError): ...
class DielectricError(MolframeError): ...
class DmsError(MolframeError): ...
class ImdError(MolframeError): ...
class MsdError(MolframeError): ...
class PathSimilarityError(MolframeError): ...
class TrajectoryError(MolframeError): ...
class TrajectoryIoError(MolframeError): ...
class UpdatingSelectionError(MolframeError): ...
class WaterDynamicsError(MolframeError): ...
class MolframeIndexError(MolframeError, IndexError): ...
class MolframeKeyError(MolframeError, KeyError): ...

@final
class Format:
    Auto: Format
    Mmcif: Format
    Pdbml: Format
    BinaryCif: Format
    Mmtf: Format
    Pdb: Format
    Pqr: Format
    Pdbqt: Format

@final
class ParseMode:
    Strict: ParseMode
    Permissive: ParseMode
    Recover: ParseMode

@final
class MissingElementPolicy:
    PreserveUnknown: MissingElementPolicy
    InferFromAtomName: MissingElementPolicy

@final
class AmbiguousResidueBoundaryPolicy:
    Reject: AmbiguousResidueBoundaryPolicy
    InferFromFileOrder: AmbiguousResidueBoundaryPolicy
