from enum import Enum
from numpy import float32, float64, int64
from numpy.typing import NDArray
from ._facade_models import BondOrder, BondProvenance

class ProviderError(Exception): ...

class DatasetId:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> DatasetId: ...
    def get(self) -> int: ...
    def next(self) -> DatasetId | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class ChunkId:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> ChunkId: ...
    def get(self) -> int: ...
    def next(self) -> ChunkId | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class LogicalRow:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> LogicalRow: ...
    def get(self) -> int: ...
    def next(self) -> LogicalRow | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class LocalRow:
    value: int
    def __init__(self, value: int) -> None: ...
    def get(self) -> int: ...
    def next(self) -> LocalRow | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class PayloadKind(Enum):
    Structure: PayloadKind
    BondTopology: PayloadKind
    Property: PayloadKind
    Frame: PayloadKind

class ChunkLayout:
    target_rows: int
    is_regular: bool
    @staticmethod
    def regular(rows_per_chunk: int) -> ChunkLayout: ...
    @staticmethod
    def source_defined(target_rows: int) -> ChunkLayout: ...

class ChunkDescriptor:
    dataset: DatasetId
    chunk: ChunkId
    logical_start: LogicalRow
    rows: int
    def __init__(self, dataset: DatasetId, chunk: ChunkId, logical_start: LogicalRow, rows: int) -> None: ...
    def resolve(self, local: LocalRow) -> LogicalRow: ...

class DatasetDescriptor:
    id: DatasetId
    payload: PayloadKind
    logical_rows: int
    chunk_count: int
    first_chunk: ChunkId
    layout: ChunkLayout
    @staticmethod
    def regular(dataset: DatasetId, payload: PayloadKind, logical_rows: int, rows_per_chunk: int, first_chunk: ChunkId) -> DatasetDescriptor: ...
    @staticmethod
    def source_defined(dataset: DatasetId, payload: PayloadKind, logical_rows: int, chunk_count: int, first_chunk: ChunkId, target_rows: int) -> DatasetDescriptor: ...
    def regular_chunk(self, chunk: ChunkId) -> ChunkDescriptor: ...

class DatasetCatalog:
    datasets: list[DatasetDescriptor]
    def __init__(self, datasets: list[DatasetDescriptor]) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, dataset: DatasetId) -> DatasetDescriptor | None: ...

class PropertyKind(Enum):
    Boolean: PropertyKind
    Integer: PropertyKind
    Real: PropertyKind
    Symbol: PropertyKind

class PropertyValue:
    kind: PropertyKind
    presence: object
    boolean: bool | None
    integer: int | None
    real: float | None
    symbol: object | None

class AtomEndpoint:
    dataset: DatasetId
    row: LogicalRow
    def __init__(self, dataset: DatasetId, row: LogicalRow) -> None: ...

class BondChunkRecord:
    atom_a: AtomEndpoint
    atom_b: AtomEndpoint
    order: BondOrder
    provenance: BondProvenance

class BondChunk:
    descriptor: ChunkDescriptor
    atom_dataset: DatasetId
    structure: object
    def record(self, local: LocalRow) -> BondChunkRecord: ...
    def minimum_host_bytes(self) -> int: ...

class StructureChunk:
    descriptor: ChunkDescriptor
    positions: NDArray[float32]
    def element(self, local: LocalRow) -> object | None: ...
    def atom_site_id(self, local: LocalRow) -> int | None: ...

class PropertyChunk:
    descriptor: ChunkDescriptor
    name: str
    kind: PropertyKind | None
    def value(self, local: LocalRow) -> PropertyValue: ...
    def integers(self) -> NDArray[int64] | None: ...
    def reals(self) -> NDArray[float64] | None: ...

class FrameChunk:
    descriptor: ChunkDescriptor
    positions: NDArray[float32]
    coordinates: object
    def __init__(self, descriptor: ChunkDescriptor, coordinates: object, start: int, end: int) -> None: ...

class StructureChunkProvider:
    dataset: DatasetDescriptor
    def __init__(self, dataset: DatasetId, first_chunk: ChunkId, structure: object) -> None: ...
    def chunk(self, chunk: ChunkId) -> StructureChunk: ...

class BondChunkProvider:
    dataset: DatasetDescriptor
    def __init__(self, dataset: DatasetId, first_chunk: ChunkId, atom_dataset: DatasetId, atom_logical_start: LogicalRow, structure: object) -> None: ...
    @staticmethod
    def with_rows_per_chunk(dataset: DatasetId, first_chunk: ChunkId, atom_dataset: DatasetId, atom_logical_start: LogicalRow, structure: object, rows_per_chunk: int) -> BondChunkProvider: ...
    def chunk(self, chunk: ChunkId) -> BondChunk: ...

class PropertyChunkProvider:
    dataset: DatasetDescriptor
    def __init__(self, dataset: DatasetId, first_chunk: ChunkId, structure: object, name: str) -> None: ...
    @staticmethod
    def plddt(dataset: DatasetId, first_chunk: ChunkId, structure: object) -> PropertyChunkProvider: ...
    def chunk(self, chunk: ChunkId) -> PropertyChunk: ...

class FrameChunkProvider:
    dataset: DatasetDescriptor
    def __init__(self, dataset: DatasetId, first_chunk: ChunkId, structure: object, model: object) -> None: ...
    def chunk(self, chunk: ChunkId) -> FrameChunk: ...

TARGET_CHUNK_BONDS: int
