from typing import Literal

from . import (
    AnalysisPolicy,
    BoolArray,
    ExecutionContext,
    Float32Array,
    SecondarySource,
    SecondaryStructure,
    Table,
    UInt8Array,
    UInt32Array,
    crystal as crystal,
)

class Structure:
    @property
    def atom_count(self) -> int: ...
    @property
    def residue_count(self) -> int: ...
    @property
    def chain_count(self) -> int: ...
    @property
    def model_count(self) -> int: ...
    @property
    def atoms(self) -> Atoms: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def models(self) -> Models: ...
    @property
    def coordinates(self) -> Float32Array: ...
    def select(self, query: str | Query, *, policy: AnalysisPolicy | None = ...) -> Selection: ...
    def edit(self) -> StructureEditor: ...
    @property
    def bonds(self) -> BondTable: ...
    @property
    def bond_count(self) -> int: ...
    @property
    def secondary_structure(self) -> list[SecondaryStructure]: ...
    @property
    def secondary_source(self) -> list[SecondarySource]: ...
    @property
    def metadata(self) -> EntryMetadata: ...
    @property
    def cell(self) -> crystal.UnitCell | None: ...
    @property
    def anisotropy(self) -> Table | None: ...
    @property
    def annotations(self) -> Annotations: ...
    @property
    def entities(self) -> Entities: ...
    @property
    def elements(self) -> UInt8Array: ...
    @property
    def occupancies(self) -> Float32Array: ...
    @property
    def b_factors(self) -> Float32Array: ...
    def infer_bonds(
        self,
        *,
        scale: float = ...,
        lower_bound: float = ...,
        across_chains: bool = ...,
        context: ExecutionContext | None = None,
    ) -> Structure: ...

class BondTable:
    """The covalent bonds of a structure, readable by any Arrow consumer.

    Columns: ``bond_index``, ``atom_a``, ``atom_b``, ``order``, ``provenance``.
    """

    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class Atom:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def coordinate(self) -> tuple[float, float, float] | None: ...
    @property
    def component_name(self) -> str | None: ...
    @property
    def residue(self) -> Residue | None: ...
    @property
    def element(self) -> str | None: ...
    @property
    def atomic_number(self) -> int | None: ...
    @property
    def occupancy(self) -> float | None: ...
    @property
    def b_factor(self) -> float | None: ...
    @property
    def formal_charge(self) -> int | None: ...
    @property
    def altloc(self) -> str | None: ...
    @property
    def serial(self) -> int | None: ...
    @property
    def auth_name(self) -> str | None: ...
    @property
    def anisotropy(self) -> tuple[float, float, float, float, float, float] | None: ...

class Atoms:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class Residue:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def atoms(self) -> Atoms: ...
    def atom(self, name: str) -> Atom | None: ...
    @property
    def number(self) -> int | None: ...
    @property
    def auth_number(self) -> int | None: ...
    @property
    def auth_name(self) -> str | None: ...
    @property
    def insertion_code(self) -> str | None: ...
    @property
    def is_hetero(self) -> bool: ...
    @property
    def chain(self) -> Chain | None: ...
    @property
    def secondary_structure(self) -> SecondaryStructure | None: ...
    @property
    def secondary_source(self) -> SecondarySource | None: ...

class ResidueSelection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...

class Residues:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class Chain:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> str | None: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def auth_label(self) -> str | None: ...
    @property
    def entity(self) -> int | None: ...
    @property
    def polymer_kind(
        self,
    ) -> (
        Literal["none", "protein", "dna", "rna", "nucleic_hybrid", "saccharide", "other"] | None
    ): ...

class Chains:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Chain: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class Model:
    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int | None: ...
    @property
    def chains(self) -> Chains: ...

class Models:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Model: ...

class StructureEditor:
    """Staged topology edits, validated as a whole and published by ``finish()``."""

    def rename_chain(self, chain: int, label: str) -> None: ...
    def clear_extensions(self) -> None: ...
    def delete(self, selection: Selection) -> None: ...
    def coordinates(self, *, context: ExecutionContext | None = None) -> CoordinateEditor: ...
    def finish(self) -> Structure: ...

class CoordinateEditor:
    """A private, writable copy of a structure's coordinates.

    ``positions()`` is a view onto the copy; ``commit()`` publishes a new structure
    holding its own snapshot, so editing on cannot change what was published.
    """

    def positions(self, model: int = 0) -> Float32Array: ...
    def commit(self) -> Structure: ...

class EntryMetadata:
    @property
    def id(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def method(self) -> str | None: ...
    @property
    def resolution(self) -> float | None: ...
    @property
    def space_group(self) -> str | None: ...

class Annotation:
    """One per-atom column; ``values`` at an atom where ``present`` is false is a placeholder."""

    @property
    def kind(self) -> Literal["boolean", "integer", "real", "symbol"]: ...
    @property
    def values(self) -> object: ...
    @property
    def present(self) -> BoolArray: ...

class Annotations:
    def __len__(self) -> int: ...
    @property
    def names(self) -> list[str]: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Annotation: ...

class Entity:
    @property
    def index(self) -> int: ...
    @property
    def id(self) -> str | None: ...
    @property
    def kind(self) -> Literal["polymer", "non_polymer", "water", "branched", "unknown"] | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def sequence(self) -> list[str]: ...
    @property
    def chains(self) -> list[int]: ...

class Entities:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Entity: ...

class Selection:
    def __len__(self) -> int: ...
    @property
    def indices(self) -> UInt32Array: ...
    def is_stale_for(self, structure: Structure) -> bool: ...
    def to_coordinates(self, *, model: int = ...) -> Float32Array: ...
    def residues(self, structure: Structure | None = ...) -> ResidueSelection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __and__(self, other: Selection) -> Selection: ...
    def __sub__(self, other: Selection) -> Selection: ...

class Query:
    def __init__(self, source: str) -> None: ...
    @property
    def fingerprint(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def references(self) -> list[str]: ...
    def select(self, structure: Structure, *, policy: AnalysisPolicy | None = ...) -> Selection: ...
    def __and__(self, other: Query) -> Query: ...
    def __or__(self, other: Query) -> Query: ...
    def __invert__(self) -> Query: ...
