[package]
name = "molframe-modelcif"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
description = "ModelCIF metadata and confidence metrics for molframe"

[dependencies]
num-traits.workspace = true
molframe-core.workspace = true
molframe-cif.workspace = true

[dev-dependencies]
criterion.workspace = true
molframe-bench.workspace = true
molframe-core.workspace = true

[[bench]]
name = "modelcif"
harness = false

[lints]
workspace = true
