from typing import final
from numpy import float32, uint32
from numpy.typing import NDArray
from ..xtal import UnitCell
from .._native import SpatialBackend

class SpatialError(ValueError): ...

@final
class NeighborPair:
    def __init__(self, first: int, second: int, distance: float) -> None: ...
    first: int
    second: int
    distance: float
    def __repr__(self) -> str: ...

@final
class NeighborTable:
    """Immutable native columns for source-target neighbour rows."""
    indices: NDArray[uint32]
    distance: NDArray[float32]
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class NeighborPairs:
    def __init__(self, *, positions: NDArray[float32], cutoff: float, left: NDArray[uint32] | None = ..., right: NDArray[uint32] | None = ..., options: SpatialSearchOptions | None = ..., cell: UnitCell | None = ...) -> None: ...
    def execute(self) -> NeighborTable: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> NeighborPairs: ...
    def __repr__(self) -> str: ...

@final
class AtomsWithin:
    def __init__(self, *, positions: NDArray[float32], targets: NDArray[uint32], cutoff: float, query: NDArray[uint32] | None = ..., options: SpatialSearchOptions | None = ..., cell: UnitCell | None = ...) -> None: ...
    def execute(self) -> NDArray[uint32]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> AtomsWithin: ...
    def __repr__(self) -> str: ...

@final
class AutoBackendProfile:
    def __init__(self, brute_force_pair_limit: int, kd_target_minimum: int, kd_query_ratio: int, periodic_backend: SpatialBackend) -> None: ...
    @staticmethod
    def balanced() -> AutoBackendProfile: ...
    brute_force_pair_limit: int
    kd_target_minimum: int
    kd_query_ratio: int
    periodic_backend: SpatialBackend

@final
class NeighborSkinProfile:
    def __init__(self, cutoff_ratio: float, minimum: float) -> None: ...
    @staticmethod
    def balanced() -> NeighborSkinProfile: ...
    cutoff_ratio: float
    minimum: float

@final
class CellGridOptions:
    def __init__(self, maximum_cell_count: int, edge_growth_factor: float) -> None: ...
    @staticmethod
    def memory_balanced() -> CellGridOptions: ...
    maximum_cell_count: int
    edge_growth_factor: float

@final
class KdPeriodicOptions:
    def __init__(self, maximum_image_count: int) -> None: ...
    @staticmethod
    def balanced() -> KdPeriodicOptions: ...
    maximum_image_count: int

@final
class PeriodicImage:
    displacement: tuple[float, float, float]
    lattice_shift: tuple[int, int, int]

@final
class PeriodicBox:
    def __init__(self, cell: UnitCell) -> None: ...
    def displacement(self, left: tuple[float, float, float], right: tuple[float, float, float]) -> tuple[float, float, float]: ...
    def minimum_image(self, left: tuple[float, float, float], right: tuple[float, float, float]) -> PeriodicImage: ...
    def distance_squared(self, left: tuple[float, float, float], right: tuple[float, float, float]) -> float: ...
    def fractional(self, position: tuple[float, float, float]) -> tuple[float, float, float]: ...
    def cartesian(self, fractional: tuple[float, float, float]) -> tuple[float, float, float]: ...
    def wrap(self, position: tuple[float, float, float]) -> tuple[float, float, float]: ...
    def interpolate(self, left: tuple[float, float, float], right: tuple[float, float, float], amount: float) -> tuple[float, float, float] | None: ...

@final
class SpatialOption:
    BruteForcePairLimit: SpatialOption
    KdTargetMinimum: SpatialOption
    KdQueryRatio: SpatialOption
    PeriodicBackend: SpatialOption
    NeighborSkinRatio: SpatialOption
    NeighborSkinMinimum: SpatialOption
    MaximumCellCount: SpatialOption
    CellGrowthFactor: SpatialOption
    KdPeriodicImageLimit: SpatialOption

@final
class NeighborListOptions:
    def __init__(self, skin: float, *, cell_grid: CellGridOptions | None = ...) -> None: ...
    @staticmethod
    def with_skin(skin: float) -> NeighborListOptions: ...
    skin: float
    cell_grid: CellGridOptions
    def validate(self) -> None: ...

@final
class NeighborList:
    @classmethod
    def build(cls, positions: NDArray[float32], left: NDArray[uint32], right: NDArray[uint32], cutoff: float, options: NeighborListOptions, *, cell: UnitCell | None = ...) -> NeighborList: ...
    def generation(self) -> int: ...
    def is_current(self, generation: int) -> bool: ...
    def can_reuse(self, positions: NDArray[float32], *, cell: UnitCell | None = ...) -> bool: ...
    def pairs(self, positions: NDArray[float32], cutoff: float, *, cell: UnitCell | None = ...) -> NeighborTable: ...

@final
class SpatialSearchOptions:
    def __init__(self, backend: SpatialBackend = SpatialBackend.Auto, *, automatic: AutoBackendProfile | None = None, neighbor_skin: NeighborSkinProfile | None = None, cell_grid: CellGridOptions | None = None, kd_periodic: KdPeriodicOptions | None = None) -> None: ...
    @staticmethod
    def balanced() -> SpatialSearchOptions: ...
    def plan(self, left_count: int, right_count: int, periodic: bool, cutoff: float) -> SpatialPlan: ...

@final
class SpatialPlan:
    requested_backend: SpatialBackend
    backend: SpatialBackend
    neighbor_skin: float | None
    options: SpatialSearchOptions

def neighbor_pairs(positions: NDArray[float32], cutoff: float, *, left: NDArray[uint32] | None = None, right: NDArray[uint32] | None = None, backend: SpatialBackend = SpatialBackend.Auto, cell: UnitCell | None = None) -> NeighborTable: ...
def neighbor_pairs_with_options(positions: NDArray[float32], cutoff: float, options: SpatialSearchOptions, *, left: NDArray[uint32] | None = None, right: NDArray[uint32] | None = None, cell: UnitCell | None = None) -> NeighborTable: ...
def atoms_within(positions: NDArray[float32], targets: NDArray[uint32], cutoff: float, *, query: NDArray[uint32] | None = None, backend: SpatialBackend = SpatialBackend.Auto, cell: UnitCell | None = None) -> NDArray[uint32]: ...
def atoms_within_with_options(positions: NDArray[float32], targets: NDArray[uint32], cutoff: float, options: SpatialSearchOptions, *, query: NDArray[uint32] | None = None, cell: UnitCell | None = None) -> NDArray[uint32]: ...
def nearest_neighbors(positions: NDArray[float32], targets: NDArray[uint32], query: int, count: int, *, cell: UnitCell | None = None, periodic_options: KdPeriodicOptions | None = None) -> NeighborTable: ...
