from typing import final
from numpy import float64, int32
from numpy.typing import NDArray
from .._io_types import ReflectionError

@final
class ReflectionColumnType:
    MillerIndex: ReflectionColumnType
    Amplitude: ReflectionColumnType
    Intensity: ReflectionColumnType
    StandardDeviation: ReflectionColumnType
    Phase: ReflectionColumnType
    Flag: ReflectionColumnType
    Real: ReflectionColumnType
    Text: ReflectionColumnType

@final
class ReflectionValue:
    def __init__(self, kind: str, value: int | float | str | None = ...) -> None: ...
    @staticmethod
    def missing() -> ReflectionValue: ...
    @staticmethod
    def inapplicable() -> ReflectionValue: ...
    kind: str
    value: int | float | str | None
    def as_f64(self) -> float | None: ...
    def as_i32(self) -> int | None: ...

@final
class ReflectionColumn:
    def __init__(self, label: str, column_type: ReflectionColumnType, values: list[ReflectionValue], *, dataset_id: int = 0, mtz_type: str | None = ...) -> None: ...
    label: str
    column_type: ReflectionColumnType
    dataset_id: int
    mtz_type: str | None
    values: list[ReflectionValue]
    def numeric_values(self, *, copy: bool = True) -> NDArray[float64]: ...

@final
class ReflectionDataset:
    def __init__(self, id: int, project: str, crystal: str, name: str, *, wavelength: float | None = ..., cell: tuple[list[float], list[float]] | None = ...) -> None: ...
    id: int
    project: str
    crystal: str
    name: str
    wavelength: float | None
    cell: tuple[list[float], list[float]] | None

@final
class ReflectionMetadata:
    def __init__(self) -> None: ...
    def with_title(self, title: str) -> ReflectionMetadata: ...
    def with_crystal(self, cell: tuple[list[float], list[float]], space_group_number: int, space_group_name: str) -> ReflectionMetadata: ...
    def with_symmetry_operations(self, symmetry_operations: list[str]) -> ReflectionMetadata: ...
    def with_datasets(self, datasets: list[ReflectionDataset]) -> ReflectionMetadata: ...
    def with_history(self, history: list[str]) -> ReflectionMetadata: ...
    def with_sort_order(self, sort_order: list[int]) -> ReflectionMetadata: ...
    def with_resolution_range(self, resolution_range: list[float]) -> ReflectionMetadata: ...
    def with_missing_value(self, missing_value: float) -> ReflectionMetadata: ...
    def with_extra_header_records(self, extra_header_records: list[str]) -> ReflectionMetadata: ...
    def __repr__(self) -> str: ...

@final
class ReflectionTable:
    def __init__(self, columns: list[ReflectionColumn], *, metadata: ReflectionMetadata | None = ...) -> None: ...
    title: str
    cell: tuple[list[float], list[float]] | None
    space_group_number: int | None
    space_group_name: str | None
    columns: list[ReflectionColumn]
    datasets: list[ReflectionDataset]
    history: list[str]
    symmetry_operations: list[str]
    sort_order: list[int]
    resolution_range: list[float] | None
    missing_value: float | None
    extra_header_records: list[str]
    def row_count(self) -> int: ...
    def validate(self) -> None: ...
    def column_any(self, labels: list[str]) -> ReflectionColumn | None: ...
    def miller_indices(self) -> NDArray[int32]: ...

def read_mtz(data: bytes) -> ReflectionTable: ...
def write_mtz(table: ReflectionTable) -> bytes: ...
