from .. import Query

def all() -> Query: ...
def none() -> Query: ...
def protein() -> Query: ...
def backbone() -> Query: ...
def sidechain() -> Query: ...
def nucleic() -> Query: ...
def nucleic_backbone() -> Query: ...
def nucleic_base() -> Query: ...
def nucleic_sugar() -> Query: ...
def water() -> Query: ...
def ions() -> Query: ...
def lipids() -> Query: ...
def glycans() -> Query: ...
def hetero() -> Query: ...
def hydrogen() -> Query: ...
def polar_hydrogen() -> Query:
    """Hydrogen bonded to N/O/S in the full topology; unavailable bonds raise E4003."""

def nonpolar_hydrogen() -> Query:
    """Other hydrogen, including unbonded H; unavailable bonds raise E4003."""

def heavy() -> Query: ...
def polymer() -> Query: ...
def ligands() -> Query: ...
def aromatic() -> Query: ...
def helix() -> Query: ...
def strand() -> Query: ...
def sheet() -> Query: ...
def alpha_helix() -> Query: ...
def helix_310() -> Query: ...
def pi_helix() -> Query: ...
def polyproline() -> Query: ...
def bridge() -> Query: ...
def turn() -> Query: ...
def bend() -> Query: ...
def coil() -> Query: ...
def chain(value: str) -> Query: ...
def residue(value: str) -> Query: ...
def atom(value: str) -> Query: ...
def within(radius: float, target: Query) -> Query: ...
def residues_within(radius: float, target: Query) -> Query: ...
