from .. import Query

def all() -> Query: ...
def none() -> Query: ...
def protein() -> Query: ...
def backbone() -> Query: ...
def sidechain() -> Query: ...
def nucleic() -> Query: ...
def nucleic_backbone() -> Query: ...
def nucleic_base() -> Query: ...
def nucleic_sugar() -> Query: ...
def water() -> Query: ...
def ions() -> Query: ...
def lipids() -> Query: ...
def glycans() -> Query: ...
def hetero() -> Query: ...
def hydrogen() -> Query: ...
def heavy() -> Query: ...
def polymer() -> Query: ...
def ligands() -> Query: ...
def aromatic() -> Query: ...
def chain(value: str) -> Query: ...
def residue(value: str) -> Query: ...
def atom(value: str) -> Query: ...
def within(radius: float, target: Query) -> Query: ...
def residues_within(radius: float, target: Query) -> Query: ...
