from os import PathLike
from typing import final
from numpy import float32
from numpy.typing import NDArray
from .typing import Coordinate

class PdbioxError(Exception):
    code: str
    message: str
    remedy: str
    span: tuple[int, int, int, int] | None

class ParseError(PdbioxError): ...
class SchemaError(PdbioxError): ...
class ConsistencyError(PdbioxError): ...
class ConversionError(PdbioxError): ...
class GeometryError(PdbioxError): ...
class PolicyError(PdbioxError): ...
class PdbioxIndexError(PdbioxError, IndexError): ...
class PdbioxKeyError(PdbioxError, KeyError): ...

@final
class Model:
    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int | None: ...
    @property
    def chains(self) -> Chains: ...

@final
class Models:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Model: ...

@final
class Chain:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> str | None: ...
    @property
    def auth_label(self) -> str | None: ...
    @property
    def residues(self) -> Residues: ...

@final
class Chains:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Chain: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

@final
class Residue:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def label_seq_id(self) -> int | None: ...
    @property
    def auth_seq_id(self) -> int | None: ...
    @property
    def ins_code(self) -> str | None: ...
    @property
    def is_het(self) -> bool: ...
    @property
    def atoms(self) -> ResidueAtoms: ...

@final
class Residues:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

@final
class ResidueAtoms:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Atom: ...

@final
class Atom:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def element(self) -> str | None: ...
    @property
    def coord(self) -> Coordinate | None: ...
    @property
    def b_factor(self) -> float | None: ...

@final
class Atoms:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

@final
class Bonds:
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

@final
class CoordinateEdit:
    def __enter__(self) -> NDArray[float32]: ...
    def __exit__(self, exc_type, exc_value, traceback) -> bool: ...

@final
class Structure:
    def __repr__(self) -> str: ...
    @property
    def atom_count(self) -> int: ...
    @property
    def model_count(self) -> int: ...
    @property
    def chain_count(self) -> int: ...
    @property
    def residue_count(self) -> int: ...
    @property
    def models(self) -> Models: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def bonds(self) -> Bonds: ...
    @property
    def xyz(self) -> NDArray[float32]: ...
    @property
    def atoms(self) -> Atoms: ...
    def edit_coordinates(self) -> CoordinateEdit: ...
    def write(self, path: str | PathLike[str]) -> None: ...

def read(path: str | PathLike[str]) -> Structure: ...
