from os import PathLike
from typing import final
from numpy import float32, float64, int64, uint32
from numpy.typing import NDArray
from numpy.ma import MaskedArray
from .typing import Coordinate
from .analysis import AtomDepthOptions, BasePair, BasePairOptions, BondDeviation, CartesianAxis, CationPi, CationPiOptions, Cavity, ChainCompleteness, ChiralityFlag, ChiralityIssue, ChiralityOptions, ChiralityReport, CisPeptide, Clash, Contact, ContactMap, DensityGrid, DensityGridSpec, DsspOptions, FragmentMatch, FragmentReference, GaussianNetworkModel, GnmOptions, HalfSphereExposure, HydrogenBond, HydrogenBondOptions, LinearDensityBin, MissingResidue, NativeContacts, NucleicTorsions, PiStacking, PiStackingOptions, PlanarityFlag, PlanarityOptions, PolymerStatistics, PoreOptions, PoreSample, Pucker, QualityFlag, QualityIssue, RadialBin, RadialOptions, RamachandranBasin, RamachandranOptions, RamachandranRecord, RamachandranRegion, ReferenceAssessment, ReferenceDistribution, ReferenceLibrary, ResidueContact, RotamerDefinition, RotamerFlag, RotamerOptions, RotamerProfile, RotamerReport, SaltBridge, SecondaryStructure, SseKind, StackingKind, StereoConfiguration, SurfaceAreas, SurfaceContactOptions, SurfaceGridOptions, ValenceError, WaterBridge, assess_bond_deviation, assess_ramachandran, atom_depths, buried_surface, cavities, classify_ramachandran, density_map, linear_density, map_fragments, polymer_statistics, pore_profile, solvent_accessible_surface, sugar_pucker
from .chemistry import ComponentDictionary, Element, ElementProperties, IonicRadius, IonicSpin, PeoeAtom, PeoeAtomType, PeoeBond, PeoeOptions, PeoeParameterProfile, RadiusSet, peoe_charges
from .crystallography import SpaceGroup, SymmetryOperation, UnitCell, space_group_by_number, space_group_by_symbol, space_group_settings
from .graph import EdgeDirection, EdgeFeature, EdgeKind, Graph, GraphOptions, MissingFeaturePolicy, NodeFeature, NodeLevel, SpatialBackend
from .geometry import Axes, BackboneCoordinates, BackboneFrame, BackboneTorsions, CircularSummary, EigenOptions, HelixGeometry, Plane, Rigid, Superposition, angle, asphericity, backbone_frames, best_fit_plane, centre_of_mass, centroid, circular_summary, cross, degrees, dihedral, displacement, distance, distance_matrix, distance_matrix_between, distance_squared, dot, gyration_axes, helix_geometry, inertia_tensor, norm, normalise, path_torsions, plane_deviation, principal_axes, radius_of_gyration, rmsd, rmsf, rotation_mean, superpose, torus_summary
from .ml import Dataset, DatasetEntry, DatasetSplit, DatasetWarning, SplitStrategy, write_atom_ipc, write_atom_parquet
from .query import AltlocPolicy, AnalysisPolicy, AssemblyChoice, MissingPolicy, ModelChoice, Namespace, Query, Selection
from .science import Alignment, AlignmentMode, CadContact, CadScore, CeAlignment, CeOptions, CeSignificanceProfile, ChainMapping, ChainSequence, ContactArea, ContactSimilarity, DockQ, DockQOptions, EmptyLddtPolicy, EmptyQsPolicy, EquivalentAtomMapping, FastaRecord, FastqRecord, LadderDirection, LddtOptions, LigandRmsd, LocalCad, MatrixProfile, MsaOptions, QsOptions, RegionOptions, Scoring, SequenceDocument, SequenceDocumentKind, SequenceFormat, SimilarKmer, SimilarKmerOptions, SubstitutionMatrix, Tree, a2m_match_columns, a3m_match_columns, align_global, align_global_banded, align_global_matrix, align_local, align_local_matrix, align_region, align_semi_global, align_semi_global_matrix, analyse_cad_score, analyse_ce_align, analyse_ce_alignments, analyse_contact_map_similarity, analyse_dockq, analyse_equivalent_atom_mappings, analyse_gdt, analyse_gdt_ha, analyse_gdt_ts, analyse_lddt, analyse_ligand_symmetry_rmsd, analyse_map_chains, analyse_qs_score, analyse_tm_score, blosum62, cad_score, ce_align, ce_alignments, chain_sequences, contact_map_similarity, dockq, equivalent_atom_mappings, gdt, gdt_ha, gdt_ts, kmer_counts, lddt, ligand_symmetry_rmsd, load_matrix, map_chains, minimizers, multiple_sequence_alignment, neighbor_joining, parse_a2m, parse_a3m, parse_clustal, parse_fasta, parse_fastq, parse_phylip, parse_stockholm, progressive_msa, qs_score, read_sequence, seed_and_extend, similar_kmers, tm_score, upgma, write_a2m, write_a3m, write_clustal, write_fasta, write_fastq, write_phylip, write_sequence, write_stockholm
from .science import ResidueMatch, analyse_map_sequence_to_structure, analyse_weighted_rmsd, map_sequence_to_structure, weighted_rmsd
from .spatial import AutoBackendProfile, CellGridOptions, KdPeriodicOptions, NeighborPair, NeighborSkinProfile, SpatialPlan, SpatialSearchOptions, atoms_within, atoms_within_with_options, neighbor_pairs, neighbor_pairs_with_options
from .contract import Analysis, Assumption, AssumptionSource, Coverage, Diagnostic, ImpactEstimate, Provenance, Status
from .governed import CartesianFit, SurfaceWorkflowOptions, SurfaceWorkflowResult, analyse_chain_interface, analyse_contacts, analyse_diffusion, analyse_half_sphere_exposure, analyse_nucleic_torsions, analyse_pca, analyse_surface_geometry, analyse_torsion_pca, validate_bond_lengths, validate_cis_peptides, validate_clashes, validate_completeness, validate_planarity, validate_quality, validate_valence

class PdbioxError(Exception):
    code: str
    message: str
    remedy: str
    span: tuple[int, int, int, int] | None
class ParseError(PdbioxError): ...
class SchemaError(PdbioxError): ...
class ConsistencyError(PdbioxError): ...
class ConversionError(PdbioxError): ...
class GeometryError(PdbioxError): ...
class PolicyError(PdbioxError): ...
class PdbioxIndexError(PdbioxError, IndexError): ...
class PdbioxKeyError(PdbioxError, KeyError): ...
@final
class Format:
    Auto: Format
    Mmcif: Format
    Pdbml: Format
    BinaryCif: Format
    Mmtf: Format
    Pdb: Format
    Pqr: Format
    Pdbqt: Format
@final
class ParseMode:
    Strict: ParseMode
    Permissive: ParseMode
    Recover: ParseMode
@final
class MissingElementPolicy:
    PreserveUnknown: MissingElementPolicy
    InferFromAtomName: MissingElementPolicy
@final
class AmbiguousResidueBoundaryPolicy:
    Reject: AmbiguousResidueBoundaryPolicy
    InferFromFileOrder: AmbiguousResidueBoundaryPolicy
@final
class Limits:
    def __init__(self, decompressed_bytes: int, compression_ratio: int, rows_per_category: int, nesting_depth: int, dictionary_entries: int) -> None: ...
    @staticmethod
    def standard() -> Limits: ...
@final
class ReadScope:
    def __init__(self, only_first_model: bool, only_atomic_coords: bool, discard_hydrogens: bool) -> None: ...
    @staticmethod
    def all() -> ReadScope: ...
@final
class ReadOptions:
    def __init__(self, format: Format, mode: ParseMode, scope: ReadScope, missing_element_policy: MissingElementPolicy, ambiguous_residue_boundary_policy: AmbiguousResidueBoundaryPolicy, limits: Limits) -> None: ...
    @staticmethod
    def standard() -> ReadOptions: ...
@final
class ReadReport:
    structure: Structure
    findings: list[str]
@final
class PdbWriteOptions:
    def __init__(self, chain_map: dict[str, str], hybrid36: bool) -> None: ...
@final
class Model:
    @property
    def index(self) -> int: ...
    @property
    def number(self) -> int | None: ...
    @property
    def chains(self) -> Chains: ...
@final
class Models:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Model: ...
@final
class Chain:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> str | None: ...
    @property
    def auth_label(self) -> str | None: ...
    @property
    def residues(self) -> Residues: ...
@final
class Chains:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Chain: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
@final
class Residue:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def label_seq_id(self) -> int | None: ...
    @property
    def auth_seq_id(self) -> int | None: ...
    @property
    def ins_code(self) -> str | None: ...
    @property
    def is_het(self) -> bool: ...
    @property
    def atoms(self) -> ResidueAtoms: ...
@final
class Residues:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Residue: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
@final
class ResidueAtoms:
    def __len__(self) -> int: ...
    def __getitem__(self, key: int | str) -> Atom: ...
@final
class Atom:
    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def auth_name(self) -> str | None: ...
    @property
    def altloc(self) -> str | None: ...
    @property
    def component(self) -> str | None: ...
    @property
    def element(self) -> str | None: ...
    @property
    def coord(self) -> Coordinate | None: ...
    @property
    def b_factor(self) -> float | None: ...
    @property
    def occupancy(self) -> float | None: ...
    @property
    def formal_charge(self) -> int | None: ...
    @property
    def atom_site_id(self) -> int | None: ...

@final
class Atoms:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Atom: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
@final
class Bonds:
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
@final
class CoordinateEdit:
    def __enter__(self) -> NDArray[float32]: ...
    def __exit__(self, exc_type, exc_value, traceback) -> bool: ...
@final
class Structure:
    def __repr__(self) -> str: ...
    @property
    def atom_count(self) -> int: ...
    @property
    def model_count(self) -> int: ...
    @property
    def chain_count(self) -> int: ...
    @property
    def residue_count(self) -> int: ...
    @property
    def models(self) -> Models: ...
    @property
    def chains(self) -> Chains: ...
    @property
    def residues(self) -> Residues: ...
    @property
    def bonds(self) -> Bonds: ...
    @property
    def xyz(self) -> NDArray[float32]: ...
    @property
    def atoms(self) -> Atoms: ...
    def edit_coordinates(self) -> CoordinateEdit: ...
    def resolve_altlocs(self, policy: AnalysisPolicy) -> Analysis[Selection]: ...
    @property
    def cell(self) -> UnitCell | None: ...
    def write(self, path: str | PathLike[str]) -> None: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, stream: object | None = None, *, max_version: tuple[int, int] | None = None, dl_device: tuple[int, int] | None = None, copy: bool | None = None) -> object: ...
    def graph(self, options: GraphOptions) -> Graph: ...
    def select(self, query: Query, *, policy: AnalysisPolicy | None = None, groups: dict[str, Selection] | None = None) -> Selection: ...
    def transformed(self, transform: Rigid, *, selection: Selection | None = None) -> Structure: ...
    def contacts(self, cutoff: float, *, backend: SpatialBackend = SpatialBackend.Auto) -> list[Contact]: ...
    def base_pairs(self, dictionary: ComponentDictionary, options: BasePairOptions) -> list[BasePair]: ...
    def residue_contact_map(self, cutoff: float, minimum_separation: int, backend: SpatialBackend) -> ContactMap: ...
    def half_sphere_exposure(self, radius: float, backend: SpatialBackend) -> list[HalfSphereExposure]: ...
    def chain_interface(self, first: str, second: str, cutoff: float, backend: SpatialBackend) -> list[int]: ...
    def native_contact_fraction(self, target: Structure, cutoff: float, tolerance: float, backend: SpatialBackend) -> NativeContacts: ...
    def surface_contacts(self, radii: NDArray[float32], options: SurfaceContactOptions) -> list[Contact]: ...
    def gaussian_network_model(self, sites: Selection, options: GnmOptions, *, periodic: bool = False) -> GaussianNetworkModel: ...
    def nucleic_torsions(self) -> list[NucleicTorsions]: ...
    def secondary_structure(self, options: DsspOptions) -> list[SecondaryStructure]: ...
    def quality_flags(self) -> list[QualityFlag]: ...
    def bond_length_deviations(self, tolerance: float) -> list[BondDeviation]: ...
    def ligand_geometry_outliers(self, tolerance: float) -> list[BondDeviation]: ...
    def clashes(self, tolerance: float, radius_set: RadiusSet, *, backend: SpatialBackend = SpatialBackend.Auto) -> list[Clash]: ...
    def completeness(self, namespace: Namespace) -> list[ChainCompleteness]: ...
    def cis_peptides(self, threshold_degrees: float) -> list[CisPeptide]: ...
    def nonplanar_aromatic_rings(self, options: PlanarityOptions) -> list[PlanarityFlag]: ...
    def overvalent_atoms(self) -> list[ValenceError]: ...
    def ramachandran(self, options: RamachandranOptions, *, outliers_only: bool = False) -> list[RamachandranRecord]: ...
    def chirality_outliers(self, dictionary: ComponentDictionary, options: ChiralityOptions, *, policy: AnalysisPolicy | None = None) -> ChiralityReport: ...
    def rotamer_outliers(self, dictionary: ComponentDictionary, references: ReferenceLibrary, profile: RotamerProfile, options: RotamerOptions, *, policy: AnalysisPolicy | None = None) -> RotamerReport: ...
    def radial_distribution(self, left: Selection, right: Selection, options: RadialOptions, *, periodic: bool = False) -> list[RadialBin]: ...
    def centre_of_mass_radial_distribution(self, masses: list[float], left: list[Selection], right: list[Selection], options: RadialOptions, *, periodic: bool = False) -> list[RadialBin]: ...
    def coordination_numbers(self, left: Selection, right: Selection, shell: tuple[float, float], *, backend: SpatialBackend = SpatialBackend.Auto, periodic: bool = False) -> list[int]: ...
    def leaflets(self, sites: Selection, connection_distance: float, *, backend: SpatialBackend = SpatialBackend.Auto, periodic: bool = False) -> list[list[int]]: ...
    def hydrogen_bonds(self, options: HydrogenBondOptions) -> list[HydrogenBond]: ...
    def salt_bridges(self, maximum_distance: float, *, backend: SpatialBackend = SpatialBackend.Auto) -> list[SaltBridge]: ...
    def pi_stacking(self, options: PiStackingOptions) -> list[PiStacking]: ...
    def cation_pi(self, options: CationPiOptions) -> list[CationPi]: ...
    def water_bridges(self, options: HydrogenBondOptions) -> list[WaterBridge]: ...
    def to_openmm(self, namespace: Namespace, *, model: int = 0) -> tuple[object, object]: ...
    def to_parmed(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_ase(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_biotite(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_rdkit(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_gemmi(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_biopython(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_mdanalysis(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_mdtraj(self, namespace: Namespace, *, model: int = 0) -> object: ...
    def to_openstructure(self, namespace: Namespace, *, model: int = 0) -> object: ...

def read(path: str | PathLike[str], options: ReadOptions | None = None) -> Structure: ...
def read_with_options(path: str | PathLike[str], options: ReadOptions) -> ReadReport: ...
def read_bytes(data: bytes, options: ReadOptions, *, name: str | None = None) -> ReadReport: ...
def write_mmcif(
    structure: Structure,
    *,
    block_id: str | None = None,
    generate_connection_ids: bool = False,
    connection_type: str | None = None,
) -> str: ...
def write_bcif(structure: Structure) -> bytes: ...
def write_pdb(structure: Structure, options: PdbWriteOptions) -> str: ...

@final
class PeriodicAngle:
    def __init__(self, radians: float) -> None: ...
    @staticmethod
    def from_degrees(degrees: float) -> PeriodicAngle: ...
    @property
    def radians(self) -> float: ...
    @property
    def degrees(self) -> float: ...
    def delta_to(self, other: PeriodicAngle) -> float: ...
    def distance_to(self, other: PeriodicAngle) -> float: ...

@final
class Rotation3:
    def __init__(self, matrix: list[list[float]]) -> None: ...
    @staticmethod
    def exponential(rotation_vector: list[float]) -> Rotation3: ...
    @property
    def matrix(self) -> list[list[float]]: ...
    def logarithm(self) -> list[float]: ...
    def distance_to(self, other: Rotation3) -> float: ...
    def interpolate(self, other: Rotation3, fraction: float) -> Rotation3: ...

@final
class SurfaceMesh:
    @property
    def vertices(self) -> NDArray[float32]: ...
    @property
    def faces(self) -> NDArray[uint32]: ...
    def curvature(self) -> list[tuple[float, float, float, float, float, float, str]]: ...

@final
class PcaResult:
    mean: NDArray[float64]
    eigenvalues: NDArray[float64]
    components: NDArray[float64]
    projections: NDArray[float64]

@final
class DiffusionMap:
    eigenvalues: NDArray[float64]
    coordinates: NDArray[float64]
    graph_components: NDArray[int64]

def surface_mesh(positions: NDArray[float32], radii: NDArray[float32], probe: float, options: SurfaceGridOptions) -> SurfaceMesh: ...
def cartesian_pca(frames: NDArray[float32], fit: CartesianFit, components: int = 3, memory_limit: int = 536870912) -> PcaResult: ...
def torsion_pca(angles: NDArray[float64], components: int = 3, memory_limit: int = 536870912) -> PcaResult: ...
def diffusion_map(distances: NDArray[float64], epsilon: float, time: int = 1, dimensions: int = 3) -> DiffusionMap: ...

@final
class TrajectoryFormat:
    Xtc: TrajectoryFormat
    Trr: TrajectoryFormat
    Dcd: TrajectoryFormat
    AmberNetcdf: TrajectoryFormat
    Tng: TrajectoryFormat
    Gsd: TrajectoryFormat
    H5md: TrajectoryFormat
    Trz: TrajectoryFormat
    Namd: TrajectoryFormat
    AmberRestart: TrajectoryFormat
    AmberAscii: TrajectoryFormat
    Gro: TrajectoryFormat
    Xyz: TrajectoryFormat
    Aims: TrajectoryFormat
    Txyz: TrajectoryFormat
    DlPolyConfig: TrajectoryFormat
    DlPolyHistory: TrajectoryFormat
    CharmmCard: TrajectoryFormat
    Gamess: TrajectoryFormat
    LammpsDump: TrajectoryFormat
    Gromos11: TrajectoryFormat
    Dms: TrajectoryFormat

@final
class TrajectoryUnits:
    def __init__(
        self,
        length: tuple[str, float],
        time: tuple[str, float],
        velocity: tuple[str, float],
        force: tuple[str, float],
    ) -> None: ...
    @staticmethod
    def canonical() -> TrajectoryUnits: ...
    @property
    def length_unit(self) -> str: ...
    @property
    def length_to_angstrom(self) -> float: ...
    @property
    def time_unit(self) -> str: ...
    @property
    def time_to_picosecond(self) -> float: ...
    @property
    def velocity_unit(self) -> str: ...
    @property
    def velocity_to_angstrom_per_picosecond(self) -> float: ...
    @property
    def force_unit(self) -> str: ...
    @property
    def force_to_kilojoule_per_mole_angstrom(self) -> float: ...

@final
class TrajectoryWriteOptions:
    @staticmethod
    def xtc(*, precision: float | None = None) -> TrajectoryWriteOptions: ...
    @staticmethod
    def trr(*, double_precision: bool = False) -> TrajectoryWriteOptions: ...
    @staticmethod
    def dcd(
        *,
        little_endian: bool | None = None,
        title: str | None = None,
        start_step: int | None = None,
        save_interval: int | None = None,
        delta_akma: float | None = None,
    ) -> TrajectoryWriteOptions: ...
    @staticmethod
    def amber_netcdf(*, double_precision: bool = False) -> TrajectoryWriteOptions: ...
    @staticmethod
    def tng(
        *,
        distance_unit_exponent: int | None = None,
        lossy_precision: float | None = None,
        hashes: bool | None = None,
    ) -> TrajectoryWriteOptions: ...
    @staticmethod
    def gsd(length_to_angstrom: float) -> TrajectoryWriteOptions: ...
    @staticmethod
    def h5md(
        *,
        particle_group: str | None = None,
        units: TrajectoryUnits | None = None,
    ) -> TrajectoryWriteOptions: ...
    @staticmethod
    def trz() -> TrajectoryWriteOptions: ...

@final
class Trajectory:
    def __repr__(self) -> str: ...
    def __init__(
        self,
        xyz: NDArray[float32],
        *,
        time: NDArray[float64] | None = None,
        velocities: NDArray[float32] | None = None,
        forces: NDArray[float32] | None = None,
        cells: NDArray[float64] | None = None,
        steps: NDArray[int64] | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    @staticmethod
    def read(
        path: str | PathLike[str],
        *,
        format: TrajectoryFormat | None = None,
        length_to_angstrom: float | None = None,
        particle_group: str | None = None,
        units: TrajectoryUnits | None = None,
    ) -> Trajectory: ...
    def write(
        self,
        path: str | PathLike[str],
        *,
        options: TrajectoryWriteOptions | None = None,
    ) -> None: ...
    @property
    def atom_count(self) -> int: ...
    @property
    def format(self) -> TrajectoryFormat | None: ...
    @property
    def xyz(self) -> NDArray[float32]: ...
    @property
    def velocities(self) -> NDArray[float32] | None: ...
    @property
    def forces(self) -> NDArray[float32] | None: ...
    @property
    def time(self) -> NDArray[float64] | None: ...
    @property
    def dt(self) -> NDArray[float64] | None: ...
    @property
    def cells(self) -> NDArray[float64] | None: ...
    @property
    def steps(self) -> NDArray[int64] | None: ...
    @property
    def precision(self) -> NDArray[float64] | None: ...

@final
class DmsParticle:
    @property
    def atomic_number(self) -> int | None: ...
    @property
    def component(self) -> int | None: ...
    @property
    def nonbonded_type(self) -> int | None: ...
    @property
    def mass(self) -> float | None: ...
    @property
    def charge(self) -> float | None: ...
    @property
    def residue_id(self) -> int | None: ...
    @property
    def residue_name(self) -> str | None: ...
    @property
    def chain(self) -> str | None: ...
    @property
    def segment(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def insertion(self) -> str | None: ...
    @property
    def formal_charge(self) -> float | None: ...
    @property
    def occupancy(self) -> float | None: ...
    @property
    def b_factor(self) -> float | None: ...
    @property
    def temperature_group(self) -> int | None: ...
    @property
    def energy_group(self) -> int | None: ...
    @property
    def ligand_group(self) -> int | None: ...
    @property
    def bias_group(self) -> int | None: ...

@final
class DmsSystem:
    @staticmethod
    def read(path: str | PathLike[str]) -> DmsSystem: ...
    def write(self, path: str | PathLike[str]) -> None: ...
    def __len__(self) -> int: ...
    @property
    def version(self) -> tuple[int, int] | None: ...
    @property
    def particles(self) -> list[DmsParticle]: ...
    @property
    def positions(self) -> NDArray[float64]: ...
    @property
    def velocities(self) -> MaskedArray: ...
    @property
    def bond_indices(self) -> NDArray[uint32]: ...
    @property
    def bond_orders(self) -> NDArray[float64]: ...
    @property
    def cell(self) -> NDArray[float64] | None: ...
