"""Core diagnostics, columns, indexes, and input/output primitives."""

from typing import Any
from ._io_types import CapacityError, TableError

from .core.contract import Analysis, Assumption, AssumptionSource, Coverage, Diagnostic, ImpactEstimate, Provenance, Status
from .chem import Element
from .core.metadata import EntityKind, PolymerKind
from .query import AnalysisPolicy, Selection

from ._native import (
    AROMATIC_ATOM_ANNOTATION, ATOM_RADIUS_ANNOTATION, AUTODOCK_TYPE_ANNOTATION,
    COMPONENT_KIND_ANNOTATION, FORMAL_CHARGE_ANNOTATION, HBOND_ACCEPTOR_ANNOTATION,
    HBOND_DONOR_ANNOTATION, PAE_ANNOTATION, PARTIAL_CHARGE_ANNOTATION, PLDDT_ANNOTATION,
    POLYMER_ATOM_ROLE_ANNOTATION, SEGMENT_ID_ANNOTATION, STEREO_CONFIGURATION_ANNOTATION,
    Aabb, AltId, AmbiguousResidueBoundaryPolicy, AnnotationColumn, AtomAnnotation, AtomAnnotations, AtomChunk, AtomChunkStats,
    ChunkId, CountDifference, MetadataDifference, StructureDifference, structure_difference,
    AtomIndex, AtomRecord, BitVec, ChainRecord, ChainTable, ChunkBuilder, ColumnKind, CoordinateStore,
    ElementMask, EncodedColumn, EntityTable, ExtensionStore, Extremes,
    BondAdjacency, BondIndex, BondOrder, BondProvenance,
    BondRecord, BondTable, BondTableBuilder, ByteSpan, ChainIndex, Compression, CoordinateBlock,
    Format, InputBuffer, InputKind, Limits, MissingElementPolicy, ParseMode, ReadOptions, ReadReport,
    ReadResult, ReadScope, Reader, Select, SelectAll,
    CoordinateGeneration, DictionaryFull, EntityIndex, InstanceId, Interner, ModelIndex, ModelTable,
    OptionalI32, OptionalSymbol, ParentMapping, Position, Presence, ResidueIndex, ResidueRecord,
    ResidueTable, Structure, StructureData, StructureView, StructureEditor, CoordinateEditor,
    Class, Code, ContextItem, Diagnostics, Kind, Rendered, Severity, Strictness,
    SymbolId, TARGET_CHUNK_ATOMS, Topology, ValidityMask,
    bit_width, pack, write_output,
    unpack_one,
)

class Kind:
    Error: Kind
    Warning: Kind

class Severity:
    Info: Severity
    Loose: Severity
    Strict: Severity
    Invalidating: Severity
    Breaking: Severity
    def is_error(self, strictness: Strictness) -> bool: ...
    label: str

class Strictness:
    Strict: Strictness
    Medium: Strictness
    Loose: Strictness

class Class:
    Syntax: Class
    Schema: Class
    Consistency: Class
    Conversion: Class
    Geometry: Class
    Policy: Class
    Resource: Class
    Internal: Class

class Code:
    def __init__(self, kind: Kind, number: int) -> None: ...
    @staticmethod
    def from_text(text: str) -> Code | None: ...
    @staticmethod
    def registered() -> list[Code]: ...
    kind: Kind
    number: int
    class_: Class
    severity: Severity
    cause: str
    remedy: str
    is_registered: bool
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ContextItem:
    label: str
    value: str

class Rendered:
    text: str
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Diagnostics:
    def __init__(self, capacity: int = ...) -> None: ...
    def push(self, finding: Diagnostic) -> None: ...
    worst: Severity | None
    def has_error(self, strictness: Strictness) -> bool: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def as_list(self) -> list[Diagnostic]: ...
    def finish(self) -> list[Diagnostic]: ...

class ColumnKind:
    U8: ColumnKind
    U16: ColumnKind
    U32: ColumnKind
    U64: ColumnKind
    I8: ColumnKind
    I16: ColumnKind
    I32: ColumnKind
    F32: ColumnKind
    SymbolId: ColumnKind

class EncodedColumn:
    @staticmethod
    def plain(values: object, kind: ColumnKind) -> EncodedColumn: ...
    @staticmethod
    def encode(values: object, kind: ColumnKind) -> EncodedColumn: ...
    kind: ColumnKind
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def is_constant(self) -> bool: ...
    def get(self, position: int) -> object | None: ...
    def to_list(self) -> list[object]: ...
    def iter(self) -> list[object]: ...
    def as_slice(self) -> Any | None: ...
    def __repr__(self) -> str: ...

AtomSelection = Selection

class Position:
    byte_offset: int
    line: int
    column: int
    START: Position
    def __init__(self, byte_offset: int, line: int, column: int) -> None: ...
    def advance(self, byte: int) -> Position | None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ByteSpan:
    start: Position
    end: int
    def __init__(self, start: Position, end: int) -> None: ...
    @staticmethod
    def empty(at: Position) -> ByteSpan: ...
    def len(self) -> int | None: ...
    def is_empty(self) -> bool: ...
    def slice(self, source: bytes) -> bytes | None: ...
    def __repr__(self) -> str: ...

class AnnotationColumn:
    @staticmethod
    def boolean(values: list[bool]) -> AnnotationColumn: ...
    @staticmethod
    def integer(values: list[int]) -> AnnotationColumn: ...
    @staticmethod
    def real(values: list[float]) -> AnnotationColumn: ...
    @staticmethod
    def symbol(values: list[SymbolId]) -> AnnotationColumn: ...
    @staticmethod
    def boolean_entries(values: list[bool], presences: list[Presence]) -> AnnotationColumn: ...
    @staticmethod
    def integer_entries(values: list[int], presences: list[Presence]) -> AnnotationColumn: ...
    @staticmethod
    def real_entries(values: list[float], presences: list[Presence]) -> AnnotationColumn: ...
    @staticmethod
    def symbol_entries(values: list[SymbolId], presences: list[Presence]) -> AnnotationColumn: ...
    kind: str
    len: int
    def is_empty(self) -> bool: ...
    def presence(self, atom: int) -> Presence: ...
    def get(self, atom: int) -> tuple[Any, Presence] | None: ...
    values: list[Any]

class Compression:
    NoCompression: Compression
    Gzip: Compression
    Zstd: Compression
    @staticmethod
    def sniff(data: bytes) -> Compression: ...

class InputKind:
    Owned: InputKind
    Mapped: InputKind

class InputBuffer:
    @staticmethod
    def from_bytes(data: bytes) -> InputBuffer: ...
    @staticmethod
    def open(path: str, limits: Limits = ...) -> InputBuffer: ...
    @staticmethod
    def from_reader(data: bytes, limits: Limits = ...) -> InputBuffer: ...
    len: int
    def is_empty(self) -> bool: ...
    kind: InputKind
    origin: str | None
    bytes: bytes
    def with_origin(self, origin: str) -> InputBuffer: ...

class Select:
    def __init__(self) -> None: ...
    def accept_model(self, model: int) -> bool: ...
    def accept_chain(self, chain: int) -> bool: ...
    def accept_residue(self, residue: int) -> bool: ...
    def accept_atom(self, atom: int) -> bool: ...

SelectAll = Select

class Reader:
    @staticmethod
    def read(input: InputBuffer, options: ReadOptions) -> ReadReport: ...

class StructureDifferenceOptions:
    def __init__(self, coordinate_tolerance: float = ...) -> None: ...
    coordinate_tolerance: float

class DifferenceError(Exception):
    pass

class ValueDifference:
    def __init__(self, left: object, right: object) -> None: ...
    left: object
    right: object

class ReadReport:
    structure: Structure
    findings: list[str]

ReadResult = ReadReport

class AtomAnnotation:
    @staticmethod
    def boolean(column: AnnotationColumn) -> AtomAnnotation: ...
    @staticmethod
    def integer(column: AnnotationColumn) -> AtomAnnotation: ...
    @staticmethod
    def real(column: AnnotationColumn) -> AtomAnnotation: ...
    @staticmethod
    def symbol(column: AnnotationColumn) -> AtomAnnotation: ...
    kind: str
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def column(self) -> AnnotationColumn: ...

class AtomAnnotations:
    def __init__(self) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get(self, name: str) -> AtomAnnotation | None: ...
    def insert(self, name: str, annotation: AtomAnnotation) -> AtomAnnotation | None: ...
    def remove(self, name: str) -> AtomAnnotation | None: ...
    def iter(self) -> list[tuple[str, AtomAnnotation]]: ...

class BondTable:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def is_available(self) -> bool: ...
    available: bool
    def get(self, bond: BondIndex) -> BondRecord | None: ...
    def __getitem__(self, index: int) -> BondRecord: ...
    def iter(self) -> list[BondRecord]: ...
    def adjacency(self, atom_count: int) -> BondAdjacency: ...

class BondTableBuilder:
    def __init__(self) -> None: ...
    def push(self, record: BondRecord) -> None: ...
    def finish(self) -> BondTable: ...
    def finish_with_availability(self, available: bool) -> BondTable: ...

class AtomIndex:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> AtomIndex: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> AtomIndex | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class BondIndex:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> BondIndex: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> BondIndex | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class ChainIndex:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> ChainIndex: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> ChainIndex | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class ChunkId:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> ChunkId: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> ChunkId | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class EntityIndex:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> EntityIndex: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> EntityIndex | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class InstanceId:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> InstanceId: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> InstanceId | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class ModelIndex:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> ModelIndex: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> ModelIndex | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class ResidueIndex:
    value: int
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> ResidueIndex: ...
    def get(self) -> int: ...
    def as_usize(self) -> int: ...
    def next(self) -> ResidueIndex | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...

class BondAdjacency:
    def neighbours(self, atom: AtomIndex) -> list[AtomIndex]: ...

class CoordinateGeneration:
    value: int
    INITIAL: CoordinateGeneration
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_raw(value: int) -> CoordinateGeneration: ...
    def get(self) -> int: ...
    def next(self) -> CoordinateGeneration | None: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class Aabb:
    min: tuple[float, float, float]
    max: tuple[float, float, float]
    EMPTY: Aabb
    def __init__(self, min: tuple[float, float, float], max: tuple[float, float, float]) -> None: ...
    @staticmethod
    def empty() -> Aabb: ...
    def is_empty(self) -> bool: ...
    def extend(self, point: tuple[float, float, float]) -> None: ...
    def union(self, other: Aabb) -> None: ...
    def within(self, other: Aabb, distance: float) -> bool: ...

class ElementMask:
    EMPTY: ElementMask
    def __init__(self) -> None: ...
    def insert(self, element: Element) -> None: ...
    def contains(self, element: Element) -> bool: ...
    def is_empty(self) -> bool: ...
    def union_with(self, other: ElementMask) -> None: ...
    def intersects(self, other: ElementMask) -> bool: ...
    def len(self) -> int: ...

class Extremes:
    def __init__(self) -> None: ...
    def observe(self, value: float) -> None: ...
    min: float | None
    max: float | None
    def excludes_above(self, at_least: float) -> bool: ...
    def excludes_below(self, at_most: float) -> bool: ...

class AtomChunkStats:
    bounds: Aabb
    elements: ElementMask
    model: int
    residue_min: int
    residue_max: int
    b_factor: Extremes
    occupancy: Extremes
    has_altloc: bool
    has_missing_coords: bool
    has_hydrogen: bool
    def excludes_element(self, element: Element) -> bool: ...
    def excludes_region(self, region: Aabb, distance: float) -> bool: ...
    def excludes_residues(self, first: int, last: int) -> bool: ...
