from typing import final

class PdbioxError(Exception):
    code: str
    message: str
    remedy: str
    span: tuple[int, int, int, int] | None

class ParseError(PdbioxError): ...
class SchemaError(PdbioxError): ...
class ConsistencyError(PdbioxError): ...
class ConversionError(PdbioxError): ...
class GeometryError(PdbioxError): ...
class PolicyError(PdbioxError): ...
class PolicyConfigError(PdbioxError): ...
class DifferenceError(PdbioxError): ...
class ReexecutionError(PdbioxError): ...
class CapacityError(PdbioxError): ...
class TableError(PdbioxError): ...
class DatasetError(PdbioxError): ...
class GraphError(PdbioxError): ...
class TableFileError(PdbioxError): ...
class DlpackError(PdbioxError): ...
class LoadError(PdbioxError): ...
class CompareError(PdbioxError): ...
class CadError(PdbioxError): ...
class CadConstructionError(PdbioxError): ...
class CeError(PdbioxError): ...
class GovernedCompareError(PdbioxError): ...
class BasePairError(PdbioxError): ...
class CationPiError(PdbioxError): ...
class DensityError(PdbioxError): ...
class DsspBinaryError(PdbioxError): ...
class DsspError(PdbioxError): ...
class DynamicsError(PdbioxError): ...
class EnsembleGeometryError(PdbioxError): ...
class EnsembleSimilarityError(PdbioxError): ...
class EnsembleStatisticsError(PdbioxError): ...
class FragmentMappingError(PdbioxError): ...
class GnmError(PdbioxError): ...
class GovernedAnalysisError(PdbioxError): ...
class GovernedEnsembleError(PdbioxError): ...
class GovernedNativeError(PdbioxError): ...
class HelicalError(PdbioxError): ...
class HseError(PdbioxError): ...
class HydrogenBondError(PdbioxError): ...
class KMeansError(PdbioxError): ...
class NativeError(PdbioxError): ...
class NucleicTorsionError(PdbioxError): ...
class PhysicalKernelError(PdbioxError): ...
class PiStackingError(PdbioxError): ...
class PolymerError(PdbioxError): ...
class PoreError(PdbioxError): ...
class RadialError(PdbioxError): ...
class StandaloneAnalysisError(PdbioxError): ...
class AtomDepthError(PdbioxError): ...
class BuriedSurfaceError(PdbioxError): ...
class SasaError(PdbioxError): ...
class SurfaceGeometryError(PdbioxError): ...
class SurfaceWorkflowError(PdbioxError): ...
class MapStatisticsError(PdbioxError): ...
class MrcError(PdbioxError): ...
class MonomerLibraryReadError(PdbioxError): ...
class RestraintError(PdbioxError): ...
class ReflectionError(PdbioxError): ...
class AltlocOccupancyError(PdbioxError): ...
class AltlocOccupancyKernelError(PdbioxError): ...
class BFactorError(PdbioxError): ...
class BFactorKernelError(PdbioxError): ...
class CcdCompletenessKernelError(PdbioxError): ...
class CompletenessError(PdbioxError): ...
class GovernedMapError(PdbioxError): ...
class LigandGeometryKernelError(PdbioxError): ...
class NucleicGeometryError(PdbioxError): ...
class PlanarityError(PdbioxError): ...
class PlaneRestraintKernelError(PdbioxError): ...
class RamachandranError(PdbioxError): ...
class RealSpaceCorrelationError(PdbioxError): ...
class ReferenceError(PdbioxError): ...
class RotamerError(PdbioxError): ...
class DielectricError(PdbioxError): ...
class DmsError(PdbioxError): ...
class ImdError(PdbioxError): ...
class MsdError(PdbioxError): ...
class PathSimilarityError(PdbioxError): ...
class TrajectoryError(PdbioxError): ...
class TrajectoryIoError(PdbioxError): ...
class UpdatingSelectionError(PdbioxError): ...
class WaterDynamicsError(PdbioxError): ...
class PdbioxIndexError(PdbioxError, IndexError): ...
class PdbioxKeyError(PdbioxError, KeyError): ...

@final
class Format:
    Auto: Format
    Mmcif: Format
    Pdbml: Format
    BinaryCif: Format
    Mmtf: Format
    Pdb: Format
    Pqr: Format
    Pdbqt: Format

@final
class ParseMode:
    Strict: ParseMode
    Permissive: ParseMode
    Recover: ParseMode

@final
class MissingElementPolicy:
    PreserveUnknown: MissingElementPolicy
    InferFromAtomName: MissingElementPolicy

@final
class AmbiguousResidueBoundaryPolicy:
    Reject: AmbiguousResidueBoundaryPolicy
    InferFromFileOrder: AmbiguousResidueBoundaryPolicy
