"""Sequence, phylogeny, and structural-comparison operations."""

from typing import final, Protocol
from numpy import float32, float64, uint32
from numpy.typing import NDArray
from . import Structure
from .core.contract import Analysis
from .chem import ComponentDictionary
from .geom import Rigid
from .query import AnalysisPolicy, Namespace

@final
class Tree:
    @staticmethod
    def from_newick(text: str) -> Tree: ...
    def to_newick(self) -> str: ...
    @property
    def leaf_count(self) -> int: ...
    def ladderized(self, direction: LadderDirection) -> Tree: ...
    def ladderize(self, direction: LadderDirection) -> Tree: ...
    def rerooted_at_leaf(self, leaf: str, fraction_from_leaf: float) -> Tree: ...
    def reroot_at_leaf(self, leaf: str, fraction_from_leaf: float) -> Tree: ...
    def traverse(self, order: TraversalOrder) -> list[Tree]: ...

@final
class LadderDirection:
    Ascending: LadderDirection
    Descending: LadderDirection

@final
class TraversalOrder:
    Preorder: TraversalOrder
    Postorder: TraversalOrder

class NewickError(ValueError): ...
class RerootError(ValueError): ...

def tm_score(model: NDArray[float32], reference: NDArray[float32]) -> float: ...
def gdt_ts(model: NDArray[float32], reference: NDArray[float32]) -> float: ...
def gdt_ha(model: NDArray[float32], reference: NDArray[float32]) -> float: ...
def gdt(model: NDArray[float32], reference: NDArray[float32], cutoffs: list[float]) -> float: ...
def lddt(model: NDArray[float32], reference: NDArray[float32], options: LddtOptions) -> float: ...
def ce_align(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions) -> CeAlignment: ...
def ce_alignments(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions) -> list[CeAlignment]: ...
def qs_score(model: Structure, native: Structure, first_chain: str, second_chain: str, namespace: Namespace, options: QsOptions) -> float: ...
def dockq(model: Structure, native: Structure, receptor: str, ligand: str, namespace: Namespace, options: DockQOptions) -> DockQ: ...
def weighted_rmsd(model: NDArray[float32], reference: NDArray[float32], weights: list[float]) -> float: ...
def cad_contact_areas(positions: NDArray[float32], radii: NDArray[float32], residues: NDArray[uint32], probe: float, density: float) -> list[ContactArea]: ...
def cad_score(reference: list[ContactArea], model: list[ContactArea]) -> CadScore: ...
def contact_map_similarity(first: list[tuple[int, int]], second: list[tuple[int, int]]) -> ContactSimilarity: ...
def equivalent_atom_mappings(dictionary: ComponentDictionary, component_id: str, limit: int) -> list[EquivalentAtomMapping]: ...
def ligand_symmetry_rmsd(reference: NDArray[float32], model: NDArray[float32], dictionary: ComponentDictionary, component_id: str, limit: int) -> LigandRmsd: ...
def analyse_cad_score(reference: list[ContactArea], model: list[ContactArea], policy: AnalysisPolicy) -> Analysis[CadScore]: ...
def analyse_cad_contact_areas(positions: NDArray[float32], radii: NDArray[float32], residues: NDArray[uint32], probe: float, density: float, policy: AnalysisPolicy) -> Analysis[list[ContactArea]]: ...
def analyse_contact_map_similarity(first: list[tuple[int, int]], second: list[tuple[int, int]], policy: AnalysisPolicy) -> Analysis[ContactSimilarity]: ...
def analyse_equivalent_atom_mappings(dictionary: ComponentDictionary, component_id: str, limit: int, policy: AnalysisPolicy) -> Analysis[list[EquivalentAtomMapping]]: ...
def analyse_ligand_symmetry_rmsd(reference: NDArray[float32], model: NDArray[float32], dictionary: ComponentDictionary, component_id: str, limit: int, policy: AnalysisPolicy) -> Analysis[LigandRmsd]: ...
def analyse_gdt(model: NDArray[float32], reference: NDArray[float32], cutoffs: list[float], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_ce_align(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions, policy: AnalysisPolicy) -> Analysis[CeAlignment]: ...
def analyse_ce_alignments(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions, policy: AnalysisPolicy) -> Analysis[list[CeAlignment]]: ...
def analyse_map_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, scoring: Scoring, minimum_identity: float, policy: AnalysisPolicy) -> Analysis[list[ChainMapping]]: ...
def analyse_lddt(model: NDArray[float32], reference: NDArray[float32], options: LddtOptions, policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_tm_score(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_gdt_ts(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_gdt_ha(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_dockq(model: Structure, native: Structure, receptor: str, ligand: str, options: DockQOptions, policy: AnalysisPolicy) -> Analysis[DockQ]: ...
def analyse_qs_score(model: Structure, native: Structure, first_chain: str, second_chain: str, options: QsOptions, policy: AnalysisPolicy) -> Analysis[float]: ...
def chain_sequences(structure: Structure, dictionary: ComponentDictionary, namespace: Namespace) -> list[ChainSequence]: ...
def map_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, namespace: Namespace, scoring: Scoring, minimum_identity: float) -> list[ChainMapping]: ...
def assign_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, namespace: Namespace, scoring: Scoring, minimum_identity: float) -> ChainAssignment: ...
def analyse_assign_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, scoring: Scoring, minimum_identity: float, policy: AnalysisPolicy) -> Analysis[ChainAssignment]: ...
def map_sequence_to_structure(query: bytes, structure: Structure, dictionary: ComponentDictionary, namespace: Namespace, scoring: Scoring) -> list[ResidueMatch]: ...
def analyse_map_sequence_to_structure(query: bytes, structure: Structure, dictionary: ComponentDictionary, scoring: Scoring, policy: AnalysisPolicy) -> Analysis[list[ResidueMatch]]: ...
def analyse_weighted_rmsd(model: NDArray[float32], reference: NDArray[float32], weights: list[float], policy: AnalysisPolicy) -> Analysis[float]: ...
def align_mapping(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping) -> ComparisonAlignment: ...
def measure_mapping(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping, alignment: ComparisonAlignment) -> DistanceMeasurement: ...
def decide_rmsd(measurement: DistanceMeasurement, maximum_rmsd: float) -> ComparisonVerdict: ...
def interface_rmsd(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping, alignment: ComparisonAlignment) -> InterfaceRmsd: ...
def pocket_rmsd(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping, alignment: ComparisonAlignment) -> PocketRmsd: ...
def gdt_with_cutoffs(model: NDArray[float32], reference: NDArray[float32], cutoffs: list[float]) -> float: ...
def lddt_with_options(model: NDArray[float32], reference: NDArray[float32], options: LddtOptions) -> float: ...
def qs_score_in_namespace(model: Structure, native: Structure, first_chain: str, second_chain: str, namespace: Namespace, options: QsOptions) -> float: ...
def dockq_in_namespace(model: Structure, native: Structure, receptor: str, ligand: str, namespace: Namespace, options: DockQOptions) -> DockQ: ...
def governed_comparison_workflow(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping, maximum_rmsd: float, policy: AnalysisPolicy) -> Analysis[tuple[DistanceMeasurement, ComparisonVerdict]]: ...
def governed_interface_rmsd(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping, policy: AnalysisPolicy) -> Analysis[InterfaceRmsd]: ...
def governed_pocket_rmsd(reference: NDArray[float32], model: NDArray[float32], mapping: PointMapping, policy: AnalysisPolicy) -> Analysis[PocketRmsd]: ...
def governed_assign_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, scoring: Scoring, minimum_identity: float, policy: AnalysisPolicy) -> Analysis[ChainAssignment]: ...
def governed_cad_contact_areas(positions: NDArray[float32], radii: NDArray[float32], residues: NDArray[uint32], probe: float, density: float, policy: AnalysisPolicy) -> Analysis[list[ContactArea]]: ...
def governed_cad_score(reference: list[ContactArea], model: list[ContactArea], policy: AnalysisPolicy) -> Analysis[CadScore]: ...
def governed_ce_align(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions, policy: AnalysisPolicy) -> Analysis[CeAlignment]: ...
def governed_ce_alignments(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions, policy: AnalysisPolicy) -> Analysis[list[CeAlignment]]: ...
def governed_contact_map_similarity(first: list[tuple[int, int]], second: list[tuple[int, int]], policy: AnalysisPolicy) -> Analysis[ContactSimilarity]: ...
def governed_dockq(model: Structure, native: Structure, receptor: str, ligand: str, options: DockQOptions, policy: AnalysisPolicy) -> Analysis[DockQ]: ...
def governed_equivalent_atom_mappings(dictionary: ComponentDictionary, component_id: str, limit: int, policy: AnalysisPolicy) -> Analysis[list[EquivalentAtomMapping]]: ...
def governed_gdt_ha(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def governed_gdt_ts(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def governed_gdt_with_cutoffs(model: NDArray[float32], reference: NDArray[float32], cutoffs: list[float], policy: AnalysisPolicy) -> Analysis[float]: ...
def governed_lddt(model: NDArray[float32], reference: NDArray[float32], options: LddtOptions, policy: AnalysisPolicy) -> Analysis[float]: ...
def governed_ligand_symmetry_rmsd(reference: NDArray[float32], model: NDArray[float32], dictionary: ComponentDictionary, component_id: str, limit: int, policy: AnalysisPolicy) -> Analysis[LigandRmsd]: ...
def governed_map_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, scoring: Scoring, minimum_identity: float, policy: AnalysisPolicy) -> Analysis[list[ChainMapping]]: ...
def governed_map_sequence_to_structure(query: bytes, structure: Structure, dictionary: ComponentDictionary, scoring: Scoring, policy: AnalysisPolicy) -> Analysis[list[ResidueMatch]]: ...
def governed_qs_score(model: Structure, native: Structure, first_chain: str, second_chain: str, options: QsOptions, policy: AnalysisPolicy) -> Analysis[float]: ...
def governed_tm_score(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def governed_weighted_rmsd(model: NDArray[float32], reference: NDArray[float32], weights: list[float], policy: AnalysisPolicy) -> Analysis[float]: ...
def align_global(left: bytes, right: bytes, scoring: Scoring | None = None) -> Alignment: ...
def align_local(left: bytes, right: bytes, scoring: Scoring | None = None) -> Alignment: ...
def align_semi_global(left: bytes, right: bytes, scoring: Scoring | None = None) -> Alignment: ...
def align_global_banded(left: bytes, right: bytes, scoring: Scoring, band: int) -> Alignment: ...
def blosum62() -> SubstitutionMatrix: ...
def align_global_matrix(left: bytes, right: bytes, matrix: SubstitutionMatrix, gap_open: int, gap_extend: int) -> Alignment: ...
def align_local_matrix(left: bytes, right: bytes, matrix: SubstitutionMatrix, gap_open: int, gap_extend: int) -> Alignment: ...
def align_semi_global_matrix(left: bytes, right: bytes, matrix: SubstitutionMatrix, gap_open: int, gap_extend: int) -> Alignment: ...
def seed_and_extend(query: bytes, reference: bytes, k: int, scoring: Scoring) -> Alignment | None: ...
def multiple_sequence_alignment(sequences: list[bytes], scoring: Scoring) -> list[bytes]: ...
def progressive_msa(sequences: list[bytes], options: MsaOptions) -> list[bytes]: ...
def parse_a2m(text: str) -> list[FastaRecord]: ...
def a2m_match_columns(sequence: bytes) -> bytes: ...
def write_a2m(records: list[FastaRecord]) -> str: ...
def write_a3m(records: list[FastaRecord]) -> str: ...
def parse_fastq(text: str) -> list[FastqRecord]: ...
def write_fastq(records: list[FastqRecord]) -> str: ...
def read_sequence(text: str, format: SequenceFormat) -> SequenceDocument: ...
def write_sequence(document: SequenceDocument, format: SequenceFormat) -> str: ...
def load_matrix(profile: MatrixProfile) -> SubstitutionMatrix: ...
def similar_kmers(query: bytes, alphabet: bytes, matrix: SubstitutionMatrix, options: SimilarKmerOptions) -> list[SimilarKmer]: ...
def align_region(left: bytes, right: bytes, scoring: Scoring, options: RegionOptions) -> Alignment: ...
def kmer_counts(sequence: bytes, k: int) -> list[tuple[bytes, int]]: ...
def minimizers(sequence: bytes, k: int, window: int) -> list[tuple[int, bytes]]: ...
def parse_fasta(text: str) -> list[FastaRecord]: ...
def write_fasta(records: list[FastaRecord]) -> str: ...
def parse_a3m(text: str) -> list[FastaRecord]: ...
def a3m_match_columns(sequence: bytes) -> bytes: ...
def parse_clustal(text: str) -> list[FastaRecord]: ...
def write_clustal(records: list[FastaRecord]) -> str: ...
def parse_phylip(text: str) -> list[FastaRecord]: ...
def write_phylip(records: list[FastaRecord]) -> str: ...
def parse_stockholm(text: str) -> list[FastaRecord]: ...
def write_stockholm(records: list[FastaRecord]) -> str: ...
def neighbor_joining(labels: list[str], distances: NDArray[float64]) -> Tree | None: ...
def upgma(labels: list[str], distances: NDArray[float64]) -> Tree | None: ...
