from typing import final
from numpy import bool_, float32, float64
from numpy.typing import NDArray
from . import Rotation3

@final
class Rigid:
    def __init__(self, rotation: list[list[float]], translation: list[float]) -> None: ...
    @staticmethod
    def identity() -> Rigid: ...
    @staticmethod
    def translation(offset: list[float]) -> Rigid: ...
    @property
    def rotation(self) -> list[list[float]]: ...
    @property
    def offset(self) -> list[float]: ...
    def inverse(self) -> Rigid: ...
    def then(self, next: Rigid) -> Rigid: ...
    def apply(self, positions: NDArray[float32]) -> NDArray[float32]: ...

@final
class Superposition:
    @property
    def transform(self) -> Rigid: ...
    @property
    def rmsd(self) -> float: ...

@final
class Axes:
    values: list[float]
    vectors: list[list[float]]

@final
class Plane:
    centre: list[float]
    normal: list[float]

@final
class CircularSummary:
    mean: float | None
    resultant: float
    variance: float

@final
class EigenOptions:
    def __init__(self, relative_tolerance: float, maximum_sweeps: int) -> None: ...
    relative_tolerance: float
    maximum_sweeps: int

@final
class BackboneFrame:
    tangent: list[float]
    normal: list[float]
    binormal: list[float]
    curvature: float
    torsion: float | None

@final
class BackboneTorsions:
    phi: float | None
    psi: float | None
    omega: float | None

@final
class BackboneCoordinates:
    def __init__(
        self,
        nitrogen: NDArray[float32],
        alpha_carbon: NDArray[float32],
        carbonyl_carbon: NDArray[float32],
        nitrogen_present: NDArray[bool_],
        alpha_carbon_present: NDArray[bool_],
        carbonyl_carbon_present: NDArray[bool_],
        connected_to_next: NDArray[bool_],
    ) -> None: ...
    def torsions(self) -> list[BackboneTorsions]: ...

@final
class HelixGeometry:
    axis: list[float]
    rise: float
    twist: float

def distance_matrix(positions: NDArray[float32]) -> NDArray[float64]: ...
def distance_matrix_between(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def rmsd(mobile: NDArray[float32], reference: NDArray[float32]) -> float: ...
def rmsf(frames: NDArray[float32]) -> NDArray[float64]: ...
def superpose(mobile: NDArray[float32], reference: NDArray[float32]) -> Superposition: ...
def distance(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def distance_squared(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def displacement(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def dot(left: NDArray[float64], right: NDArray[float64]) -> NDArray[float64]: ...
def cross(left: NDArray[float64], right: NDArray[float64]) -> NDArray[float64]: ...
def norm(vectors: NDArray[float64]) -> NDArray[float64]: ...
def normalise(vectors: NDArray[float64]) -> list[list[float] | None]: ...
def angle(first: NDArray[float32], vertex: NDArray[float32], third: NDArray[float32]) -> list[float | None]: ...
def dihedral(first: NDArray[float32], second: NDArray[float32], third: NDArray[float32], fourth: NDArray[float32]) -> list[float | None]: ...
def degrees(radians: NDArray[float64]) -> NDArray[float64]: ...
def centroid(positions: NDArray[float32]) -> list[float] | None: ...
def centre_of_mass(positions: NDArray[float32], masses: NDArray[float64] | None) -> list[float] | None: ...
def radius_of_gyration(positions: NDArray[float32], masses: NDArray[float64] | None) -> float | None: ...
def inertia_tensor(positions: NDArray[float32], masses: NDArray[float64] | None) -> list[list[float]] | None: ...
def principal_axes(positions: NDArray[float32], masses: NDArray[float64] | None, options: EigenOptions) -> Axes | None: ...
def asphericity(positions: NDArray[float32], options: EigenOptions) -> float | None: ...
def gyration_axes(positions: NDArray[float32], options: EigenOptions) -> Axes | None: ...
def best_fit_plane(positions: NDArray[float32], options: EigenOptions) -> Plane | None: ...
def plane_deviation(positions: NDArray[float32], options: EigenOptions) -> float | None: ...
def circular_summary(radians: NDArray[float64], indeterminate_tolerance: float) -> CircularSummary: ...
def torus_summary(radians: NDArray[float64], indeterminate_tolerance: float) -> list[CircularSummary]: ...
def rotation_mean(matrices: NDArray[float64], matrix_tolerance: float, small_angle_tolerance: float, half_turn_tolerance: float, mean_tolerance: float, maximum_iterations: int) -> Rotation3: ...
def path_torsions(positions: NDArray[float32], present: NDArray[bool_], maximum: int) -> list[float | None]: ...
def backbone_frames(positions: NDArray[float32], present: NDArray[bool_]) -> list[BackboneFrame | None]: ...
def helix_geometry(positions: NDArray[float32], present: NDArray[bool_], options: EigenOptions) -> HelixGeometry | None: ...
