from typing import final
from numpy import float32, float64
from numpy.typing import NDArray
from .analysis import BondDeviation, ChainCompleteness, CisPeptide, Clash, Contact, HalfSphereExposure, NucleicTorsions, PlanarityFlag, PlanarityOptions, QualityFlag, SurfaceGridOptions, ValenceError
from .chemistry import RadiusSet
from .graph import SpatialBackend
from .contract import Analysis
from .query import AnalysisPolicy
from . import DiffusionMap, PcaResult, Structure, SurfaceMesh

@final
class CartesianFit:
    @staticmethod
    def none() -> CartesianFit: ...
    @staticmethod
    def reference(coordinates: NDArray[float32]) -> CartesianFit: ...
    @staticmethod
    def iterative_mean(max_iterations: int, tolerance: float) -> CartesianFit: ...

@final
class SurfaceWorkflowResult:
    mesh: SurfaceMesh
    curvature: list[tuple[float, float, float, float, float, float, str]]
    geodesic_source: int | None
    geodesic_distances: NDArray[float64] | None

@final
class SurfaceWorkflowOptions:
    def __init__(self, selection: str, radii_set: str, probe: float, grid: SurfaceGridOptions, source_vertex: int | None = None) -> None: ...

@final
class FrameAlignment:
    Unaligned: FrameAlignment; Rigid: FrameAlignment
@final
class Linkage:
    Single: Linkage; Complete: Linkage; Average: Linkage
@final
class RemainderPolicy:
    Include: RemainderPolicy; Reject: RemainderPolicy
@final
class EnsembleDistanceMatrix:
    def __init__(self, values: NDArray[float64]) -> None: ...
    size: int; values: list[float]
@final
class Clustering:
    labels: list[int | None]; members: list[list[int]]; medoids: list[int]
@final
class KMeansOptions:
    def __init__(self, initial_centres: list[int], maximum_iterations: int, convergence_tolerance_squared: float) -> None: ...
@final
class KMeans:
    labels: list[int]; centres: list[list[float]]; inertia: float; iterations: int
@final
class HarmonicSimilarityOptions:
    def __init__(self, covariance_regularization: float, memory_limit_bytes: int) -> None: ...
@final
class HarmonicSimilarity:
    mean_term: float; covariance_term: float; distance: float; similarity: float
@final
class GroupVariance:
    atoms: list[int]; variance_by_axis: list[float]; rms_fluctuation: float
@final
class ConvergenceBlock:
    start: int; end: int; block_mean: float; cumulative_mean: float

def analyse_surface_geometry(positions: NDArray[float32], radii: NDArray[float32], options: SurfaceWorkflowOptions, policy: AnalysisPolicy) -> Analysis[SurfaceWorkflowResult]: ...
def analyse_pca(frames: NDArray[float32], *, fit: CartesianFit, components: int, memory_limit: int, policy: AnalysisPolicy) -> Analysis[PcaResult]: ...
def analyse_torsion_pca(angles: NDArray[float64], *, torsion_set: str, components: int, memory_limit: int, policy: AnalysisPolicy) -> Analysis[PcaResult]: ...
def analyse_diffusion(distances: NDArray[float64], *, metric: str, epsilon: float, time: int, dimensions: int, policy: AnalysisPolicy) -> Analysis[DiffusionMap]: ...
def analyse_contacts(structure: Structure, cutoff: float, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[Contact]]: ...
def analyse_chain_interface(structure: Structure, first_chain: str, second_chain: str, cutoff: float, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[int]]: ...
def analyse_half_sphere_exposure(structure: Structure, radius: float, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[HalfSphereExposure]]: ...
def analyse_nucleic_torsions(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[NucleicTorsions]]: ...
def validate_clashes(structure: Structure, tolerance: float, radii: RadiusSet, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[Clash]]: ...
def validate_bond_lengths(structure: Structure, tolerance: float, policy: AnalysisPolicy) -> Analysis[list[BondDeviation]]: ...
def validate_cis_peptides(structure: Structure, threshold_degrees: float, policy: AnalysisPolicy) -> Analysis[list[CisPeptide]]: ...
def validate_planarity(structure: Structure, options: PlanarityOptions, policy: AnalysisPolicy) -> Analysis[list[PlanarityFlag]]: ...
def validate_quality(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[QualityFlag]]: ...
def validate_completeness(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[ChainCompleteness]]: ...
def validate_valence(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[ValenceError]]: ...
def analyse_rmsd_to_reference(frames: NDArray[float32], reference: int, alignment: FrameAlignment, policy: AnalysisPolicy) -> Analysis[list[float]]: ...
def analyse_pairwise_fitted_rmsd(frames: NDArray[float32], memory_limit: int, policy: AnalysisPolicy) -> Analysis[EnsembleDistanceMatrix]: ...
def analyse_pairwise_torus_distance(points: NDArray[float64], weights: NDArray[float64], metric_name: str, memory_limit: int, policy: AnalysisPolicy) -> Analysis[EnsembleDistanceMatrix]: ...
def analyse_generalized_procrustes_mean(frames: NDArray[float32], tolerance: float, maximum_iterations: int, policy: AnalysisPolicy) -> Analysis[list[list[float]]]: ...
def analyse_agglomerative_clustering(distances: EnsembleDistanceMatrix, cluster_count: int, linkage: Linkage, policy: AnalysisPolicy) -> Analysis[Clustering]: ...
def analyse_dbscan_clustering(distances: EnsembleDistanceMatrix, epsilon: float, minimum_points: int, policy: AnalysisPolicy) -> Analysis[Clustering]: ...
def analyse_medoid(distances: EnsembleDistanceMatrix, members: list[int], policy: AnalysisPolicy) -> Analysis[int]: ...
def analyse_kmeans(observations: list[list[float]], options: KMeansOptions, policy: AnalysisPolicy) -> Analysis[KMeans]: ...
def analyse_harmonic_ensemble_similarity(first: list[list[float]], second: list[list[float]], options: HarmonicSimilarityOptions, policy: AnalysisPolicy) -> Analysis[HarmonicSimilarity]: ...
def analyse_cluster_population_similarity(first: list[int], second: list[int], cluster_count: int, policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_group_coordinate_variance(frames: NDArray[float32], groups: list[list[int]], policy: AnalysisPolicy) -> Analysis[list[GroupVariance]]: ...
def analyse_block_convergence(values: list[float], block_size: int, remainder: RemainderPolicy, policy: AnalysisPolicy) -> Analysis[list[ConvergenceBlock]]: ...
