from os import PathLike
from typing import final
from . import Structure

@final
class DatasetEntry:
    @property
    def id(self) -> str: ...
    @property
    def path(self) -> PathLike[str]: ...
    @property
    def atom_count(self) -> int: ...
    @property
    def resolution(self) -> float | None: ...
    @property
    def method(self) -> str | None: ...
    @property
    def deposition_date(self) -> str | None: ...
    @property
    def sequence(self) -> str | None: ...
    @property
    def structure_cluster(self) -> str | None: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def statistics(self) -> dict[str, float]: ...

@final
class SplitStrategy:
    @staticmethod
    def sequence_identity(threshold: float) -> SplitStrategy: ...
    @staticmethod
    def structural_cluster() -> SplitStrategy: ...
    @staticmethod
    def temporal() -> SplitStrategy: ...
    @staticmethod
    def random(seed: int) -> SplitStrategy: ...

@final
class DatasetWarning:
    RandomSplitMayLeak: DatasetWarning

@final
class Dataset:
    def __init__(self, path: str | PathLike[str]) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> DatasetEntry: ...
    def load(self, index: int) -> Structure: ...
    def filter(
        self,
        *,
        resolution_below: float | None = None,
        method: str | None = None,
        minimum_atoms: int | None = None,
        maximum_atoms: int | None = None,
        tag: str | None = None,
    ) -> Dataset: ...
    def split(
        self,
        strategy: SplitStrategy,
        *,
        train: float = 0.8,
        validation: float = 0.1,
        test: float = 0.1,
    ) -> DatasetSplit: ...
    def batches(self, batch_size: int) -> list[Dataset]: ...

@final
class DatasetSplit:
    @property
    def train(self) -> Dataset: ...
    @property
    def validation(self) -> Dataset: ...
    @property
    def test(self) -> Dataset: ...
    @property
    def warnings(self) -> list[DatasetWarning]: ...

def write_atom_ipc(path: str | PathLike[str], structure: Structure) -> None: ...
def write_atom_parquet(path: str | PathLike[str], structure: Structure) -> None: ...
