from typing import final
from numpy import uint32
from numpy.typing import NDArray

@final
class Namespace:
    Label: Namespace
    Auth: Namespace
    Explicit: Namespace

@final
class MissingPolicy:
    Ignore: MissingPolicy
    Report: MissingPolicy
    Indeterminate: MissingPolicy
    Fail: MissingPolicy

@final
class ModelChoice:
    @staticmethod
    def first() -> ModelChoice: ...
    @staticmethod
    def index(index: int) -> ModelChoice: ...
    @staticmethod
    def all() -> ModelChoice: ...
    @staticmethod
    def ensemble() -> ModelChoice: ...

@final
class AltlocPolicy:
    @staticmethod
    def keep_all() -> AltlocPolicy: ...
    @staticmethod
    def conformer_consistent() -> AltlocPolicy: ...
    @staticmethod
    def label(label: str) -> AltlocPolicy: ...
    @staticmethod
    def first() -> AltlocPolicy: ...
    @staticmethod
    def highest_occupancy_per_residue() -> AltlocPolicy: ...
    @staticmethod
    def highest_occupancy_per_atom() -> AltlocPolicy: ...

@final
class AssemblyChoice:
    @staticmethod
    def asymmetric_unit() -> AssemblyChoice: ...
    @staticmethod
    def biological(identifier: str) -> AssemblyChoice: ...
    @staticmethod
    def crystal(radius: float) -> AssemblyChoice: ...

@final
class AnalysisPolicy:
    def __init__(self, *, assembly: AssemblyChoice | None = None, model: ModelChoice | None = None, altloc: AltlocPolicy | None = None, identifiers: Namespace = Namespace.Auth, missing_atoms: MissingPolicy = MissingPolicy.Report) -> None: ...
    @property
    def fingerprint(self) -> str: ...

@final
class Selection:
    def __init__(self, indices: list[int]) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, index: int) -> bool: ...
    @property
    def indices(self) -> NDArray[uint32]: ...
    def intersect(self, other: Selection) -> Selection: ...
    def union(self, other: Selection) -> Selection: ...
    def difference(self, other: Selection) -> Selection: ...
    def complement(self, atom_count: int) -> Selection: ...

@final
class Query:
    def __init__(self, source: str) -> None: ...
