from typing import final
from numpy import float32, float64, uint32
from numpy.typing import NDArray
from . import Structure
from .contract import Analysis
from .chemistry import ComponentDictionary
from .query import AnalysisPolicy, Namespace

@final
class Scoring:
    def __init__(self, match_score: int = 1, mismatch_score: int = -1, gap_open: int = -2, gap_extend: int = -1) -> None: ...

@final
class Alignment:
    @property
    def score(self) -> int: ...
    @property
    def columns(self) -> list[tuple[int | None, int | None]]: ...

@final
class MsaOptions:
    def __init__(self, scoring: Scoring, *, refinement_passes: int = 0) -> None: ...

@final
class EmptyLddtPolicy:
    Perfect: EmptyLddtPolicy
    Error: EmptyLddtPolicy

@final
class LddtOptions:
    def __init__(self, inclusion_radius: float, minimum_reference_distance: float, tolerances: list[float], empty_policy: EmptyLddtPolicy) -> None: ...
    @staticmethod
    def standard(inclusion_radius: float) -> LddtOptions: ...

@final
class CeSignificanceProfile:
    OriginalWindowEight: CeSignificanceProfile

@final
class CeOptions:
    def __init__(self, window_size: int, max_gap: int, max_paths: int, fragment_similarity_threshold: float, path_similarity_threshold: float, significance: CeSignificanceProfile | None) -> None: ...
    @staticmethod
    def original() -> CeOptions: ...

@final
class CeAlignment:
    reference_indices: list[int]
    mobile_indices: list[int]
    fragment_count: int
    similarity: float
    z_score: float | None
    rmsd: float

@final
class EmptyQsPolicy:
    Perfect: EmptyQsPolicy
    Error: EmptyQsPolicy

@final
class QsOptions:
    def __init__(self, contact_distance: float, empty_policy: EmptyQsPolicy) -> None: ...
    @staticmethod
    def standard(contact_distance: float) -> QsOptions: ...

@final
class DockQOptions:
    def __init__(self, contact_distance: float, ligand_scale: float, interface_scale: float) -> None: ...

@final
class DockQ:
    fnat: float
    ligand_rmsd: float
    interface_rmsd: float
    score: float

@final
class ContactArea:
    def __init__(self, first: int, second: int, area: float) -> None: ...
    first: int
    second: int
    area: float

@final
class CadContact:
    first: int
    second: int
    reference_area: float
    model_area: float
    lost_area: float

@final
class LocalCad:
    residue: int
    reference_area: float
    lost_area: float
    score: float

@final
class CadScore:
    score: float
    reference_area: float
    lost_area: float
    contacts: list[CadContact]
    local: list[LocalCad]

@final
class ContactSimilarity:
    shared: int
    union: int
    jaccard: float

@final
class EquivalentAtomMapping:
    reference_to_model: list[int]

@final
class LigandRmsd:
    rmsd: float
    mapping: EquivalentAtomMapping

@final
class ChainSequence:
    label: str
    sequence: bytes

@final
class ChainMapping:
    reference: str
    target: str
    identity: float

@final
class ChainAlternative:
    reference: str
    target: str
    identity: float

@final
class ChainAssignment:
    primary: list[ChainMapping]
    alternatives: list[ChainAlternative]

@final
class ResidueMatch:
    query_position: int
    residue: int

@final
class FastaRecord:
    def __init__(self, id: str, description: str, sequence: bytes) -> None: ...
    id: str
    description: str
    sequence: bytes

@final
class FastqRecord:
    def __init__(self, id: str, description: str, sequence: bytes, quality: bytes) -> None: ...
    id: str
    description: str
    sequence: bytes
    quality: bytes

@final
class SequenceFormat:
    Fasta: SequenceFormat
    Fastq: SequenceFormat
    Stockholm: SequenceFormat
    Clustal: SequenceFormat
    Phylip: SequenceFormat
    A2m: SequenceFormat
    A3m: SequenceFormat
    Newick: SequenceFormat

@final
class SequenceDocumentKind:
    Records: SequenceDocumentKind
    Fastq: SequenceDocumentKind
    Tree: SequenceDocumentKind

@final
class SequenceDocument:
    @staticmethod
    def records(records: list[FastaRecord]) -> SequenceDocument: ...
    @staticmethod
    def fastq(records: list[FastqRecord]) -> SequenceDocument: ...
    @staticmethod
    def tree(tree: Tree) -> SequenceDocument: ...
    @property
    def kind(self) -> SequenceDocumentKind: ...
    def record_values(self) -> list[FastaRecord]: ...
    def fastq_values(self) -> list[FastqRecord]: ...
    def tree_value(self) -> Tree: ...

@final
class MatrixProfile:
    @staticmethod
    def blosum(level: int) -> MatrixProfile: ...
    @staticmethod
    def pam(distance: int) -> MatrixProfile: ...
    @staticmethod
    def identity() -> MatrixProfile: ...
    @staticmethod
    def nuc44() -> MatrixProfile: ...

@final
class SimilarKmerOptions:
    def __init__(self, minimum_score: int, max_results: int, max_candidates: int) -> None: ...

@final
class SimilarKmer:
    word: bytes
    score: int

@final
class AlignmentMode:
    Global: AlignmentMode
    Local: AlignmentMode
    SemiGlobal: AlignmentMode

@final
class RegionOptions:
    def __init__(self, left: tuple[int, int], right: tuple[int, int], mode: AlignmentMode, *, band: int | None = None) -> None: ...

@final
class SubstitutionMatrix:
    def score(self, left: int, right: int) -> int: ...
    name: str
    version: str
    source: str
    retrieved: str

@final
class Tree:
    @staticmethod
    def from_newick(text: str) -> Tree: ...
    def to_newick(self) -> str: ...
    @property
    def leaf_count(self) -> int: ...
    def ladderized(self, direction: LadderDirection) -> Tree: ...
    def rerooted_at_leaf(self, leaf: str, fraction_from_leaf: float) -> Tree: ...

@final
class LadderDirection:
    Ascending: LadderDirection
    Descending: LadderDirection

def tm_score(model: NDArray[float32], reference: NDArray[float32]) -> float: ...
def gdt_ts(model: NDArray[float32], reference: NDArray[float32]) -> float: ...
def gdt_ha(model: NDArray[float32], reference: NDArray[float32]) -> float: ...
def gdt(model: NDArray[float32], reference: NDArray[float32], cutoffs: list[float]) -> float: ...
def lddt(model: NDArray[float32], reference: NDArray[float32], options: LddtOptions) -> float: ...
def ce_align(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions) -> CeAlignment: ...
def ce_alignments(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions) -> list[CeAlignment]: ...
def qs_score(model: Structure, native: Structure, first_chain: str, second_chain: str, namespace: Namespace, options: QsOptions) -> float: ...
def dockq(model: Structure, native: Structure, receptor: str, ligand: str, namespace: Namespace, options: DockQOptions) -> DockQ: ...
def weighted_rmsd(model: NDArray[float32], reference: NDArray[float32], weights: list[float]) -> float: ...
def cad_contact_areas(positions: NDArray[float32], radii: NDArray[float32], residues: NDArray[uint32], probe: float, density: float) -> list[ContactArea]: ...
def cad_score(reference: list[ContactArea], model: list[ContactArea]) -> CadScore: ...
def contact_map_similarity(first: list[tuple[int, int]], second: list[tuple[int, int]]) -> ContactSimilarity: ...
def equivalent_atom_mappings(dictionary: ComponentDictionary, component_id: str, limit: int) -> list[EquivalentAtomMapping]: ...
def ligand_symmetry_rmsd(reference: NDArray[float32], model: NDArray[float32], dictionary: ComponentDictionary, component_id: str, limit: int) -> LigandRmsd: ...
def analyse_cad_score(reference: list[ContactArea], model: list[ContactArea], policy: AnalysisPolicy) -> Analysis[CadScore]: ...
def analyse_cad_contact_areas(positions: NDArray[float32], radii: NDArray[float32], residues: NDArray[uint32], probe: float, density: float, policy: AnalysisPolicy) -> Analysis[list[ContactArea]]: ...
def analyse_contact_map_similarity(first: list[tuple[int, int]], second: list[tuple[int, int]], policy: AnalysisPolicy) -> Analysis[ContactSimilarity]: ...
def analyse_equivalent_atom_mappings(dictionary: ComponentDictionary, component_id: str, limit: int, policy: AnalysisPolicy) -> Analysis[list[EquivalentAtomMapping]]: ...
def analyse_ligand_symmetry_rmsd(reference: NDArray[float32], model: NDArray[float32], dictionary: ComponentDictionary, component_id: str, limit: int, policy: AnalysisPolicy) -> Analysis[LigandRmsd]: ...
def analyse_gdt(model: NDArray[float32], reference: NDArray[float32], cutoffs: list[float], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_ce_align(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions, policy: AnalysisPolicy) -> Analysis[CeAlignment]: ...
def analyse_ce_alignments(reference: NDArray[float32], mobile: NDArray[float32], options: CeOptions, policy: AnalysisPolicy) -> Analysis[list[CeAlignment]]: ...
def analyse_map_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, scoring: Scoring, minimum_identity: float, policy: AnalysisPolicy) -> Analysis[list[ChainMapping]]: ...
def analyse_lddt(model: NDArray[float32], reference: NDArray[float32], options: LddtOptions, policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_tm_score(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_gdt_ts(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_gdt_ha(model: NDArray[float32], reference: NDArray[float32], policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_dockq(model: Structure, native: Structure, receptor: str, ligand: str, options: DockQOptions, policy: AnalysisPolicy) -> Analysis[DockQ]: ...
def analyse_qs_score(model: Structure, native: Structure, first_chain: str, second_chain: str, options: QsOptions, policy: AnalysisPolicy) -> Analysis[float]: ...
def chain_sequences(structure: Structure, dictionary: ComponentDictionary, namespace: Namespace) -> list[ChainSequence]: ...
def map_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, namespace: Namespace, scoring: Scoring, minimum_identity: float) -> list[ChainMapping]: ...
def assign_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, namespace: Namespace, scoring: Scoring, minimum_identity: float) -> ChainAssignment: ...
def analyse_assign_chains(reference: Structure, target: Structure, dictionary: ComponentDictionary, scoring: Scoring, minimum_identity: float, policy: AnalysisPolicy) -> Analysis[ChainAssignment]: ...
def map_sequence_to_structure(query: bytes, structure: Structure, dictionary: ComponentDictionary, namespace: Namespace, scoring: Scoring) -> list[ResidueMatch]: ...
def analyse_map_sequence_to_structure(query: bytes, structure: Structure, dictionary: ComponentDictionary, scoring: Scoring, policy: AnalysisPolicy) -> Analysis[list[ResidueMatch]]: ...
def analyse_weighted_rmsd(model: NDArray[float32], reference: NDArray[float32], weights: list[float], policy: AnalysisPolicy) -> Analysis[float]: ...
def align_global(left: bytes, right: bytes, scoring: Scoring | None = None) -> Alignment: ...
def align_local(left: bytes, right: bytes, scoring: Scoring | None = None) -> Alignment: ...
def align_semi_global(left: bytes, right: bytes, scoring: Scoring | None = None) -> Alignment: ...
def align_global_banded(left: bytes, right: bytes, scoring: Scoring, band: int) -> Alignment: ...
def blosum62() -> SubstitutionMatrix: ...
def align_global_matrix(left: bytes, right: bytes, matrix: SubstitutionMatrix, gap_open: int, gap_extend: int) -> Alignment: ...
def align_local_matrix(left: bytes, right: bytes, matrix: SubstitutionMatrix, gap_open: int, gap_extend: int) -> Alignment: ...
def align_semi_global_matrix(left: bytes, right: bytes, matrix: SubstitutionMatrix, gap_open: int, gap_extend: int) -> Alignment: ...
def seed_and_extend(query: bytes, reference: bytes, k: int, scoring: Scoring) -> Alignment | None: ...
def multiple_sequence_alignment(sequences: list[bytes], scoring: Scoring) -> list[bytes]: ...
def progressive_msa(sequences: list[bytes], options: MsaOptions) -> list[bytes]: ...
def parse_a2m(text: str) -> list[FastaRecord]: ...
def a2m_match_columns(sequence: bytes) -> bytes: ...
def write_a2m(records: list[FastaRecord]) -> str: ...
def write_a3m(records: list[FastaRecord]) -> str: ...
def parse_fastq(text: str) -> list[FastqRecord]: ...
def write_fastq(records: list[FastqRecord]) -> str: ...
def read_sequence(text: str, format: SequenceFormat) -> SequenceDocument: ...
def write_sequence(document: SequenceDocument, format: SequenceFormat) -> str: ...
def load_matrix(profile: MatrixProfile) -> SubstitutionMatrix: ...
def similar_kmers(query: bytes, alphabet: bytes, matrix: SubstitutionMatrix, options: SimilarKmerOptions) -> list[SimilarKmer]: ...
def align_region(left: bytes, right: bytes, scoring: Scoring, options: RegionOptions) -> Alignment: ...
def kmer_counts(sequence: bytes, k: int) -> list[tuple[bytes, int]]: ...
def minimizers(sequence: bytes, k: int, window: int) -> list[tuple[int, bytes]]: ...
def parse_fasta(text: str) -> list[FastaRecord]: ...
def write_fasta(records: list[FastaRecord]) -> str: ...
def parse_a3m(text: str) -> list[FastaRecord]: ...
def a3m_match_columns(sequence: bytes) -> bytes: ...
def parse_clustal(text: str) -> list[FastaRecord]: ...
def write_clustal(records: list[FastaRecord]) -> str: ...
def parse_phylip(text: str) -> list[FastaRecord]: ...
def write_phylip(records: list[FastaRecord]) -> str: ...
def parse_stockholm(text: str) -> list[FastaRecord]: ...
def write_stockholm(records: list[FastaRecord]) -> str: ...
def neighbor_joining(labels: list[str], distances: NDArray[float64]) -> Tree | None: ...
def upgma(labels: list[str], distances: NDArray[float64]) -> Tree | None: ...
