//! Single checked-in operation catalog used by registration and parity checks.

use pyo3::prelude::*;

#[derive(Clone, Copy, Debug)]
pub(crate) struct Capability {
    pub(crate) name: &'static str,
    pub(crate) domain: &'static str,
    pub(crate) feature: &'static str,
    pub(crate) inputs: &'static str,
    pub(crate) result: &'static str,
    pub(crate) policy: bool,
    pub(crate) eager: bool,
    pub(crate) workflow: bool,
    pub(crate) execution_needs: &'static str,
    pub(crate) cost: molframe::Cost,
}

pub(crate) const CAPABILITIES: &[Capability] = &[
    Capability {
        name: "centroid",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "coordinate",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu",
        cost: molframe::Cost::Borrow,
    },
    Capability {
        name: "distance_matrix",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "matrix",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "rmsd",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu",
        cost: molframe::Cost::Borrow,
    },
    Capability {
        name: "atom_contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure|selection",
        result: "ContactTable",
        policy: true,
        eager: true,
        workflow: true,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "sasa",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "lee_richards",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "cavities",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "tm_score",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gdt_ts",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gdt_ha",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "weighted_rmsd",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates, weights",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "align",
        domain: "sequence",
        feature: "sequence",
        inputs: "sequence, sequence",
        result: "Alignment",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "parse_fasta",
        domain: "sequence",
        feature: "sequence",
        inputs: "text",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "write_fasta",
        domain: "sequence",
        feature: "sequence",
        inputs: "records",
        result: "text",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "kmer_counts",
        domain: "sequence",
        feature: "sequence",
        inputs: "sequence",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "to_mmcif",
        domain: "formats",
        feature: "formats",
        inputs: "structure",
        result: "text",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "to_pdb",
        domain: "formats",
        feature: "formats",
        inputs: "structure",
        result: "text",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "to_bcif",
        domain: "formats",
        feature: "formats",
        inputs: "structure",
        result: "bytes",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "write",
        domain: "formats",
        feature: "formats",
        inputs: "structure, path",
        result: "file",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "element",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "symbol",
        result: "ElementProperties",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "vdw_radius",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "symbol",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "vdw_radii",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "clashes",
        domain: "validation",
        feature: "validation",
        inputs: "structure",
        result: "ClashTable",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "neighbor_pairs",
        domain: "spatial",
        feature: "spatial",
        inputs: "coordinates",
        result: "arrays",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
];

pub(crate) fn validate_registration(module: &Bound<'_, PyModule>) -> PyResult<()> {
    for capability in CAPABILITIES {
        debug_assert!(!capability.inputs.is_empty());
        debug_assert!(!capability.result.is_empty());
        debug_assert!(!capability.feature.is_empty());
        debug_assert!(!capability.execution_needs.is_empty());
        debug_assert!(capability.eager || capability.workflow);
        let domain = module.getattr(capability.domain)?;
        if capability.eager {
            domain.getattr(capability.name)?;
        }
        let _ = (capability.policy, capability.cost);
    }
    Ok(())
}
