# SPDX-FileCopyrightText: 2026 Miguel Cárdenas
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# REUSE specification 3.2 — https://reuse.software/spec/
#
# The workspace is dual-licensed MIT OR Apache-2.0. The bundled reference
# data keeps the licences of its upstream sources: ionic radii from mendeleev
# (MIT) and the space-group catalogue from spglib (BSD-3-Clause).

version = 1

[[annotations]]
path = "**/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Miguel Cárdenas"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = "crates/molframe-chem/data/LICENSE.mendeleev"
precedence = "override"
SPDX-FileCopyrightText = "2015 Lukasz Mentel"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "crates/molframe-chem/data/ionic-radii.bin"
precedence = "override"
SPDX-FileCopyrightText = "2015 Lukasz Mentel"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "crates/molframe-xtal/data/LICENSE.spglib"
precedence = "override"
SPDX-FileCopyrightText = "2024 Spglib team"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "crates/molframe-xtal/data/space-groups.bin"
precedence = "override"
SPDX-FileCopyrightText = "2024 Spglib team"
SPDX-License-Identifier = "BSD-3-Clause"
