from collections.abc import Sequence
from typing import final

@final
class UnitCell:
    def __init__(self, lengths: Sequence[float], angles: Sequence[float]) -> None: ...
    def reciprocal_vector(self, hkl: Sequence[int]) -> list[float]: ...
    def reciprocal_spacing_squared(self, hkl: Sequence[int]) -> float: ...
    def d_spacing(self, hkl: Sequence[int]) -> float: ...

@final
class SpaceGroup:
    def __init__(self, hall_number: int) -> None: ...
    def reflection_symmetry(self, hkl: Sequence[int]) -> ReflectionSymmetry: ...
    @property
    def hall_symbol(self) -> str | None: ...
    @property
    def hall_number(self) -> int | None: ...

@final
class ReflectionSymmetry:
    @property
    def centric(self) -> bool: ...
    @property
    def systematically_absent(self) -> bool: ...
    @property
    def epsilon_factor(self) -> int: ...

__all__: list[str]
