from collections.abc import Sequence
from typing import Literal, Protocol, Self, final

from .. import Structure

class IntArray(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class FloatArray(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class IntArray64(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

class ComplexArray(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

@final
class UnitCell:
    def __init__(self, lengths: Sequence[float], angles: Sequence[float]) -> None: ...
    def reciprocal_vector(self, hkl: Sequence[int]) -> list[float]: ...
    def reciprocal_spacing_squared(self, hkl: Sequence[int]) -> float: ...
    def d_spacing(self, hkl: Sequence[int]) -> float: ...

@final
class SpaceGroup:
    def __init__(self, hall_number: int) -> None: ...
    def reflection_symmetry(self, hkl: Sequence[int]) -> ReflectionSymmetry: ...
    @property
    def hall_symbol(self) -> str | None: ...
    @property
    def hall_number(self) -> int | None: ...

@final
class ReflectionSymmetry:
    @property
    def centric(self) -> bool: ...
    @property
    def systematically_absent(self) -> bool: ...
    @property
    def epsilon_factor(self) -> int: ...

@final
class AssemblyInstance:
    @property
    def matrix(self) -> list[float]: ...
    @property
    def chains(self) -> list[str]: ...

@final
class ResolutionBins:
    def __new__(
        cls,
        cell: UnitCell,
        hkl: IntArray,
        *,
        bins: int = 20,
        method: Literal["equal_count", "dstar", "dstar2", "dstar3"] = "equal_count",
    ) -> Self: ...
    def __len__(self) -> int: ...
    @property
    def limits(self) -> FloatArray: ...
    @property
    def midpoints(self) -> FloatArray: ...
    def indices(self, inverse_d2: FloatArray) -> IntArray64: ...
    def d_min(self, bin: int) -> float: ...
    def d_max(self, bin: int) -> float: ...

@final
class ReducedCell:
    @property
    def lengths(self) -> tuple[float, float, float]: ...
    @property
    def angles(self) -> tuple[float, float, float]: ...
    @property
    def change_of_basis(self) -> list[list[int]]: ...
    @property
    def iterations(self) -> int: ...
    @property
    def converged(self) -> bool: ...

def reduce_cell(
    lengths: Sequence[float],
    angles: Sequence[float],
    *,
    epsilon: float = 1e-9,
    iteration_limit: int = 100,
) -> ReducedCell: ...
def normalizers(
    cell: UnitCell,
    space_group: SpaceGroup,
    hkl: IntArray,
    amplitudes: FloatArray,
    bins: ResolutionBins,
) -> FloatArray: ...
def assemblies(structure: Structure) -> list[str]: ...
def assembly(structure: Structure, id: str) -> list[AssemblyInstance]: ...
def structure_factors(structure: Structure, hkl: IntArray) -> ComplexArray: ...

__all__: list[str]
