from __future__ import annotations
from os import PathLike
from typing import Literal, Protocol, final

from .. import Structure

_RadiusSet = Literal["bondi", "amber_united", "charmm", "alvarez"]

class Float32Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

@final
class ElementProperties:
    @property
    def symbol(self) -> str: ...
    @property
    def atomic_number(self) -> int: ...
    @property
    def atomic_weight(self) -> float: ...
    @property
    def covalent_radius(self) -> float | None: ...
    @property
    def electronegativity(self) -> float | None: ...
    @property
    def valence_electrons(self) -> int: ...
    @property
    def period(self) -> int: ...
    @property
    def group(self) -> int | None: ...

def element(symbol: str) -> ElementProperties: ...
def vdw_radius(symbol: str, *, radii: _RadiusSet = "bondi") -> float | None: ...
def vdw_radii(structure: Structure, *, radii: _RadiusSet = "bondi") -> Float32Array: ...
def annotate(
    structure: Structure,
    components: str | PathLike[str],
    *,
    version: str = "unversioned",
) -> Structure: ...
