"""Typed atom annotation columns and canonical annotation keys."""

from . import (
    AROMATIC_ATOM_ANNOTATION, ATOM_RADIUS_ANNOTATION, AUTODOCK_TYPE_ANNOTATION,
    COMPONENT_KIND_ANNOTATION, FORMAL_CHARGE_ANNOTATION, HBOND_ACCEPTOR_ANNOTATION,
    HBOND_DONOR_ANNOTATION, PAE_ANNOTATION, PARTIAL_CHARGE_ANNOTATION,
    PLDDT_ANNOTATION, POLYMER_ATOM_ROLE_ANNOTATION, SEGMENT_ID_ANNOTATION,
    STEREO_CONFIGURATION_ANNOTATION, AnnotationColumn, AtomAnnotation,
    AtomAnnotations,
)

__all__ = [
    "AnnotationColumn", "AtomAnnotation", "AtomAnnotations",
    "AROMATIC_ATOM_ANNOTATION", "ATOM_RADIUS_ANNOTATION",
    "AUTODOCK_TYPE_ANNOTATION", "COMPONENT_KIND_ANNOTATION",
    "FORMAL_CHARGE_ANNOTATION", "HBOND_ACCEPTOR_ANNOTATION",
    "HBOND_DONOR_ANNOTATION", "PAE_ANNOTATION", "PARTIAL_CHARGE_ANNOTATION",
    "PLDDT_ANNOTATION", "POLYMER_ATOM_ROLE_ANNOTATION",
    "SEGMENT_ID_ANNOTATION", "STEREO_CONFIGURATION_ANNOTATION",
]
