[package]
name = "pdbiox-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Typed and textual structural selection plans for pdbiox"

[dependencies]
pdbiox-chem.workspace = true
pdbiox-core.workspace = true

[dev-dependencies]
pdbiox-cif.workspace = true

[lints]
workspace = true
