[package]
name = "pdbiox-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Typed and textual structural selection plans for pdbiox"

[dependencies]
pdbiox-chem.workspace = true
pdbiox-core.workspace = true

[dev-dependencies]
criterion.workspace = true
pdbiox-bench.workspace = true
pdbiox-cif.workspace = true
pdbiox-spatial.workspace = true

[[bench]]
name = "query"
harness = false

[lints]
workspace = true
