from ..core import Structure
from ..core.contract import Analysis
from ..query import AnalysisPolicy
from ..spatial import SpatialBackend
from ._analysis_models import Contact, HalfSphereExposure, NucleicTorsions

def analyse_contacts(structure: Structure, cutoff: float, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[Contact]]: ...
def analyse_chain_interface(structure: Structure, first_chain: str, second_chain: str, cutoff: float, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[int]]: ...
def analyse_half_sphere_exposure(structure: Structure, radius: float, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[HalfSphereExposure]]: ...
def analyse_nucleic_torsions(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[NucleicTorsions]]: ...
