from typing import final
from numpy import bool_, float32, float64
from numpy.typing import NDArray
from . import PeriodicAngle, Rotation3
from . import (
    backbone, eigen, fluctuation, matrix, measure, moments, path,
    periodic_angle, planar, polymer, rotation, superposition, transform,
)

@final
class Centroid:
    def __init__(self, *, positions: NDArray[float32]) -> None: ...
    def execute(self) -> list[float] | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Centroid: ...
    def __repr__(self) -> str: ...

@final
class CentreOfMass:
    def __init__(self, *, positions: NDArray[float32], masses: NDArray[float64] | None = ...) -> None: ...
    def execute(self) -> list[float] | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> CentreOfMass: ...
    def __repr__(self) -> str: ...

@final
class RadiusOfGyration:
    def __init__(self, *, positions: NDArray[float32], masses: NDArray[float64] | None = ...) -> None: ...
    def execute(self) -> float | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> RadiusOfGyration: ...
    def __repr__(self) -> str: ...

@final
class InertiaTensor:
    def __init__(self, *, positions: NDArray[float32], masses: NDArray[float64] | None = ...) -> None: ...
    def execute(self) -> list[list[float]] | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> InertiaTensor: ...
    def __repr__(self) -> str: ...

@final
class PrincipalAxes:
    def __init__(self, *, positions: NDArray[float32], masses: NDArray[float64] | None = ..., options: EigenOptions | None = ...) -> None: ...
    def execute(self) -> Axes | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> PrincipalAxes: ...
    def __repr__(self) -> str: ...

@final
class Asphericity:
    def __init__(self, *, positions: NDArray[float32], options: EigenOptions | None = ...) -> None: ...
    def execute(self) -> float | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Asphericity: ...
    def __repr__(self) -> str: ...

@final
class GyrationAxes:
    def __init__(self, *, positions: NDArray[float32], options: EigenOptions | None = ...) -> None: ...
    def execute(self) -> Axes | None: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> GyrationAxes: ...
    def __repr__(self) -> str: ...

@final
class DistanceMatrixOp:
    def __init__(self, *, positions: NDArray[float32]) -> None: ...
    def execute(self) -> DistanceMatrix: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> DistanceMatrixOp: ...
    def __repr__(self) -> str: ...

@final
class DistanceMatrixBetween:
    def __init__(self, *, left: NDArray[float32], right: NDArray[float32]) -> None: ...
    def execute(self) -> DistanceMatrix: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> DistanceMatrixBetween: ...
    def __repr__(self) -> str: ...

@final
class Rmsf:
    def __init__(self, *, frames: NDArray[float32]) -> None: ...
    def execute(self) -> NDArray[float64]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Rmsf: ...
    def __repr__(self) -> str: ...

class EigenError(ValueError): ...
class FluctuationError(ValueError): ...
class MatrixError(ValueError): ...
class PeriodicError(ValueError): ...
class RotationError(ValueError): ...
class SuperposeError(ValueError): ...

@final
class Rigid:
    IDENTITY: Rigid
    def __init__(self, rotation: list[list[float]], translation: list[float]) -> None: ...
    @staticmethod
    def identity() -> Rigid: ...
    @staticmethod
    def translation(offset: list[float]) -> Rigid: ...
    @property
    def rotation(self) -> list[list[float]]: ...
    @property
    def offset(self) -> list[float]: ...
    def inverse(self) -> Rigid: ...
    def then(self, next: Rigid) -> Rigid: ...
    def apply(self, positions: NDArray[float32]) -> NDArray[float32]: ...
    def apply_one(self, position: list[float]) -> list[float]: ...
    def apply_all(self, positions: NDArray[float32]) -> NDArray[float32]: ...
    def determinant(self) -> float: ...

@final
class Superposition:
    @property
    def transform(self) -> Rigid: ...
    @property
    def rmsd(self) -> float: ...

@final
class Axes:
    values: list[float]
    vectors: list[list[float]]

@final
class Plane:
    centre: list[float]
    normal: list[float]

@final
class CircularSummary:
    mean: float | None
    resultant: float
    variance: float

@final
class EigenOptions:
    STANDARD_RELATIVE_TOLERANCE: float
    STANDARD_MAXIMUM_SWEEPS: int
    def __init__(self, relative_tolerance: float, maximum_sweeps: int) -> None: ...
    @staticmethod
    def standard() -> EigenOptions: ...
    relative_tolerance: float
    maximum_sweeps: int

@final
class Decomposition:
    values: list[float]
    vectors: list[list[float]]
    def dominant(self) -> list[float]: ...
    def vector(self, position: int) -> list[float] | None: ...

@final
class DistanceMatrix:
    @staticmethod
    def from_positions(positions: NDArray[float32]) -> DistanceMatrix: ...
    @staticmethod
    def from_sets(left: NDArray[float32], right: NDArray[float32]) -> DistanceMatrix: ...
    rows: int
    columns: int
    def get(self, row: int, column: int) -> float | None: ...
    def as_slice(self) -> list[float]: ...
    def as_array(self) -> NDArray[float64]: ...

@final
class TorusMetric:
    def __init__(self, weights: list[float]) -> None: ...
    @staticmethod
    def uniform(dimension: int) -> TorusMetric: ...
    dimension: int
    def distance(self, left: NDArray[float64], right: NDArray[float64]) -> float: ...

@final
class BackboneResidue:
    def __init__(self, nitrogen: list[float] | None = None, alpha_carbon: list[float] | None = None, carbonyl_carbon: list[float] | None = None, connected_to_next: bool = False) -> None: ...
    nitrogen: list[float] | None
    alpha_carbon: list[float] | None
    carbonyl_carbon: list[float] | None
    connected_to_next: bool

@final
class RotationOptions:
    STANDARD_MATRIX_TOLERANCE: float
    STANDARD_SMALL_ANGLE_TOLERANCE: float
    STANDARD_HALF_TURN_TOLERANCE: float
    def __init__(self, matrix_tolerance: float, small_angle_tolerance: float, half_turn_tolerance: float) -> None: ...
    @staticmethod
    def standard() -> RotationOptions: ...
    matrix_tolerance: float
    small_angle_tolerance: float
    half_turn_tolerance: float

@final
class RotationMeanOptions:
    def __init__(self, convergence_tolerance: float, maximum_iterations: int, rotation: RotationOptions) -> None: ...
    convergence_tolerance: float
    maximum_iterations: int
    rotation: RotationOptions

@final
class SuperposeOptions:
    STANDARD_COLLINEAR_RELATIVE_TOLERANCE: float
    def __init__(self, collinear_relative_tolerance: float, eigen: EigenOptions) -> None: ...
    @staticmethod
    def standard() -> SuperposeOptions: ...
    collinear_relative_tolerance: float
    eigen: EigenOptions

@final
class BackboneFrame:
    tangent: list[float]
    normal: list[float]
    binormal: list[float]
    curvature: float
    torsion: float | None

@final
class BackboneTorsions:
    phi: float | None
    psi: float | None
    omega: float | None

@final
class BackboneCoordinates:
    def __init__(
        self,
        nitrogen: NDArray[float32],
        alpha_carbon: NDArray[float32],
        carbonyl_carbon: NDArray[float32],
        nitrogen_present: NDArray[bool_],
        alpha_carbon_present: NDArray[bool_],
        carbonyl_carbon_present: NDArray[bool_],
        connected_to_next: NDArray[bool_],
    ) -> None: ...
    def torsions(self) -> list[BackboneTorsions]: ...

@final
class HelixGeometry:
    axis: list[float]
    rise: float
    twist: float

def distance_matrix(positions: NDArray[float32]) -> NDArray[float64]: ...
def distance_matrix_between(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def rmsd(mobile: NDArray[float32], reference: NDArray[float32]) -> float: ...
def rmsd_flat(mobile: NDArray[float32], reference: NDArray[float32]) -> float: ...
def rmsf(frames: NDArray[float32]) -> NDArray[float64]: ...
def superpose(mobile: NDArray[float32], reference: NDArray[float32]) -> Superposition: ...
def distance(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def distance_squared(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def displacement(left: NDArray[float32], right: NDArray[float32]) -> NDArray[float64]: ...
def dot(left: NDArray[float64], right: NDArray[float64]) -> NDArray[float64]: ...
def cross(left: NDArray[float64], right: NDArray[float64]) -> NDArray[float64]: ...
def norm(vectors: NDArray[float64]) -> NDArray[float64]: ...
def normalise(vectors: NDArray[float64]) -> list[list[float] | None]: ...
def angle(first: NDArray[float32], vertex: NDArray[float32], third: NDArray[float32]) -> list[float | None]: ...
def dihedral(first: NDArray[float32], second: NDArray[float32], third: NDArray[float32], fourth: NDArray[float32]) -> list[float | None]: ...
def degrees(radians: NDArray[float64]) -> NDArray[float64]: ...
def centroid(positions: NDArray[float32]) -> list[float] | None: ...
def centre_of_mass(positions: NDArray[float32], masses: NDArray[float64] | None) -> list[float] | None: ...
def radius_of_gyration(positions: NDArray[float32], masses: NDArray[float64] | None) -> float | None: ...
def inertia_tensor(positions: NDArray[float32], masses: NDArray[float64] | None) -> list[list[float]] | None: ...
def principal_axes(positions: NDArray[float32], masses: NDArray[float64] | None, options: EigenOptions) -> Axes | None: ...
def asphericity(positions: NDArray[float32], options: EigenOptions) -> float | None: ...
def gyration_axes(positions: NDArray[float32], options: EigenOptions) -> Axes | None: ...
def best_fit_plane(positions: NDArray[float32], options: EigenOptions) -> Plane | None: ...
def plane_deviation(positions: NDArray[float32], options: EigenOptions) -> float | None: ...
def circular_summary(radians: NDArray[float64], indeterminate_tolerance: float) -> CircularSummary: ...
def torus_summary(radians: NDArray[float64], indeterminate_tolerance: float) -> list[CircularSummary]: ...
def rotation_mean(matrices: NDArray[float64], matrix_tolerance: float, small_angle_tolerance: float, half_turn_tolerance: float, mean_tolerance: float, maximum_iterations: int) -> Rotation3: ...
def path_torsions(positions: NDArray[float32], present: NDArray[bool_], maximum: int) -> list[float | None]: ...
def backbone_frames(positions: NDArray[float32], present: NDArray[bool_]) -> list[BackboneFrame | None]: ...
def helix_geometry(positions: NDArray[float32], present: NDArray[bool_], options: EigenOptions) -> HelixGeometry | None: ...
def asphericity_with_options(positions: NDArray[float32], options: EigenOptions) -> float | None: ...
def best_fit_plane_with_options(positions: NDArray[float32], options: EigenOptions) -> Plane | None: ...
def gyration_axes_with_options(positions: NDArray[float32], options: EigenOptions) -> Axes | None: ...
def helix_geometry_with_options(positions: NDArray[float32], present: NDArray[bool_], options: EigenOptions) -> HelixGeometry | None: ...
def plane_deviation_with_options(positions: NDArray[float32], options: EigenOptions) -> float | None: ...
def principal_axes_with_options(positions: NDArray[float32], masses: NDArray[float64] | None, options: EigenOptions) -> Axes | None: ...
def rotation_mean_with_options(matrices: NDArray[float64], options: RotationMeanOptions) -> Rotation3: ...
def superpose_with_options(mobile: NDArray[float32], reference: NDArray[float32], options: SuperposeOptions) -> Superposition: ...
def symmetric(matrix: NDArray[float64]) -> Decomposition: ...
def symmetric_with_options(matrix: NDArray[float64], options: EigenOptions) -> Decomposition: ...
def backbone_torsions(residues: list[BackboneResidue]) -> list[BackboneTorsions]: ...
