from typing import Any, final
from numpy import float64, int64
from numpy.typing import NDArray
from . import BcifReader, BinaryDocument, Document, Limits, ReadOptions, ReadReport, Structure

@final
class DataType:
    Int8: DataType
    Int16: DataType
    Int32: DataType
    Uint8: DataType
    Uint16: DataType
    Uint32: DataType
    Float32: DataType
    Float64: DataType

@final
class Encoding:
    @staticmethod
    def byte_array(data_type: DataType) -> Encoding: ...
    @staticmethod
    def fixed_point(factor: float, src_type: DataType) -> Encoding: ...
    @staticmethod
    def interval_quantization(minimum: float, maximum: float, num_steps: int, src_type: DataType) -> Encoding: ...
    @staticmethod
    def run_length(src_type: DataType, src_size: int) -> Encoding: ...
    @staticmethod
    def delta(origin: int, src_type: DataType) -> Encoding: ...
    @staticmethod
    def integer_packing(byte_count: int, is_unsigned: bool, src_size: int) -> Encoding: ...
    @staticmethod
    def string_array(data_encoding: list[Encoding], string_data: str, offset_encoding: list[Encoding], offsets: bytes) -> Encoding: ...
    kind: str
    data_type: DataType | None
    src_type: DataType | None
    factor: float | None
    interval: tuple[float, float, int] | None
    origin: int | None
    src_size: int | None
    packing: tuple[int, bool] | None
    def string_array_parts(self) -> tuple[list[Encoding], str, list[Encoding], bytes] | None: ...

@final
class EncodedData:
    def __init__(self, encoding: list[Encoding], data: bytes) -> None: ...
    encoding: list[Encoding]
    data: bytes

@final
class Decoded:
    kind: str
    values: NDArray[int64] | NDArray[float64] | list[str]

class BinaryDocument:
    version: str
    encoder: str
    block_count: int
    def __init__(self, data: bytes, limits: object) -> None: ...
    def category(self, block: int, name: str) -> object | None: ...
    def to_document(self) -> Document: ...

class BcifReader:
    @staticmethod
    def read_document(data: bytes, limits: object) -> BinaryDocument: ...
    @staticmethod
    def read(data: bytes, options: object) -> object: ...

def encode_integers(values: NDArray[int64]) -> EncodedData: ...
def encode_floats(values: NDArray[float64]) -> EncodedData: ...
def encode_interval(values: NDArray[float64], steps: int) -> EncodedData: ...
def encode_strings(values: list[str]) -> EncodedData: ...
def decode(encoded: EncodedData) -> Decoded: ...
def read_document(data: bytes, limits: Limits) -> BinaryDocument: ...
def read(data: bytes, options: ReadOptions) -> ReadReport: ...
def read_with_document(data: bytes, options: ReadOptions) -> tuple[Document, ReadReport]: ...
def write_document(document: Document) -> bytes: ...
def write_structure(structure: Structure) -> bytes: ...
def write_structure_with_options(structure: Structure, *, block_id: str | None = ..., generate_connection_ids: bool = ..., connection_type: str | None = ...) -> bytes: ...
