[package]
name = "molframe-chem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
description = "Deposited-component chemistry and versioned element data for molframe"

[dependencies]
num-traits.workspace = true
molframe-cif.workspace = true
molframe-core.workspace = true

[dev-dependencies]
criterion.workspace = true
molframe-bench.workspace = true

[[bench]]
name = "chem"
harness = false

[lints]
workspace = true
