[package]
name = "pdbiox-seq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Sequence alignment and comparison for pdbiox"

[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "seq"
harness = false

[lints]
workspace = true
