[package]
name = "molframe-seq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
description = "Sequence alignment and comparison for molframe"

[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "seq"
harness = false

[lints]
workspace = true
