[package]
name = "pdbiox-ic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Internal-coordinate conversion and rebuilding for pdbiox"

[dependencies]
pdbiox-core.workspace = true
pdbiox-geom.workspace = true
num-traits.workspace = true

[dev-dependencies]
criterion.workspace = true
pdbiox-bench.workspace = true
pdbiox-cif.workspace = true

[[bench]]
name = "ic"
harness = false

[lints]
workspace = true
