from ..chem import RadiusSet
from ..core import Structure
from ..core.contract import Analysis
from ..query import AnalysisPolicy
from ..spatial import SpatialBackend
from . import BondDeviation, ChainCompleteness, CisPeptide, Clash, PlanarityFlag, PlanarityOptions, QualityFlag, ValenceError

def validate_clashes(structure: Structure, tolerance: float, radii: RadiusSet, backend: SpatialBackend, policy: AnalysisPolicy) -> Analysis[list[Clash]]: ...
def validate_bond_lengths(structure: Structure, tolerance: float, policy: AnalysisPolicy) -> Analysis[list[BondDeviation]]: ...
def validate_cis_peptides(structure: Structure, threshold_degrees: float, policy: AnalysisPolicy) -> Analysis[list[CisPeptide]]: ...
def validate_planarity(structure: Structure, options: PlanarityOptions, policy: AnalysisPolicy) -> Analysis[list[PlanarityFlag]]: ...
def validate_quality(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[QualityFlag]]: ...
def validate_completeness(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[ChainCompleteness]]: ...
def validate_valence(structure: Structure, policy: AnalysisPolicy) -> Analysis[list[ValenceError]]: ...
