//! Catalogued operations of the `analysis` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "dssp",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Table",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "contact_potential",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,charges,grid",
        result: "ScalarGrid",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "atom_contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure|selection",
        result: "ContactTable",
        policy: true,
        eager: true,
        workflow: true,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "hydrogen_bonds",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "salt_bridges",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "contact_map",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,cutoff,min_separation,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "pi_stacking",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,max_centre_distance,max_parallel_angle,min_perpendicular_angle",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "cation_pi",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,max_distance,max_face_angle",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "water_bridges",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,max_distance,min_angle,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "chain_interface",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,first_chain,second_chain,cutoff,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "half_sphere_exposure",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,radius,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "nucleic_torsions",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "native_contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "reference,target,cutoff,tolerance,backend",
        result: "Analysis<dict>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "leaflets",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,sites,connection_distance,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "radial_distribution",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,first,second,minimum_distance,maximum_distance,bins,volume,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "coordination_numbers",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,first,second,minimum_distance,maximum_distance,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "linear_density",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,axis,minimum,maximum,bins,weights",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "density_map",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,origin,spacing,shape,weights",
        result: "Analysis<DensityGrid>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "pore_profile",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,axis_origin,axis_direction,start,end,samples,search_radius,grid_spacing,probe_radius,radii,memory_limit_bytes",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "surface_contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,tolerance,probe,surface_density,minimum_area,radii,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
];
