//! Catalogued operations of the `chemistry` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "apply_polymer_role_profile",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure,components,rules,profile_id,version",
        result: "PolymerRoleReport",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "partial_charges",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure,components?",
        result: "PartialCharges",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "element",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "symbol",
        result: "ElementProperties",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "vdw_radius",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "symbol",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "vdw_radii",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "carbohydrates",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure, component dictionary",
        result: "CarbohydrateReport",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "snfg_symbol",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "component identifier",
        result: "SnfgSymbol | None",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "annotate",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure,components,version",
        result: "Structure",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "polymer_atom_roles",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "none",
        result: "dict[str,int]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
];
