//! Catalogued operations of the `compare` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "tm_score",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gdt_ts",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gdt_ha",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "weighted_rmsd",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates, weights",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "lddt",
        domain: "compare",
        feature: "compare",
        inputs: "model,reference,inclusion_radius,tolerances,minimum_reference_distance",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "dockq",
        domain: "compare",
        feature: "compare",
        inputs: "model,native,receptor,ligand,contact_distance,ligand_scale,interface_scale,chain_names",
        result: "DockQ",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "qs_score",
        domain: "compare",
        feature: "compare",
        inputs: "model,native,first_chain,second_chain,contact_distance,chain_names",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "mapped_dockq",
        domain: "compare",
        feature: "compare",
        inputs: "model,native,receptor,ligand,components,scoring,min_identity,automorphism_limit",
        result: "DockQ,MappedComparison",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "mapped_qs_score",
        domain: "compare",
        feature: "compare",
        inputs: "model,native,first_chain,second_chain,components,scoring,min_identity,automorphism_limit",
        result: "float,MappedComparison",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
];
