//! Catalogued operations of the `crystal` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "assembly_covalent_links",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure,assembly,model",
        result: "AssemblyBond[]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "assemblies",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure",
        result: "str[]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "assembly",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure,id",
        result: "AssemblyInstance[]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "normalizers",
        domain: "crystal",
        feature: "crystal",
        inputs: "cell,space_group,hkl,amplitudes,bins",
        result: "Float64Array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "reduce_cell",
        domain: "crystal",
        feature: "crystal",
        inputs: "lengths,angles,epsilon,iteration_limit",
        result: "ReducedCell",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "structure_factors",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure,hkl",
        result: "Complex128Array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
];
