//! Operations on data a structure carries or is written to: crystallography,
//! formats, motifs, sequences and trajectories.

use super::Capability;

pub(super) const DATA: &[Capability] = &[
    Capability {
        name: "assembly_covalent_links",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure,assembly,model",
        result: "AssemblyBond[]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "align",
        domain: "sequence",
        feature: "sequence",
        inputs: "sequence, sequence",
        result: "Alignment",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "parse_fasta",
        domain: "sequence",
        feature: "sequence",
        inputs: "text",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "write_fasta",
        domain: "sequence",
        feature: "sequence",
        inputs: "records",
        result: "text",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "kmer_counts",
        domain: "sequence",
        feature: "sequence",
        inputs: "sequence",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "to_mmcif",
        domain: "formats",
        feature: "formats",
        inputs: "structure",
        result: "text",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "to_pdb",
        domain: "formats",
        feature: "formats",
        inputs: "structure",
        result: "text",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "to_bcif",
        domain: "formats",
        feature: "formats",
        inputs: "structure",
        result: "bytes",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "write",
        domain: "formats",
        feature: "formats",
        inputs: "structure, path",
        result: "file",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "read",
        domain: "trajectory",
        feature: "trajectory",
        inputs: "path",
        result: "Trajectory",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "rmsd",
        domain: "trajectory",
        feature: "trajectory",
        inputs: "positions",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "assemblies",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure",
        result: "str[]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "assembly",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure,id",
        result: "AssemblyInstance[]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "normalizers",
        domain: "crystal",
        feature: "crystal",
        inputs: "cell,space_group,hkl,amplitudes,bins",
        result: "Float64Array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "reduce_cell",
        domain: "crystal",
        feature: "crystal",
        inputs: "lengths,angles,epsilon,iteration_limit",
        result: "ReducedCell",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "structure_factors",
        domain: "crystal",
        feature: "crystal",
        inputs: "structure,hkl",
        result: "Complex128Array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "evaluate",
        domain: "motif",
        feature: "motif",
        inputs: "structure,specification,components,version,limits",
        result: "MotifReport",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "coordinates",
        domain: "interop",
        feature: "interop",
        inputs: "structure",
        result: "CoordinateTensor",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "graph",
        domain: "interop",
        feature: "interop",
        inputs: "structure,nodes,edges,direction,cutoff,neighbors,node_features,edge_features,missing,backend,periodic",
        result: "Graph",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "write_atoms_ipc",
        domain: "interop",
        feature: "interop",
        inputs: "structure,path,metadata",
        result: "None",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,io",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "write_atoms_parquet",
        domain: "interop",
        feature: "interop",
        inputs: "structure,path,metadata",
        result: "None",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,io",
        cost: molframe::Cost::Materialize,
    },
];
