//! Catalogued operations of the `geometry` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "centroid",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "coordinate",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu",
        cost: molframe::Cost::Borrow,
    },
    Capability {
        name: "distance_matrix",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "matrix",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "rmsd",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu",
        cost: molframe::Cost::Borrow,
    },
    Capability {
        name: "distances",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "angles",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "dihedrals",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "centre_of_mass",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "radius_of_gyration",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "inertia_tensor",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "principal_axes",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gyration_axes",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "asphericity",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "shape_parameter",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "best_fit_plane",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "plane_deviation",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "rmsd_after_fit",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "superpose",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "rmsf",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
];
