//! Operations on structures: analysis, chemistry, comparison, validation,
//! surfaces, spatial search and geometry.

use super::Capability;

pub(super) const STRUCTURAL: &[Capability] = &[
    Capability {
        name: "apply_polymer_role_profile",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure,components,rules,profile_id,version",
        result: "PolymerRoleReport",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "dssp",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Table",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "partial_charges",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure,components?",
        result: "PartialCharges",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "contact_potential",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,charges,grid",
        result: "ScalarGrid",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "centroid",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "coordinate",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu",
        cost: molframe::Cost::Borrow,
    },
    Capability {
        name: "distance_matrix",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates",
        result: "matrix",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "rmsd",
        domain: "geometry",
        feature: "geometry",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: true,
        execution_needs: "cpu",
        cost: molframe::Cost::Borrow,
    },
    Capability {
        name: "atom_contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure|selection",
        result: "ContactTable",
        policy: true,
        eager: true,
        workflow: true,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "sasa",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "lee_richards",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "cavities",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "tm_score",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gdt_ts",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "gdt_ha",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "weighted_rmsd",
        domain: "compare",
        feature: "compare",
        inputs: "coordinates, coordinates, weights",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "element",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "symbol",
        result: "ElementProperties",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "vdw_radius",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "symbol",
        result: "float",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "vdw_radii",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "clashes",
        domain: "validation",
        feature: "validation",
        inputs: "structure",
        result: "ClashTable",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "neighbor_pairs",
        domain: "spatial",
        feature: "spatial",
        inputs: "coordinates",
        result: "arrays",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "hydrogen_bonds",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "salt_bridges",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "carbohydrates",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure, component dictionary",
        result: "CarbohydrateReport",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "snfg_symbol",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "component identifier",
        result: "SnfgSymbol | None",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "annotate",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "structure,components,version",
        result: "Structure",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "contact_map",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,cutoff,min_separation,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "pi_stacking",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,max_centre_distance,max_parallel_angle,min_perpendicular_angle",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "cation_pi",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,max_distance,max_face_angle",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "water_bridges",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,max_distance,min_angle,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "chain_interface",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,first_chain,second_chain,cutoff,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "half_sphere_exposure",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure,radius,backend",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "nucleic_torsions",
        domain: "analysis",
        feature: "analysis",
        inputs: "structure",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "native_contacts",
        domain: "analysis",
        feature: "analysis",
        inputs: "reference,target,cutoff,tolerance,backend",
        result: "Analysis<dict>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,spatial,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "polymer_atom_roles",
        domain: "chemistry",
        feature: "chemistry",
        inputs: "none",
        result: "dict[str,int]",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
];
