//! Catalogued operations of the `surface` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "sasa",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "lee_richards",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "cavities",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "list",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "surface_points",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "SurfacePoints",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "surface_points_at_density",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "SurfacePoints",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "solvent_excluded_surface",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii",
        result: "Mesh",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "buried_surface",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii, in_first",
        result: "BuriedSurface",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "buried_solvent_excluded_surface",
        domain: "surface",
        feature: "surface",
        inputs: "coordinates, radii, roles",
        result: "BuriedSurface",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "atom_depths",
        domain: "surface",
        feature: "surface",
        inputs: "atoms, surface",
        result: "array",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
];
