//! Catalogued operations of the `validation` namespace.

use super::Capability;

pub(super) const ROWS: &[Capability] = &[
    Capability {
        name: "clashes",
        domain: "validation",
        feature: "validation",
        inputs: "structure",
        result: "ClashTable",
        policy: false,
        eager: true,
        workflow: false,
        execution_needs: "cpu",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "bond_length_deviations",
        domain: "validation",
        feature: "validation",
        inputs: "structure,tolerance",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "cis_peptides",
        domain: "validation",
        feature: "validation",
        inputs: "structure,threshold_degrees",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "quality_flags",
        domain: "validation",
        feature: "validation",
        inputs: "structure",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "valence",
        domain: "validation",
        feature: "validation",
        inputs: "structure",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "planarity",
        domain: "validation",
        feature: "validation",
        inputs: "structure,max_deviation",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "completeness",
        domain: "validation",
        feature: "validation",
        inputs: "structure",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "altloc_occupancy_sums",
        domain: "validation",
        feature: "validation",
        inputs: "structure,expected_sum,tolerance",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "ligand_geometry",
        domain: "validation",
        feature: "validation",
        inputs: "structure,tolerance",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
    Capability {
        name: "b_factor_distribution",
        domain: "validation",
        feature: "validation",
        inputs: "structure,outlier_standard_deviations,selection",
        result: "Analysis<Table>",
        policy: true,
        eager: true,
        workflow: false,
        execution_needs: "cpu,memory",
        cost: molframe::Cost::Materialize,
    },
];
