from typing import Any, final
from numpy import bool_, float32, float64
from numpy.typing import NDArray
from .._native.analysis import *
from .._native.analysis import __all__
from . import hbond, salt_bridge, surface_contact_analysis
from ._governed import *
from ..geom import EigenOptions
from .. import Structure
from ..chem import ComponentDictionary
from ..core.contract import Analysis
from ..chem import RadiusSet
from ..spatial import SpatialBackend
from .._io_types import (BasePairError, CationPiError, DensityError, DsspBinaryError, DsspError,
    DynamicsError, EnsembleGeometryError, EnsembleSimilarityError,
    EnsembleStatisticsError, FragmentMappingError, GnmError, GovernedAnalysisError,
    GovernedEnsembleError, GovernedNativeError, HelicalError, HseError,
    HydrogenBondError, KMeansError, NativeError, NucleicTorsionError,
    PhysicalKernelError, PiStackingError, PolymerError, PoreError, RadialError,
    StandaloneAnalysisError)
from ..query import AnalysisPolicy, Namespace, Selection

@final
class StreamlineDirection:
    Forward: StreamlineDirection
    Backward: StreamlineDirection
    Both: StreamlineDirection

@final
class StreamlineOptions:
    def __init__(self, step_size: float = ..., max_steps: int = ..., max_length: float = ..., min_speed: float = ..., direction: StreamlineDirection = ...) -> None: ...
    @property
    def step_size(self) -> float: ...
    @property
    def max_steps(self) -> int: ...
    @property
    def max_length(self) -> float: ...
    @property
    def min_speed(self) -> float: ...

@final
class VectorFieldGrid:
    def __init__(self, origin: tuple[float, float, float], spacing: tuple[float, float, float], shape: tuple[int, int, int], vectors: list[tuple[float, float, float]]) -> None: ...
    def sample(self, point: tuple[float, float, float]) -> tuple[float, float, float] | None: ...

@final
class VectorFieldError:
    InvalidGrid: VectorFieldError
    GridTooLarge: VectorFieldError
    LengthMismatch: VectorFieldError
    NonFiniteInput: VectorFieldError
    InvalidOptions: VectorFieldError

def integrate_streamlines(field: VectorFieldGrid, seeds: list[tuple[float, float, float]], options: StreamlineOptions) -> list[list[tuple[float, float, float]]]: ...

class _StructureOperation:
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...

@final
class HydrogenBonds(_StructureOperation):
    def __init__(self, *, maximum_distance: float = ..., minimum_angle: float = ..., backend: SpatialBackend | None = None, periodic: bool = ..., policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> HydrogenBonds: ...
    def __repr__(self) -> str: ...

@final
class BasePairs(_StructureOperation):
    def __init__(self, *, dictionary: ComponentDictionary, options: BasePairOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> BasePairs: ...
    def __repr__(self) -> str: ...

@final
class SaltBridges(_StructureOperation):
    def __init__(self, *, maximum_distance: float = ..., backend: SpatialBackend | None = None, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> SaltBridges: ...
    def __repr__(self) -> str: ...

@final
class PiStackingAnalysis(_StructureOperation):
    def __init__(self, *, options: PiStackingOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> PiStackingAnalysis: ...
    def __repr__(self) -> str: ...

@final
class CationPiAnalysis(_StructureOperation):
    def __init__(self, *, options: CationPiOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> CationPiAnalysis: ...
    def __repr__(self) -> str: ...

@final
class WaterBridges(_StructureOperation):
    def __init__(self, *, options: WaterBridgeOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> WaterBridges: ...
    def __repr__(self) -> str: ...

@final
class ResidueContacts(_StructureOperation):
    def __init__(self, *, cutoff: float = ..., minimum_separation: int = ..., backend: SpatialBackend | None = None, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> ResidueContacts: ...
    def __repr__(self) -> str: ...

@final
class ChainInterfaceAnalysis(_StructureOperation):
    def __init__(self, *, first_chain: str, second_chain: str, cutoff: float = ..., backend: SpatialBackend | None = None, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> ChainInterfaceAnalysis: ...
    def __repr__(self) -> str: ...

@final
class AssignSecondaryStructure(_StructureOperation):
    def __init__(self, *, options: DsspOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> AssignSecondaryStructure: ...
    def __repr__(self) -> str: ...

@final
class NucleicTorsionAnalysis(_StructureOperation):
    def __init__(self, *, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> NucleicTorsionAnalysis: ...
    def __repr__(self) -> str: ...

@final
class HalfSphereExposureAnalysis(_StructureOperation):
    def __init__(self, *, radius: float, backend: SpatialBackend | None = None, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> HalfSphereExposureAnalysis: ...
    def __repr__(self) -> str: ...

@final
class Gnm(_StructureOperation):
    def __init__(self, *, sites: Selection, options: GnmOptions, periodic: bool = ..., policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Gnm: ...
    def __repr__(self) -> str: ...

@final
class RadialDistribution(_StructureOperation):
    def __init__(self, *, left: Selection, right: Selection, options: RadialOptions, periodic: bool = ..., policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> RadialDistribution: ...
    def __repr__(self) -> str: ...

@final
class CoordinationNumbers(_StructureOperation):
    def __init__(self, *, left: Selection, right: Selection, shell: tuple[float, float], backend: SpatialBackend | None = None, periodic: bool = ..., policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> CoordinationNumbers: ...
    def __repr__(self) -> str: ...

@final
class Leaflets(_StructureOperation):
    def __init__(self, *, sites: Selection, options: LeafletOptions, periodic: bool = ..., policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Leaflets: ...
    def __repr__(self) -> str: ...

@final
class LinearDensity(_StructureOperation):
    def __init__(self, *, weights: NDArray[float64], options: LinearDensityOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> LinearDensity: ...
    def __repr__(self) -> str: ...

@final
class DensityMap(_StructureOperation):
    def __init__(self, *, weights: NDArray[float64], spec: DensityGridSpec, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> DensityMap: ...
    def __repr__(self) -> str: ...

class _AnalysisDensityMap:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> _AnalysisDensityMap: ...
    def __repr__(self) -> str: ...

@final
class PoreProfile(_StructureOperation):
    def __init__(self, *, radii: NDArray[float32], options: PoreOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> PoreProfile: ...
    def __repr__(self) -> str: ...

@final
class SurfaceContacts(_StructureOperation):
    def __init__(self, *, radii: NDArray[float32], options: SurfaceContactOptions, policy: AnalysisPolicy | None = ...) -> None: ...
    def execute(self, structure: Structure) -> Analysis[Any]: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> SurfaceContacts: ...
    def __repr__(self) -> str: ...

from ._analysis_models import (
    BasePair, BasePairOptions, CentreGroup, Clustering, Contact, ContactMap,
    ConvergenceBlock, DsspOptions, DsspSegment, EnsembleDistanceMatrix,
    AnisotropicNetworkModel, AnmOptions, FragmentMatch, FragmentReference,
    FrameAlignment, GaussianNetworkModel, GnmOptions, GroupVariance,
    HalfSphereExposure, HarmonicSimilarity, NormalMode, NormalModeSet,
    HarmonicSimilarityOptions, KMeans, KMeansOptions, Leaflet, LeafletOptions,
    LinearDensityOptions, Linkage, NativeContacts,
    NucleicTorsions, PolymerStatistics, PoreOptions, PoreProfileOptions,
    PoreSample, Pucker, RadialBin, RadialDistributionOptions, RadialOptions,
    RemainderPolicy, ResidueContact, SecondaryStructure, SseKind, SseRecord,
    SurfaceContactOptions,
)
from ._analysis_operations import (
    BaseFrame, CartesianAxis, CationPi, CationPiOptions, ContactTable,
    DensityGrid, DensityGridSpec, DielectricOptions, DielectricResult,
    HelicalOptions, HelicalParameters, HydrogenBond, HydrogenBondOptions,
    LinearDensityBin, PiStacking, PiStackingOptions, SaltBridge, StackingKind,
    WaterBridge, WaterBridgeOptions, WaterDynamicsOptions,
    WaterLag, analyse_agglomerative_clustering,
    analyse_block_convergence,
    analyse_centre_of_mass_radial_distribution,
    analyse_cluster_population_similarity, analyse_dbscan_clustering,
    analyse_dielectric_from_dipoles, analyse_generalized_procrustes_mean,
    analyse_group_coordinate_variance, analyse_harmonic_ensemble_similarity,
    analyse_helical_parameters, analyse_helical_steps, analyse_kmeans,
    analyse_medoid, analyse_pairwise_fitted_rmsd,
    analyse_pairwise_torus_distance,
    analyse_rmsd_to_reference, analyse_water_dynamics, atom_contacts,
    atom_contacts_between, base_pairs, cation_pi, centre_of_mass_radial_distribution,
    chain_interface, coordination_numbers, density_map,
    dielectric_from_dipoles, gaussian_network_model, anisotropic_network_model,
    read_nmd, write_nmd, half_sphere_exposure,
    helical_parameters, helical_steps, identify_leaflets, linear_density,
    linear_density_with_options, map_fragments, native_contact_fraction,
    nucleic_torsions, parse_dssp_output, pi_stacking, polymer_statistics,
    pore_profile, radial_distribution, residue_contact_map, run_dssp,
    salt_bridges, secondary_structure, sugar_pucker, surface_contacts,
    water_bridges, water_dynamics,
)
from .._trajectory_kernels import (
    generalized_procrustes_mean, kmeans, pairwise_fitted_rmsd,
    pairwise_torus_distance, rmsd_to_reference,
)
from .._trajectory_runtime import (
    agglomerative_clustering, block_convergence,
    cluster_population_similarity, dbscan_clustering,
    group_coordinate_variance, harmonic_ensemble_similarity, medoid,
)

from collections.abc import Callable
from os import PathLike
from numpy import float32
from numpy.typing import NDArray
from ..core.execution import ExecutionContext
from .._io_types import MolframeError

class SasaStreamError(MolframeError): ...

def sasa_stream(path: str | PathLike[str], radii: NDArray[float32], probe: float, samples: int, emit: Callable[[int, float | None, float], None], context: ExecutionContext, *, frame_workspace_bytes: int = 8_000_000) -> int: ...
