"""Native structural-analysis, interaction, and dynamics operations."""

from typing import Any, final
from numpy import float32, float64, uint32
from numpy.typing import NDArray
from ..geom import EigenOptions
from .. import Structure
from ..chem import ComponentDictionary
from ..core.contract import Analysis
from .._io_types import (BasePairError, CationPiError, DensityError, DsspBinaryError, DsspError,
    DynamicsError, EnsembleGeometryError, EnsembleSimilarityError,
    EnsembleStatisticsError, FragmentMappingError, GnmError, GovernedAnalysisError,
    GovernedEnsembleError, GovernedNativeError, HelicalError, HseError,
    HydrogenBondError, KMeansError, NativeError, NucleicTorsionError,
    PhysicalKernelError, PiStackingError, PolymerError, PoreError, RadialError,
    StandaloneAnalysisError)
from ..query import AnalysisPolicy, Selection
from ..spatial import SpatialBackend

@final
class HydrogenBondOptions:
    def __init__(self, maximum_distance: float, minimum_angle: float, *, backend: object = ..., periodic: bool = False) -> None: ...

@final
class HydrogenBond:
    donor: int
    hydrogen: int
    acceptor: int
    donor_acceptor_distance: float
    hydrogen_acceptor_distance: float
    angle: float

@final
class SaltBridge:
    anion: int
    cation: int
    distance: float

@final
class StackingKind:
    Parallel: StackingKind
    TShaped: StackingKind

@final
class PiStacking:
    first: int
    second: int
    centre_distance: float
    angle: float
    kind: StackingKind

@final
class PiStackingOptions:
    def __init__(self, maximum_centre_distance: float, maximum_parallel_angle: float, minimum_perpendicular_angle: float, plane_fit: EigenOptions) -> None: ...

@final
class CationPi:
    cation_residue: int
    ring_residue: int
    distance: float

@final
class CationPiOptions:
    def __init__(self, maximum_distance: float, maximum_face_angle: float, plane_fit: EigenOptions) -> None: ...

@final
class WaterBridge:
    water: int
    first: int
    second: int

@final
class WaterBridgeOptions:
    def __init__(self, hydrogen_bonds: HydrogenBondOptions) -> None: ...
    hydrogen_bonds: HydrogenBondOptions

@final
class CartesianAxis:
    X: CartesianAxis
    Y: CartesianAxis
    Z: CartesianAxis

@final
class LinearDensityBin:
    lower: float
    upper: float
    weight: float
    density: float

@final
class DensityGridSpec:
    def __init__(self, origin: list[float], spacing: list[float], shape: list[int]) -> None: ...
    origin: list[float]
    spacing: list[float]
    shape: list[int]

@final
class DensityGrid:
    spec: DensityGridSpec
    density: NDArray[float64]
    excluded_weight: float

def polymer_statistics(path: NDArray[float32]) -> PolymerStatistics: ...
def pore_profile(positions: NDArray[float32], radii: NDArray[float32], options: PoreOptions) -> list[PoreSample]: ...
def linear_density(positions: NDArray[float32], weights: NDArray[float64], axis: CartesianAxis, bounds: tuple[float, float], bins: int) -> list[LinearDensityBin]: ...
def density_map(positions: NDArray[float32], weights: NDArray[float64], spec: DensityGridSpec) -> DensityGrid: ...
def assess_bond_deviation(deviation: BondDeviation, references: ReferenceLibrary, distribution: str) -> ReferenceAssessment: ...
def assess_ramachandran(record: RamachandranRecord, references: ReferenceLibrary, distribution: str) -> ReferenceAssessment: ...
def map_fragments(trace: list[tuple[float, float, float] | None], library: list[FragmentReference], maximum_rmsd: float) -> list[FragmentMatch]: ...
def sugar_pucker(torsions: tuple[float, float, float, float, float]) -> Pucker: ...
def linear_density_with_options(positions: NDArray[float32], weights: NDArray[float64], options: LinearDensityOptions) -> list[LinearDensityBin]: ...
@final
class ContactTable:
    first: NDArray[uint32]
    second: NDArray[uint32]
    distance: NDArray[float32]
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
def atom_contacts(structure: Structure, cutoff: float, backend: SpatialBackend) -> ContactTable: ...
def atom_contacts_between(structure: Structure, left: Selection, right: Selection, cutoff: float, backend: SpatialBackend) -> ContactTable: ...
def base_pairs(structure: Structure, dictionary: ComponentDictionary, options: BasePairOptions, context: object | None = None) -> list[BasePair]: ...
def cation_pi(structure: Structure, options: CationPiOptions) -> list[CationPi]: ...
def chain_interface(structure: Structure, first: str, second: str, cutoff: float, backend: object, context: object | None = None) -> list[int]: ...
def half_sphere_exposure(structure: Structure, radius: float, backend: object, context: object | None = None) -> list[HalfSphereExposure]: ...
def native_contact_fraction(reference: Structure, target: Structure, cutoff: float, tolerance: float, backend: object, context: object | None = None) -> NativeContacts: ...
def pi_stacking(structure: Structure, options: PiStackingOptions) -> list[PiStacking]: ...
def residue_contact_map(structure: Structure, cutoff: float, minimum_separation: int, backend: object, context: object | None = None) -> ContactMap: ...
def salt_bridges(structure: Structure, maximum_distance: float, backend: object, context: object | None = None) -> list[SaltBridge]: ...
def secondary_structure(structure: Structure, options: DsspOptions) -> list[SseRecord]: ...
def surface_contacts(structure: Structure, radii: NDArray[float32], options: SurfaceContactOptions, context: object | None = None) -> ContactTable: ...
def water_bridges(structure: Structure, options: WaterBridgeOptions, context: object | None = None) -> list[WaterBridge]: ...
def gaussian_network_model(structure: Structure, sites: Selection, options: GnmOptions, *, periodic: bool = ..., context: object | None = None) -> GaussianNetworkModel: ...
def anisotropic_network_model(structure: Structure, sites: Selection, options: AnmOptions, *, periodic: bool = ...) -> AnisotropicNetworkModel: ...
def read_nmd(data: bytes) -> NormalModeSet: ...
def write_nmd(set: NormalModeSet) -> str: ...
def nucleic_torsions(structure: Structure) -> list[NucleicTorsions]: ...
def radial_distribution(structure: Structure, left: Selection, right: Selection, options: RadialOptions, *, periodic: bool = ...) -> list[RadialBin]: ...
def centre_of_mass_radial_distribution(structure: Structure, masses: list[float], left: list[CentreGroup], right: list[CentreGroup], options: RadialOptions, *, periodic: bool = ...) -> list[RadialBin]: ...
def coordination_numbers(structure: Structure, left: Selection, right: Selection, shell: tuple[float, float], *, backend: object = ..., periodic: bool = ..., context: object | None = ...) -> list[int]: ...
def identify_leaflets(structure: Structure, sites: Selection, options: LeafletOptions, *, periodic: bool = ...) -> list[Leaflet]: ...
def parse_dssp_output(output: bytes) -> list[DsspSegment]: ...
def run_dssp(executable: str, input: str) -> list[DsspSegment]: ...

@final
class WaterDynamicsOptions:
    def __init__(self, maximum_lag: int) -> None: ...
    maximum_lag: int
@final
class WaterLag:
    lag: int; observations: int; surviving: int; resident: int
    survival_probability: float | None; residence_probability: float | None
@final
class DielectricOptions:
    def __init__(self, volume: float, temperature: float, fluctuation_prefactor: float) -> None: ...
    volume: float; temperature: float; fluctuation_prefactor: float
@final
class DielectricResult:
    mean_dipole: list[float]; fluctuation: float; relative_permittivity: float
@final
class BaseFrame:
    def __init__(self, origin: list[float], x: list[float], y: list[float], z: list[float]) -> None: ...
    origin: list[float]; x: list[float]; y: list[float]; z: list[float]
@final
class HelicalOptions:
    def __init__(self, frame_tolerance: float) -> None: ...
    frame_tolerance: float
@final
class HelicalParameters:
    x_displacement: float; y_displacement: float; z_displacement: float
    x_rotation_degrees: float; y_rotation_degrees: float; z_rotation_degrees: float
def water_dynamics(occupancy: list[Selection], options: WaterDynamicsOptions) -> list[WaterLag]: ...
def analyse_water_dynamics(occupancy: list[Selection], options: WaterDynamicsOptions, policy: AnalysisPolicy) -> Analysis[list[WaterLag]]: ...
def dielectric_from_dipoles(dipoles: list[list[float]], options: DielectricOptions) -> DielectricResult: ...
def analyse_dielectric_from_dipoles(dipoles: list[list[float]], options: DielectricOptions, policy: AnalysisPolicy) -> Analysis[DielectricResult]: ...
def helical_parameters(first: BaseFrame, second: BaseFrame, options: HelicalOptions) -> HelicalParameters: ...
def helical_steps(frames: list[BaseFrame], options: HelicalOptions) -> list[HelicalParameters]: ...
def analyse_helical_parameters(first: BaseFrame, second: BaseFrame, options: HelicalOptions, policy: AnalysisPolicy) -> Analysis[HelicalParameters]: ...
def analyse_helical_steps(frames: list[BaseFrame], options: HelicalOptions, policy: AnalysisPolicy) -> Analysis[list[HelicalParameters]]: ...
def analyse_centre_of_mass_radial_distribution(structure: Structure, masses: list[float], left: list[Selection], right: list[Selection], options: RadialOptions, policy: AnalysisPolicy) -> Analysis[list[RadialBin]]: ...
def analyse_rmsd_to_reference(frames: NDArray[float32], reference: int, alignment: FrameAlignment, policy: AnalysisPolicy) -> Analysis[list[float]]: ...
def analyse_pairwise_fitted_rmsd(frames: NDArray[float32], memory_limit: int, policy: AnalysisPolicy) -> Analysis[EnsembleDistanceMatrix]: ...
def analyse_pairwise_torus_distance(points: NDArray[float64], weights: NDArray[float64], metric_name: str, memory_limit: int, policy: AnalysisPolicy) -> Analysis[EnsembleDistanceMatrix]: ...
def analyse_generalized_procrustes_mean(frames: NDArray[float32], tolerance: float, maximum_iterations: int, policy: AnalysisPolicy) -> Analysis[NDArray[float32]]: ...
def analyse_agglomerative_clustering(distances: EnsembleDistanceMatrix, cluster_count: int, linkage: Linkage, policy: AnalysisPolicy) -> Analysis[Clustering]: ...
def analyse_dbscan_clustering(distances: EnsembleDistanceMatrix, epsilon: float, minimum_points: int, policy: AnalysisPolicy) -> Analysis[Clustering]: ...
def analyse_medoid(distances: EnsembleDistanceMatrix, members: list[int], policy: AnalysisPolicy) -> Analysis[int]: ...
def analyse_kmeans(observations: NDArray[float64], options: KMeansOptions, policy: AnalysisPolicy) -> Analysis[KMeans]: ...
def analyse_harmonic_ensemble_similarity(first: list[list[float]], second: list[list[float]], options: HarmonicSimilarityOptions, policy: AnalysisPolicy) -> Analysis[HarmonicSimilarity]: ...
def analyse_cluster_population_similarity(first: list[int], second: list[int], cluster_count: int, policy: AnalysisPolicy) -> Analysis[float]: ...
def analyse_group_coordinate_variance(frames: NDArray[float32], groups: list[list[int]], policy: AnalysisPolicy) -> Analysis[list[GroupVariance]]: ...
def analyse_block_convergence(values: list[float], block_size: int, remainder: RemainderPolicy, policy: AnalysisPolicy) -> Analysis[list[ConvergenceBlock]]: ...
