from os import PathLike
from .._trajectory import Timestep

class GsdError(Exception): ...
class GsdOptions:
    def __init__(self, length_to_angstrom: float) -> None: ...
    length_to_angstrom: float
class GsdTrajectory:
    frames: list[Timestep]
    steps: list[int]
def parse_gsd(path: str | PathLike[str], options: GsdOptions) -> GsdTrajectory: ...
def write_gsd(path: str | PathLike[str], frames: list[Timestep], options: GsdOptions) -> None: ...
