from collections.abc import Sequence
from typing import Literal, Protocol, final

@final
class Alignment:
    @property
    def score(self) -> int: ...
    @property
    def columns(self) -> list[tuple[int | None, int | None]]: ...
    @property
    def aligned(self) -> tuple[str, str]: ...
    def __len__(self) -> int: ...

@final
class FastaRecord:
    def __init__(self, id: str, sequence: str, description: str = "") -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def sequence(self) -> str: ...
    def __len__(self) -> int: ...

@final
class Scoring:
    def __init__(
        self,
        *,
        match_score: int = 1,
        mismatch_score: int = -1,
        gap_open: int = -2,
        gap_extend: int = -1,
    ) -> None: ...
    @property
    def match_score(self) -> int: ...
    @property
    def mismatch_score(self) -> int: ...
    @property
    def gap_open(self) -> int: ...
    @property
    def gap_extend(self) -> int: ...

def align(
    left: str,
    right: str,
    *,
    mode: Literal["global", "local", "semi_global"] = "global",
    scoring: Scoring | None = None,
    matrix: SubstitutionMatrix | None = None,
    gap_open: int | None = None,
    gap_extend: int | None = None,
) -> Alignment:
    """Align two sequences; with ``matrix`` the gap costs must be stated."""

def parse_fasta(text: str) -> list[FastaRecord]: ...
def write_fasta(records: Sequence[FastaRecord]) -> str: ...
def kmer_counts(sequence: str, k: int) -> list[tuple[str, int]]: ...
def msa(
    sequences: Sequence[str],
    *,
    scoring: Scoring,
    refinement_passes: int = 0,
    memory_limit: int | None = None,
) -> list[str]:
    """Align several sequences progressively into equal-length rows with ``-`` gaps."""

def neighbor_joining(labels: Sequence[str], distances: Distances) -> Tree: ...
def upgma(labels: Sequence[str], distances: Distances) -> Tree: ...

class Distances(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

@final
class SubstitutionMatrix:
    @staticmethod
    def blosum(level: int) -> SubstitutionMatrix: ...
    @staticmethod
    def pam(distance: int) -> SubstitutionMatrix: ...
    @staticmethod
    def identity() -> SubstitutionMatrix: ...
    @staticmethod
    def nuc44() -> SubstitutionMatrix: ...
    def score(self, first: str, second: str) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def source(self) -> str: ...

@final
class Tree:
    @staticmethod
    def from_newick(text: str) -> Tree: ...
    def newick(self) -> str: ...
    @property
    def leaf_count(self) -> int: ...
    def leaves(self) -> list[str]: ...
    def ladderize(self, direction: Literal["ascending", "descending"]) -> Tree: ...
    def reroot_at_leaf(self, leaf: str, fraction: float) -> Tree: ...
