from __future__ import annotations
from collections.abc import Sequence
from typing import Literal, final

@final
class Alignment:
    @property
    def score(self) -> int: ...
    @property
    def columns(self) -> list[tuple[int | None, int | None]]: ...
    @property
    def aligned(self) -> tuple[str, str]: ...
    def __len__(self) -> int: ...

@final
class FastaRecord:
    def __init__(self, id: str, sequence: str, description: str = "") -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def sequence(self) -> str: ...
    def __len__(self) -> int: ...

def align(
    left: str,
    right: str,
    *,
    mode: Literal["global", "local", "semi_global"] = "global",
    match_score: int = 1,
    mismatch_score: int = -1,
    gap_open: int = -2,
    gap_extend: int = -1,
) -> Alignment: ...
def parse_fasta(text: str) -> list[FastaRecord]: ...
def write_fasta(records: Sequence[FastaRecord]) -> str: ...
def kmer_counts(sequence: str, k: int) -> list[tuple[str, int]]: ...
