from os import PathLike
from ..core.contract import Diagnostic
from . import ReadOptions, ReadReport, cif_read
from . import document, lexer

class Quoting:
    Bare: Quoting
    Single: Quoting
    Double: Quoting
    Text: Quoting

class CifToken:
    kind: str
    text: str | None
    quoting: Quoting | None

class Spanned:
    token: CifToken
    span: tuple[int, int, int, int]

class CifLexer:
    def __init__(self, data: bytes) -> None: ...
    position: tuple[int, int, int]
    def __len__(self) -> int: ...
    def next_token(self) -> Spanned | None: ...
    def remaining(self) -> int: ...

class Rows:
    def __init__(self, category: Category) -> None: ...
    category: Category
    row: int
    def advance(self) -> bool: ...
    def value(self, item: str) -> CifValue | None: ...
    def text(self, item: str) -> str | None: ...
    def identifier(self, item: str) -> str | None: ...
    def integer(self, item: str) -> int | None: ...
    def float(self, item: str) -> float | None: ...
    def is_recorded(self, item: str) -> bool: ...

class CifValue:
    def __init__(self, text: str, quoting: Quoting) -> None: ...
    @staticmethod
    def parse(text: str, quoting: Quoting) -> CifValue: ...
    @staticmethod
    def inapplicable() -> CifValue: ...
    @staticmethod
    def unknown() -> CifValue: ...
    @staticmethod
    def text_value(value: str) -> CifValue: ...
    @staticmethod
    def integer_value(value: int) -> CifValue: ...
    @staticmethod
    def float_value(value: float) -> CifValue: ...
    kind: str
    text: str | None
    number: float | None
    def as_str(self) -> str | None: ...
    def as_integer(self) -> int | None: ...
    def as_float(self) -> float | None: ...
    def as_identifier(self) -> str | None: ...
    def is_recorded(self) -> bool: ...

class CifWriteError(ValueError):
    pass

class CifWriteOptions:
    def __init__(self, *, block_id: str | None = ..., generate_connection_ids: bool = ..., connection_type: str | None = ...) -> None: ...
    @staticmethod
    def standard() -> CifWriteOptions: ...
    block_id: str | None
    generate_connection_ids: bool
    connection_type: str | None
    def with_block_id(self, block_id: str) -> CifWriteOptions: ...
    def with_generated_connection_ids(self) -> CifWriteOptions: ...
    def with_connection_type_id(self, value: str) -> CifWriteOptions: ...

class Column:
    def __init__(self, values: list[tuple[CifValue, Quoting]] | None = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> CifValue | None: ...
    def push(self, value: CifValue, quoting: Quoting) -> None: ...
    def get(self, row: int) -> CifValue | None: ...
    def quoting(self, row: int) -> Quoting | None: ...
    @property
    def is_empty(self) -> bool: ...
    values: list[CifValue]

class Category:
    def __init__(self, name: str, span: tuple[int, int, int, int] | None = ...) -> None: ...
    name: str
    row_count: int
    len: int
    is_empty: bool
    span: tuple[int, int, int, int]
    items: list[str]
    def column(self, item: str) -> Column | None: ...
    def column_mut(self, item: str) -> Column | None: ...
    def rows(self) -> Rows: ...
    def push(self, item: str, value: CifValue, quoting: Quoting) -> None: ...
    def value(self, item: str, row: int) -> CifValue | None: ...
    def text(self, item: str, row: int) -> str | None: ...
    def identifier(self, item: str, row: int) -> str | None: ...

class DataBlock:
    def __init__(self, name: str) -> None: ...
    name: str
    categories: list[Category]
    len: int
    is_empty: bool
    def category(self, name: str) -> Category | None: ...
    def category_mut(self, name: str) -> Category | None: ...
    def add_category(self, category: Category) -> None: ...
    def push(self, category: str, item: str, value: CifValue, quoting: Quoting, span: tuple[int, int, int, int] | None = ...) -> None: ...

class Document:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    is_empty: bool
    blocks: list[DataBlock]
    def push(self, block: DataBlock) -> None: ...
    def first_block(self) -> DataBlock | None: ...
    def last_block(self) -> DataBlock | None: ...
    def last_block_mut(self) -> DataBlock | None: ...

class CifReader:
    def __init__(self) -> None: ...
    @staticmethod
    def parse(data: bytes) -> tuple[Document, list[Diagnostic]]: ...
    @staticmethod
    def read(data: bytes, options: ReadOptions | None = ...) -> ReadReport: ...
    @staticmethod
    def read_with_document(data: bytes, options: ReadOptions | None = ...) -> tuple[Document, ReadReport]: ...

def parse(data: bytes) -> tuple[Document, list[Diagnostic]]: ...
def read(data: bytes, options: ReadOptions | None = ...) -> ReadReport: ...
def read_with_document(data: bytes, options: ReadOptions | None = ...) -> tuple[Document, ReadReport]: ...
def split_tag(tag: str) -> tuple[str, str]: ...
def quote_text(text: str) -> str: ...
def render_value(value: CifValue) -> str: ...
def write_canonical(structure: object, options: CifWriteOptions | None = ...) -> str: ...
def write_canonical_with_options(structure: object, options: CifWriteOptions) -> str: ...
def read_document(path: str | PathLike[str]) -> Document: ...
def write_preserving(document: Document) -> str: ...
class SmallCifAtom:
    label: str
    type_symbol: str
    fractional: tuple[float, float, float] | None
    cartesian: tuple[float, float, float] | None
    occupancy: float | None
    u_iso: float | None
    charge: str | None
class SmallCifBond:
    first: int
    second: int
    distance: float | None
    site_symmetry: str | None
    bond_type: str | None
class SmallCifStructure:
    name: str
    cell: object | None
    space_group_name: str | None
    space_group_number: int | None
    symmetry_operations: list[str]
    atoms: list[SmallCifAtom]
    bonds: list[SmallCifBond]
class SmallCifDialect:
    Ddl2: SmallCifDialect
    Ddl1: SmallCifDialect
class SmallCifOptions:
    def __init__(self, dialect: SmallCifDialect = ...) -> None: ...
    @staticmethod
    def ddl1() -> SmallCifOptions: ...
    @staticmethod
    def ddl2() -> SmallCifOptions: ...
class SmallCifError(ValueError): ...
class PdbmlError(ValueError): ...
class PdbmlReadError(ValueError): ...
def lower(document: Document, options: ReadOptions | None = ...) -> ReadReport: ...
def cif_lower(document: Document, options: ReadOptions | None = ...) -> ReadReport: ...
def lower_small_cif(document: Document) -> SmallCifStructure: ...
def lower_small_cif_with_options(document: Document, options: SmallCifOptions) -> SmallCifStructure: ...
def parse_pdbml_document(bytes: bytes) -> Document: ...
def read_pdbml(bytes: bytes, options: ReadOptions | None = ...) -> tuple[Document, ReadReport]: ...
def write_pdbml(document: Document) -> str: ...
