[package]
name = "pdbiox-traj"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Trajectory frames and formats for pdbiox"

[dependencies]
hoomd-gsd.workspace = true
hdf5-reader.workspace = true
hdf5-writer.workspace = true
molly.workspace = true
nalgebra.workspace = true
netcdf-reader.workspace = true
netcdf-writer.workspace = true
num-traits.workspace = true
pdbiox-core.workspace = true
pdbiox-geom.workspace = true
pdbiox-query.workspace = true
pdbiox-spatial.workspace = true
quick-xml.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
tng-rs.workspace = true

[dev-dependencies]
pdbiox-cif.workspace = true
tempfile.workspace = true

[lints]
workspace = true
