[package]
name = "pdbiox-pdb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Legacy PDB reading and writing for pdbiox"

[dependencies]
num-traits.workspace = true
pdbiox-core.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_bytes.workspace = true

[dev-dependencies]
pdbiox-cif.workspace = true
proptest.workspace = true

[lints]
workspace = true
