[package]
name = "pdbiox-pdb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Legacy PDB reading and writing for pdbiox"

[dependencies]
pdbiox-core.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
