[package]
name = "pdbiox-geom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Geometric kernels for pdbiox"

[dependencies]
num-traits.workspace = true

[dev-dependencies]
criterion.workspace = true
pdbiox-bench.workspace = true

[[bench]]
name = "geom"
harness = false

[lints]
workspace = true
