//! Package-level namespace additions kept with their canonical native domain.
//!
//! The base namespace contracts mirror the facade crate aliases.  These entries
//! are public subdomain values that share the same domain but are registered by
//! a neighbouring facade module.  Keeping the routing here prevents Python
//! packages from importing the extension root and accidentally re-exporting
//! unrelated capabilities.

pub(super) const ANALYSIS: &[&str] = &[
    "BasePair",
    "BasePairOptions",
    "CartesianAxis",
    "Clustering",
    "Contacts",
    "ConvergenceBlock",
    "DensityGrid",
    "DensityGridSpec",
    "EnsembleDistanceMatrix",
    "FragmentMatch",
    "FragmentReference",
    "FrameAlignment",
    "GaussianNetworkModel",
    "GnmOptions",
    "GroupVariance",
    "HalfSphereExposure",
    "HarmonicSimilarity",
    "HarmonicSimilarityOptions",
    "KMeans",
    "KMeansOptions",
    "LinearDensityBin",
    "Linkage",
    "NativeContacts",
    "NucleicTorsions",
    "Pucker",
    "RadialBin",
    "RadialOptions",
    "RemainderPolicy",
    "ResidueContact",
    "SseRecord",
    "StackingKind",
    "SurfaceContactOptions",
    "analyse_agglomerative_clustering",
    "analyse_block_convergence",
    "analyse_cluster_population_similarity",
    "analyse_dbscan_clustering",
    "analyse_generalized_procrustes_mean",
    "analyse_group_coordinate_variance",
    "analyse_harmonic_ensemble_similarity",
    "analyse_kmeans",
    "analyse_medoid",
    "analyse_pairwise_fitted_rmsd",
    "analyse_pairwise_torus_distance",
    "analyse_rmsd_to_reference",
    "linear_density_with_options",
    "map_fragments",
    "polymer_statistics",
    "pore_profile",
    "sugar_pucker",
];

pub(super) const COMPARE: &[&str] = &[
    "CadContact",
    "CadScore",
    "CeSignificanceProfile",
    "ChainAlternative",
    "ChainAssignment",
    "ChainMapping",
    "ChainSequence",
    "ContactArea",
    "ContactSimilarity",
    "EmptyLddtPolicy",
    "EmptyQsPolicy",
    "EquivalentAtomMapping",
    "LigandRmsd",
    "LocalCad",
    "ResidueMatch",
    "analyse_cad_score",
    "analyse_cad_contact_areas",
    "analyse_contact_map_similarity",
    "analyse_ce_align",
    "analyse_ce_alignments",
    "analyse_dockq",
    "analyse_equivalent_atom_mappings",
    "analyse_gdt",
    "analyse_gdt_ha",
    "analyse_gdt_ts",
    "analyse_lddt",
    "analyse_ligand_symmetry_rmsd",
    "analyse_map_chains",
    "analyse_map_sequence_to_structure",
    "analyse_qs_score",
    "analyse_tm_score",
    "analyse_assign_chains",
    "analyse_weighted_rmsd",
    "assign_chains",
    "cad_contact_areas",
    "ligand_symmetry_rmsd",
];

pub(super) const VALIDATE: &[&str] = &[
    "AltlocOccupancyError",
    "AltlocOccupancyIssue",
    "AltlocOccupancyKernelError",
    "AltlocOccupancyOptions",
    "AltlocOccupancyRecord",
    "AltlocOccupancyReport",
    "BFactorError",
    "BFactorDistribution",
    "BFactorKernelError",
    "BFactorOutlier",
    "CcdCompletenessKernelError",
    "CcdCompletenessReport",
    "ChainCompleteness",
    "ChiralityFlag",
    "ChiralityIssue",
    "ChiralityOptions",
    "ChiralityReport",
    "CompletenessError",
    "GovernedMapError",
    "LigandGeometryKernelError",
    "LigandGeometryReport",
    "NucleicGeometryError",
    "NucleicGeometryIssue",
    "NucleicGeometryPolicy",
    "NucleicGeometryRecord",
    "PlanarityError",
    "PlanarityOptions",
    "PlaneRestraint",
    "PlaneRestraintFlag",
    "PlaneRestraintKernelError",
    "PlaneRestraintReport",
    "QualityFlag",
    "QualityIssue",
    "RamachandranBasin",
    "RamachandranError",
    "RamachandranOptions",
    "RamachandranRecord",
    "RamachandranRegion",
    "RealSpaceCorrelation",
    "RealSpaceCorrelationError",
    "ReferenceAngleFlag",
    "ReferenceBondFlag",
    "ReferenceError",
    "ReferenceAssessment",
    "ReferenceDistribution",
    "ReferenceGeometryOptions",
    "ReferenceGeometryReport",
    "ReferenceLibrary",
    "ResidueAtomCompleteness",
    "RotamerDefinition",
    "RotamerError",
    "RotamerFlag",
    "RotamerOptions",
    "RotamerProfile",
    "RotamerReport",
    "TlsBFactorFlag",
    "TlsBFactorReport",
    "TlsGroup",
    "TlsModel",
    "altloc_occupancy_sums",
    "analyse_altloc_occupancy",
    "analyse_b_factor_distribution",
    "analyse_ccd_completeness",
    "analyse_plane_restraints",
    "analyse_tls_b_factor_consistency",
    "assess_bond_deviation",
    "assess_ramachandran",
    "b_factor_distribution",
    "bond_length_deviations",
    "ccd_missing_atoms",
    "chirality_outliers",
    "cis_peptides",
    "clashes",
    "classify",
    "completeness",
    "governed_masked_real_space_correlation",
    "governed_real_space_map_correlation",
    "governed_sampled_real_space_correlation",
    "ligand_geometry",
    "ligand_geometry_outliers",
    "masked_real_space_correlation",
    "nonplanar_aromatic_rings",
    "nucleic_acid_geometry",
    "overvalent_atoms",
    "plane_restraint_outliers",
    "quality_flags",
    "ramachandran",
    "ramachandran_outliers",
    "real_space_map_correlation",
    "reference_geometry",
    "rotamer_outliers",
    "sampled_real_space_correlation",
    "tls_b_factor_consistency",
    "validate_altloc_occupancy",
    "validate_cis_peptides",
    "validate_completeness",
    "validate_ccd_completeness",
    "validate_planarity",
    "validate_plane_restraints",
    "validate_quality",
    "validate_valence",
];

pub(super) const TRAJ: &[&str] = &[
    "CartesianFit",
    "Clustering",
    "ConvergenceBlock",
    "DielectricError",
    "DmsError",
    "EnsembleDistanceMatrix",
    "EnsembleGeometryError",
    "EnsembleSimilarityError",
    "EnsembleStatisticsError",
    "FrameAlignment",
    "GovernedEnsembleError",
    "GroupVariance",
    "HarmonicSimilarity",
    "HarmonicSimilarityOptions",
    "ImdError",
    "KMeans",
    "KMeansError",
    "KMeansOptions",
    "Linkage",
    "MsdError",
    "PathSimilarityError",
    "PeriodicAngle",
    "RemainderPolicy",
    "Rotation3",
    "SurfaceGridOptions",
    "SurfaceMesh",
    "TrajectoryError",
    "TrajectoryIoError",
    "UpdatingSelectionError",
    "WaterDynamicsError",
    "analyse_agglomerative_clustering",
    "analyse_diffusion",
    "analyse_block_convergence",
    "analyse_cluster_population_similarity",
    "analyse_dbscan_clustering",
    "analyse_generalized_procrustes_mean",
    "analyse_group_coordinate_variance",
    "analyse_harmonic_ensemble_similarity",
    "analyse_kmeans",
    "analyse_medoid",
    "analyse_pairwise_fitted_rmsd",
    "analyse_pairwise_torus_distance",
    "analyse_pca",
    "analyse_rmsd_to_reference",
    "analyse_torsion_pca",
    "surface_mesh",
    "torsion_pca",
];

pub(super) const COMPARE_CHILDREN: &[&str] = &["region", "workflow", "superposed"];

pub(super) const TRAJ_ALIASES: &[(&str, &str)] = &[
    ("DielectricOptions", "TrajectoryDielectricOptions"),
    (
        "dielectric_from_dipoles",
        "trajectory_dielectric_from_dipoles",
    ),
    ("water_dynamics", "trajectory_water_dynamics"),
];

pub(super) const TRAJ_ALIAS_NAMES: &[&str] = &[
    "DielectricOptions",
    "dielectric_from_dipoles",
    "water_dynamics",
];

pub(super) fn for_namespace(name: &str) -> &'static [&'static str] {
    match name {
        "analysis" => ANALYSIS,
        "compare" => COMPARE,
        "validate" => VALIDATE,
        "traj" => TRAJ,
        _ => &[],
    }
}

pub(super) fn children(name: &str) -> &'static [&'static str] {
    match name {
        "compare" => COMPARE_CHILDREN,
        _ => &[],
    }
}

pub(super) fn aliases(name: &str) -> &'static [(&'static str, &'static str)] {
    match name {
        "traj" => TRAJ_ALIASES,
        _ => &[],
    }
}

pub(super) fn alias_names(name: &str) -> &'static [&'static str] {
    match name {
        "traj" => TRAJ_ALIAS_NAMES,
        _ => &[],
    }
}
