#!/usr/bin/env python3
"""Generate exact element tables from a pinned mendeleev SQLite database."""

from __future__ import annotations

import argparse
import re
import sqlite3
import struct
from pathlib import Path


IONIC_MAGIC = b"PDBXIR01"


def rust_float(value: float) -> str:
    formatted = f"{value:.6g}"
    return formatted if any(marker in formatted for marker in ".eE") else formatted + ".0"


def optional(value: float | None, scale: float = 1.0) -> str:
    return "None" if value is None else f"Some({rust_float(value * scale)})"


def valence(configuration: str, block: str, period: int) -> int:
    orbitals: dict[tuple[int, str], int] = {}
    for principal, orbital, occupancy in re.findall(r"(\d)([spdf])(\d*)", configuration):
        orbitals[(int(principal), orbital)] = int(occupancy or "1")
    if block in {"s", "p"}:
        maximum = max(level for level, _ in orbitals)
        return sum(count for (level, _), count in orbitals.items() if level == maximum)
    if block == "d":
        return orbitals.get((period, "s"), 0) + orbitals.get((period - 1, "d"), 0)
    if block == "f":
        return (
            orbitals.get((period, "s"), 0)
            + orbitals.get((period, "p"), 0)
            + orbitals.get((period - 1, "d"), 0)
            + orbitals.get((period - 2, "f"), 0)
        )
    raise ValueError(f"unknown block {block!r}")


def rust_table(connection: sqlite3.Connection) -> str:
    columns = (
        "atomic_number, symbol, covalent_radius_pyykko, en_pauling, period, "
        "group_id, electronic_configuration, block, vdw_radius_bondi, "
        "vdw_radius_alvarez"
    )
    rows = connection.execute(f"SELECT {columns} FROM elements ORDER BY atomic_number")
    output = [
        "//! Generated by scripts/generate-elements.py from mendeleev 1.1.0.",
        "",
        "use crate::element::RawElement;",
        "",
        "pub(super) const ELEMENTS: [RawElement; 119] = [",
        "    RawElement::EMPTY,",
    ]
    count = 0
    for z, symbol, covalent, en, period, group, configuration, block, bondi, alvarez in rows:
        count += 1
        output.append(
            "    RawElement::new("
            f"{rust_float(covalent / 100)}, {optional(en)}, {period}, {group or 0}, "
            f"{valence(configuration, block, period)}, {optional(bondi, 0.01)}, "
            f"{optional(alvarez, 0.01)}), // {z} {symbol}"
        )
    if count != 118:
        raise RuntimeError(f"expected 118 elements, found {count}")
    output.extend(["];"])
    return "\n".join(output) + "\n"


def packed_text(value: str | None) -> bytes:
    encoded = (value or "").encode("ascii")
    if len(encoded) > 255:
        raise ValueError("ionic-radius label exceeds one-byte length")
    return bytes([len(encoded)]) + encoded


def ionic_table(connection: sqlite3.Connection) -> bytes:
    rows = list(
        connection.execute(
            "SELECT atomic_number, charge, coordination, spin, ionic_radius, "
            "crystal_radius, most_reliable FROM ionicradii "
            "ORDER BY atomic_number, charge, coordination, spin"
        )
    )
    output = bytearray(IONIC_MAGIC)
    output.extend(struct.pack("<H", len(rows)))
    for z, charge, coordination, spin, ionic, crystal, reliable in rows:
        output.extend(struct.pack("<Bb", z, charge))
        output.extend(packed_text(coordination))
        output.extend(packed_text(spin))
        reliability = 2 if reliable is None else int(reliable)
        output.extend(struct.pack("<ffB", ionic / 100, crystal / 100, reliability))
    return bytes(output)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("database", type=Path)
    parser.add_argument("rust_output", type=Path)
    parser.add_argument("ionic_output", type=Path)
    args = parser.parse_args()
    connection = sqlite3.connect(args.database)
    args.rust_output.write_text(rust_table(connection))
    args.ionic_output.write_bytes(ionic_table(connection))
    print(args.rust_output, args.ionic_output)


if __name__ == "__main__":
    main()
