[package]
name = "pdbiox-validate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Geometric and completeness validation for pdbiox"

[dependencies]
num-traits.workspace = true
pdbiox-core.workspace = true
pdbiox-analysis.workspace = true
pdbiox-chem.workspace = true
pdbiox-geom.workspace = true
pdbiox-spatial.workspace = true
pdbiox-xtal.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
pdbiox-bench.workspace = true
pdbiox-cif.workspace = true

[[bench]]
name = "validate"
harness = false

[lints]
workspace = true
