from os import PathLike
from typing import final, Mapping
from . import Structure
from .._io_types import DatasetError, DlpackError, GraphError, LoadError, TableFileError
from .graph import EdgeDirection, EdgeFeature, EdgeKind, Graph, GraphOptions, MissingFeaturePolicy, NodeFeature, NodeLevel, SpatialBackend
from . import graph

@final
class ArrowStream:
    consumed: bool
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
    def __repr__(self) -> str: ...

@final
class AtomArrowTable:
    def __init__(self, structure: Structure) -> None: ...
    def schema(self) -> object: ...
    def record_batches(self) -> list[object]: ...
    def arrow_stream(self) -> ArrowStream: ...
    def __repr__(self) -> str: ...

@final
class ResidueArrowTable:
    def __init__(self, structure: Structure) -> None: ...
    def schema(self) -> object: ...
    def record_batches(self) -> list[object]: ...
    def arrow_stream(self) -> ArrowStream: ...
    def __repr__(self) -> str: ...

@final
class ChainArrowTable:
    def __init__(self, structure: Structure) -> None: ...
    def schema(self) -> object: ...
    def record_batches(self) -> list[object]: ...
    def arrow_stream(self) -> ArrowStream: ...
    def __repr__(self) -> str: ...

@final
class BondArrowTable:
    def __init__(self, structure: Structure) -> None: ...
    def schema(self) -> object: ...
    def record_batches(self) -> list[object]: ...
    def arrow_stream(self) -> ArrowStream: ...
    def __repr__(self) -> str: ...

AtomTable = AtomArrowTable
BondTable = BondArrowTable
ChainTable = ChainArrowTable
ResidueTable = ResidueArrowTable

@final
class DLDevice:
    def __init__(self, device_type: int, device_id: int) -> None: ...
    device_type: int
    device_id: int

@final
class DLDataType:
    def __init__(self, code: int, bits: int, lanes: int) -> None: ...
    code: int
    bits: int
    lanes: int

@final
class DLTensor:
    def __init__(self, data_address: int, device: DLDevice, ndim: int, dtype: DLDataType, shape: list[int], *, strides: list[int] | None = None, byte_offset: int = 0) -> None: ...
    data_address: int
    device: DLDevice
    ndim: int
    dtype: DLDataType
    shape: list[int]
    strides: list[int] | None
    byte_offset: int

@final
class DLManagedTensor:
    tensor: DLTensor
    manager_context_address: int
    has_deleter: bool

@final
class DlpackTensor:
    @staticmethod
    def coordinates(structure: Structure) -> DlpackTensor: ...
    cost: ExportCost
    managed: DLManagedTensor | None
    consumed: bool
    def capsule(self) -> object: ...

@final
class ExportCost:
    ZeroCopy: ExportCost
    Decode: ExportCost
    Copy: ExportCost
    label: str

@final
class MolframeExtension:
    AtomIndex: MolframeExtension
    ResidueIndex: MolframeExtension
    ChainIndex: MolframeExtension
    EntityIndex: MolframeExtension
    Coordinates3f: MolframeExtension
    Element: MolframeExtension
    SymbolId: MolframeExtension
    Altloc: MolframeExtension
    Selection: MolframeExtension
    Validity: MolframeExtension
    name: str
    storage_type: str

@final
class DatasetEntry:
    def __init__(self, id: str, path: str | PathLike[str], atom_count: int, *, resolution: float | None = None, method: str | None = None, deposition_date: str | None = None, sequence: str | None = None, structure_cluster: str | None = None, tags: list[str] = [], statistics: dict[str, float] | None = None) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def path(self) -> PathLike[str]: ...
    @property
    def atom_count(self) -> int: ...
    @property
    def resolution(self) -> float | None: ...
    @property
    def method(self) -> str | None: ...
    @property
    def deposition_date(self) -> str | None: ...
    @property
    def sequence(self) -> str | None: ...
    @property
    def structure_cluster(self) -> str | None: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def statistics(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...

ManifestEntry = DatasetEntry

@final
class DatasetFilter:
    def __init__(self, *, resolution_below: float | None = None, method: str | None = None, minimum_atoms: int | None = None, maximum_atoms: int | None = None, tag: str | None = None) -> None: ...
    resolution_below: float | None
    method: str | None
    minimum_atoms: int | None
    maximum_atoms: int | None
    tag: str | None

@final
class SplitRatios:
    def __init__(self, train: float, validation: float, test: float) -> None: ...
    train: float
    validation: float
    test: float
    def __repr__(self) -> str: ...

@final
class SplitOptions:
    def __init__(self, strategy: SplitStrategy, *, ratios: SplitRatios | None = None, train: float = 0.8, validation: float = 0.1, test: float = 0.1) -> None: ...
    strategy: SplitStrategy
    ratios: SplitRatios

@final
class SplitStrategy:
    @staticmethod
    def sequence_identity(threshold: float) -> SplitStrategy: ...
    @staticmethod
    def structural_cluster() -> SplitStrategy: ...
    @staticmethod
    def temporal() -> SplitStrategy: ...
    @staticmethod
    def random(seed: int) -> SplitStrategy: ...

@final
class DatasetWarning:
    RandomSplitMayLeak: DatasetWarning

@final
class Dataset:
    def __init__(self, path: str | PathLike[str]) -> None: ...
    @staticmethod
    def from_entries(entries: list[DatasetEntry]) -> Dataset: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __getitem__(self, index: int) -> DatasetEntry: ...
    def load(self, index: int) -> Structure: ...
    def filter(
        self,
        *,
        resolution_below: float | None = None,
        method: str | None = None,
        minimum_atoms: int | None = None,
        maximum_atoms: int | None = None,
        tag: str | None = None,
    ) -> Dataset: ...
    def filter_spec(self, filter: DatasetFilter) -> Dataset: ...
    def split(
        self,
        strategy: SplitStrategy,
        *,
        train: float = 0.8,
        validation: float = 0.1,
        test: float = 0.1,
    ) -> DatasetSplit: ...
    def split_options(self, options: SplitOptions) -> DatasetSplit: ...
    def batches(self, batch_size: int) -> list[Dataset]: ...

@final
class DatasetSplit:
    @property
    def train(self) -> Dataset: ...
    @property
    def validation(self) -> Dataset: ...
    @property
    def test(self) -> Dataset: ...
    @property
    def warnings(self) -> list[DatasetWarning]: ...

def write_atom_ipc(path: str | PathLike[str], structure: Structure) -> None: ...
def write_atom_ipc_with_metadata(path: str | PathLike[str], structure: Structure, *, metadata: Mapping[str, str] | None = None) -> None: ...
def write_atom_parquet(path: str | PathLike[str], structure: Structure) -> None: ...
def write_atom_parquet_with_metadata(path: str | PathLike[str], structure: Structure, *, metadata: Mapping[str, str] | None = None) -> None: ...
def extension_name(metadata: dict[str, str]) -> str | None: ...
def build_graph(structure: Structure, options: object) -> object: ...
