from __future__ import annotations
from typing import Protocol

class Array(Protocol):
    @property
    def shape(self) -> tuple[int, ...]: ...

def tm_score(model: Array, reference: Array) -> float: ...
def gdt_ts(model: Array, reference: Array) -> float: ...
def gdt_ha(model: Array, reference: Array) -> float: ...
def weighted_rmsd(model: Array, reference: Array, weights: Array) -> float: ...
