from numpy import float32
from numpy.typing import NDArray
from .._native.compare import *
from .._native.compare import __all__
from . import region, superposed, workflow
from .._io_types import MolframeError

class Rmsd:
    def __init__(self, *, mobile: NDArray[float32], reference: NDArray[float32]) -> None: ...
    def execute(self) -> float: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Rmsd: ...
    def __repr__(self) -> str: ...

class Lddt:
    def __init__(self, *, mobile: NDArray[float32], reference: NDArray[float32], inclusion_radius: float = ...) -> None: ...
    def execute(self) -> float: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> Lddt: ...
    def __repr__(self) -> str: ...

class TmScore:
    def __init__(self, *, mobile: NDArray[float32], reference: NDArray[float32]) -> None: ...
    def execute(self) -> float: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> TmScore: ...
    def __repr__(self) -> str: ...

class GdtTs:
    def __init__(self, *, mobile: NDArray[float32], reference: NDArray[float32]) -> None: ...
    def execute(self) -> float: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> GdtTs: ...
    def __repr__(self) -> str: ...

class GdtHa:
    def __init__(self, *, mobile: NDArray[float32], reference: NDArray[float32]) -> None: ...
    def execute(self) -> float: ...
    def explain(self) -> dict[str, object]: ...
    def to_dict(self) -> dict[str, object]: ...
    @staticmethod
    def from_dict(config: dict[str, object]) -> GdtHa: ...
    def __repr__(self) -> str: ...

class CompareError(MolframeError): ...
class CadError(MolframeError): ...
class CadConstructionError(MolframeError): ...
class CeError(MolframeError): ...
class GovernedCompareError(MolframeError): ...
