from .._trajectory import Timestep

class TrzError(Exception): ...
class TrzTrajectory:
    def __init__(self, title: str, has_forces: bool, frames: list[Timestep]) -> None: ...
    title: str
    has_forces: bool
    frames: list[Timestep]
def parse_trz(bytes: bytes) -> TrzTrajectory: ...
def write_trz(trajectory: TrzTrajectory) -> bytes: ...
